"""Extract the public ZarPrune API (declaration signatures + doc comments) into
lean/API.md, and a compact one-line-per-item digest for LLM prompts.

  python -m zar_ub.lean_api            # writes lean/API.md and prints the digest
  python -m zar_ub api --docstring initial_program.py   # rewrites the LEAN API block of the docstring
"""
from __future__ import annotations

import os
import re
import textwrap
from typing import List, Tuple

_HERE = os.path.dirname(os.path.abspath(__file__))
LEAN_DIR = os.path.join(os.path.dirname(_HERE), "lean", "ZarPrune")
_DECL = re.compile(r"^(@\[[^\]]*\]\s*)?(private\s+)?(theorem|def|abbrev|structure|lemma|instance)\s+([\w.']+)")


def _statement(text: str) -> str:
    """Cut a declaration line at the first top-level ` := ` / `where` (a `:=` inside `{P with w := w'}`
    or a parenthesised default value does not end the statement)."""
    depth = 0
    i = 0
    while i < len(text):
        ch = text[i]
        if ch in "({[⟨":
            depth += 1
        elif ch in ")}]⟩":
            depth = max(0, depth - 1)
        elif depth == 0:
            if text.startswith(" := ", i) or text.endswith(" :=", ) and i == len(text) - 3:
                return text[:i].strip()
            if re.match(r"\swhere\b", text[i:]):
                return text[:i].strip()
        i += 1
    return text.strip()


def extract(path: str) -> List[Tuple[str, str, str]]:
    """Return (kind, name, signature) for each top-level declaration."""
    out = []
    lines = open(path).read().splitlines()
    i = 0
    in_comment = False
    while i < len(lines):
        l = lines[i]
        if in_comment:
            if "-/" in l:
                in_comment = False
            i += 1
            continue
        if l.lstrip().startswith("/-") and "-/" not in l:
            in_comment = True
            i += 1
            continue
        m = _DECL.match(l)
        if m and not m.group(2):
            kind, name = m.group(3), m.group(4)
            sig = [l]
            j = i + 1
            # collect until the first line that ends the statement (':=' or 'where' or a blank line)
            while j < len(lines) and not re.search(r"(:=|\bwhere\b)\s*(by)?\s*$", sig[-1]) and ":=" not in sig[-1] and lines[j].strip() and not _DECL.match(lines[j]):
                sig.append(lines[j]); j += 1
            text = " ".join(s.strip() for s in sig)
            text = _statement(text)
            if kind == "structure" or kind == "instance":
                text = " ".join(s.strip() for s in sig[:1])
            out.append((kind, name, re.sub(r"\s+", " ", text)))
        i += 1
    return out


def build(files: List[str] | None = None) -> Tuple[str, str]:
    files = files or sorted(f for f in os.listdir(LEAN_DIR) if f.endswith(".lean") and f != "Demo.lean")
    md = ["# ZarPrune API (auto-generated by zar_ub.lean_api)", ""]
    digest = []
    for f in files:
        items = extract(os.path.join(LEAN_DIR, f))
        md.append(f"## {f}\n")
        for kind, name, sig in items:
            md.append(f"- `{sig}`")
            digest.append(f"{name}: {sig.split(name, 1)[1].strip() if name in sig else sig}")
        md.append("")
    text = "\n".join(md)
    with open(os.path.join(os.path.dirname(LEAN_DIR), "API.md"), "w") as fh:
        fh.write(text + "\n")
    return text, "\n".join(digest)


# --------------------------------------------------------------------------------------
# The docstring block of initial_program.py (design §2.2): regenerated from the Lean sources
# --------------------------------------------------------------------------------------
MODULE_ORDER = ["Basic", "Sum", "Prune", "Prunes", "Counting", "Cond", "Schemas", "DGH"]
#: statements the prompt quotes in full (the load-bearing lemmas for new prunes)
KEY_STATEMENTS = ["colBudget", "rowBudget", "rowLocalBudget", "valid_deleteCol_bound", "sum_le_waterfillBound",
                  "argDelCol", "argDelColF", "Prune.ofPrefixF", "discharge", "ZarPrune.Prune.mono",
                  "pairLocalBudget", "codeg_le_cap", "floor_le_codeg", "sum_codeg_row", "lowSum_le",
                  "Prune.ofFarkas", "dghBudget", "argDGH"]
BLOCK_START = "LEAN API ("
BLOCK_END = "Pattern for a new prune"


def docstring_block(width: int = 110) -> str:
    """The `LEAN API (...)` block: per-module name inventory + key statements, from the sources."""
    inv, sigs = {}, {}
    for mod in MODULE_ORDER:
        path = os.path.join(LEAN_DIR, mod + ".lean")
        if not os.path.exists(path):
            continue
        items = extract(path)
        inv[mod] = [n for _, n, _ in items]
        for kind, name, sig in items:
            sigs[name] = sig
    out = [BLOCK_START + "generated by `python -m zar_ub api --docstring initial_program.py` from lean/ZarPrune; "
           "lean/API.md has every signature;",
           "  Mathlib IS available through `import ZarPrune`):"]
    for mod, names in inv.items():
        head = f"  {mod + ':':10s}"
        body = textwrap.wrap(" ".join(names), width=width - len(head), break_long_words=False, break_on_hyphens=False)
        out.append(head + body[0])
        out.extend(" " * len(head) + b for b in body[1:])
    out.append("  Valid P A := ¬ HasKst P A ∧ P.w ≤ weight A  (so hv.1 : ¬ HasKst P A, hv.2 : P.w ≤ weight A);"
               " profileOf_row / profileOf_col are @[simp]")
    out.append("  Key statements:")
    for name in KEY_STATEMENTS:
        if name in sigs:
            sig = re.sub(r"^(theorem|def|lemma|abbrev)\s+", "", sigs[name])
            out.append("    " + sig)
    out.append("  Mathlib: Finset.sum_le_sum sum_comm card_filter powersetCard, Nat.choose lemmas, "
               "omega decide simp linarith nlinarith ring positivity")
    out.append("  Schemas (Schemas.lean, proved): `Prune.ofFarkas P ys` kills when some certificate y in ys refutes the "
               "pair-codegree system F1-F4 (see SCHEMA_DATA[\"farkas\"]); `Prune.ofResidue` is NOT in the library "
               "(SCHEMA_DATA[\"residue\"] / [\"prefix\"] must stay []).")
    out.append("  DGH (DGH.lean, proved for every (m,n;s,t)): `argDGH P` = the Davies-Gill-Horsley v = s-1 rounding "
               "inequality on both sides; it is a library lemma but NOT in the scoring baseline, so listing it "
               "earns credit only on the wide cells where it fires.")
    out.append("  Closure.lean / Evolved.lean: the closure seam (upper_bound_succ_of_condPrune) and the promoted "
               "library `evolved P` (already in the baseline); not for candidates.")
    out.append("  CondPrune entry point: besides `candidate` you may define "
               "`candidateF (P : Params) (facts : List Fact) : CondPrune P facts` (general) or "
               "`candidateF : CondPrune target [f1, ...]` (literal facts); the gate discharges it against the facts "
               "the run's ledger grants to each instance (none on pure/TRAIN tables; Tan's cited neighbours on "
               "tan2022 target tables) and falls back to `CondPrune.never` where a literal fact is not granted "
               "(artifact lean_cond).")
    return "\n".join(out)


def refresh_docstring(path: str, width: int = 110, start: str = BLOCK_START, end: str = BLOCK_END,
                      indent: str = "") -> bool:
    """Replace the block from the `LEAN API (` line up to (not including) the `Pattern for a new
    prune` line of the module docstring of `path` (config.yaml: `indent="    "`, `end="WORKED EXAMPLE"`).
    Returns True when the file changed."""
    with open(path, encoding="utf-8") as fh:
        text = fh.read()
    lines = text.split("\n")
    try:
        i = next(k for k, l in enumerate(lines) if l.startswith(indent + start))
        j = next(k for k, l in enumerate(lines) if k > i and l.startswith(indent + end))
    except StopIteration:
        raise ValueError(f"{path}: no `{start}` ... `{end}` block")
    block = [indent + l for l in docstring_block(width).split("\n")]
    if indent:  # a YAML block scalar keeps blank lines; keep one before the next paragraph
        block.append("")
    new = lines[:i] + block + lines[j:]
    new_text = "\n".join(new)
    if new_text != text:
        with open(path, "w", encoding="utf-8") as fh:
            fh.write(new_text)
        return True
    return False


if __name__ == "__main__":
    text, digest = build()
    print(digest)
