import ZarPrune
import Mathlib.Data.Fin.Tuple.Sort
import Mathlib.Data.List.Sort
import Mathlib.Data.List.OfFn

-- ===== inlined lean/ZarPrune/Closure.lean =====

/-!
# The cover seam (design §4.6): from "every listed case is refuted" to a bound

A closure file (`ZarPrune/Closures/Z_m_n_w.lean`, generated by `zar_ub/closure.py`)
proves `∀ A : Mat m n, ¬ HasKst P A → weight A ≤ w - 1` from

* a verified prune `p : Prune P` (library ∪ evolved ∪ conditional prunes),
* the facts the enumerator was allowed to use (`FactHolds f`, one hypothesis each),
* `survivors_eq : survivors P facts p = survList` (the only per-instance kernel
  computation: `decide`), and
* `Hrefuted : ∀ q ∈ survList, ∀ A, sortedProfileOf A = q → ¬ Valid P A` (the LRAT seam).

This module supplies the generic glue, in the order of design §4.6:

1. **Thinning** `lt_of_no_exact`: "no `K_{s,t}`-free matrix has exactly `w` ones" gives
   "every `K_{s,t}`-free matrix has fewer than `w` ones" (clear ones one at a time).
2. **Permutations** `act σ τ A`, with `weight_act`, `rowSum_act`, `colSum_act`,
   `hasKst_act_iff`.
3. **Sorting** `exists_sorted` (Mathlib `Tuple.sort`) and `sortedProfileOf A` (the
   non-increasing row-sum and column-sum lists, computed by `List.mergeSort`).
4. **Enumerator** `genParts` (Tan 2022, Algorithm 1: non-increasing lists, entries
   `≤ cap`, sum `= total`, `Σ choose xᵢ r ≤ budget`, proper prefix sums `≤ ub k`) with its
   completeness theorem `mem_genParts`; `genRows` / `genCols` instantiate it with the
   Argument A budgets and the prefix bounds read off a list of `Fact`s (Argument I).
5. **Survivors** `survivors P facts p` and the closure theorems `cover_of_survivors`,
   `upper_bound_succ_of_sorted_cover`.
6. `factHolds_of_waterfill_le` / `factHolds_of_waterfillT_le`: the pure-mode facts
   (waterfilled Argument A, both orientations) are discharged inside the closure file.

Gate: no `sorry`, no `native_decide`, no new axioms.
-/

set_option autoImplicit false

namespace ZarPrune

open Finset

/-! ## 1. Thinning -/

/-- Clear the cell `(i, j)`. -/
def clearCell {m n : Nat} (A : Mat m n) (i : Fin m) (j : Fin n) : Mat m n :=
  fun i' j' => if i' = i ∧ j' = j then false else A i' j'

theorem clearCell_le {m n : Nat} (A : Mat m n) (i : Fin m) (j : Fin n) :
    ∀ i' j', clearCell A i j i' j' = true → A i' j' = true := by
  intro i' j' h
  unfold clearCell at h
  split at h
  · exact absurd h Bool.false_ne_true
  · exact h

/-- A `K_{s,t}` survives adding ones. -/
theorem hasKst_mono {P : Params} {A B : Mat P.m P.n}
    (hAB : ∀ i j, A i j = true → B i j = true) (h : HasKst P A) : HasKst P B := by
  obtain ⟨R, C, hR, hC, hall⟩ := h
  exact ⟨R, C, hR, hC, fun a b => hAB _ _ (hall a b)⟩

theorem weight_eq_double_sum {m n : Nat} (A : Mat m n) :
    weight A = ∑ i, ∑ j, ind (A i j) := by
  rw [weight_eq_sum]
  exact Finset.sum_congr rfl (fun i _ => rowSum_eq_sum A i)

/-- Clearing a one drops the weight by exactly one. -/
theorem weight_clearCell {m n : Nat} (A : Mat m n) (i : Fin m) (j : Fin n) (h : A i j = true) :
    weight (clearCell A i j) + 1 = weight A := by
  rw [weight_eq_double_sum, weight_eq_double_sum]
  have key : ∀ i' j', ind (A i' j')
      = ind (clearCell A i j i' j') + (if j' = j then (if i' = i then 1 else 0) else 0) := by
    intro i' j'
    unfold clearCell
    by_cases hi : i' = i
    · by_cases hj : j' = j
      · subst hi; subst hj; simp [ind, h]
      · simp [hi, hj]
    · simp [hi]
  have e : ∑ i', ∑ j', ind (A i' j')
      = ∑ i', ∑ j', (ind (clearCell A i j i' j') + (if j' = j then (if i' = i then 1 else 0) else 0)) :=
    Finset.sum_congr rfl (fun i' _ => Finset.sum_congr rfl (fun j' _ => key i' j'))
  rw [e]
  simp only [Finset.sum_add_distrib, Finset.sum_ite_eq', Finset.mem_univ, ite_true]

theorem exists_true_of_weight_ne_zero {m n : Nat} (A : Mat m n) (h : weight A ≠ 0) :
    ∃ i j, A i j = true := by
  by_contra hcon
  apply h
  rw [weight_eq_double_sum]
  apply Finset.sum_eq_zero
  intro i _
  apply Finset.sum_eq_zero
  intro j _
  have : A i j = false := by
    cases hij : A i j
    · rfl
    · exact absurd ⟨i, j, hij⟩ hcon
  simp [ind, this]

/-- **Thinning (P19).**  If no `K_{s,t}`-free matrix has exactly `P.w` ones, every
`K_{s,t}`-free matrix has fewer than `P.w`: a heavier one could be thinned to weight
`P.w` one cell at a time without creating a `K_{s,t}`. -/
theorem lt_of_no_exact (P : Params) (h : ∀ A : Mat P.m P.n, ¬ HasKst P A → weight A ≠ P.w) :
    ∀ A : Mat P.m P.n, ¬ HasKst P A → weight A < P.w := by
  have key : ∀ d, ∀ A : Mat P.m P.n, ¬ HasKst P A → weight A = P.w + d → False := by
    intro d
    induction d with
    | zero => intro A hA hw; exact h A hA hw
    | succ d ih =>
      intro A hA hw
      obtain ⟨i, j, hij⟩ := exists_true_of_weight_ne_zero A (by omega)
      have hw' := weight_clearCell A i j hij
      exact ih (clearCell A i j) (fun hk => hA (hasKst_mono (clearCell_le A i j) hk)) (by omega)
  intro A hA
  by_contra hlt
  exact key (weight A - P.w) A hA (by omega)

/-! ## 2. Permutations -/

/-- Permute rows by `σ` and columns by `τ`. -/
def act {m n : Nat} (σ : Equiv.Perm (Fin m)) (τ : Equiv.Perm (Fin n)) (A : Mat m n) : Mat m n :=
  fun i j => A (σ i) (τ j)

theorem rowSum_act {m n : Nat} (σ : Equiv.Perm (Fin m)) (τ : Equiv.Perm (Fin n)) (A : Mat m n)
    (i : Fin m) : rowSum (act σ τ A) i = rowSum A (σ i) := by
  rw [rowSum_eq_sum, rowSum_eq_sum]
  exact Equiv.sum_comp τ (fun j => ind (A (σ i) j))

theorem colSum_act {m n : Nat} (σ : Equiv.Perm (Fin m)) (τ : Equiv.Perm (Fin n)) (A : Mat m n)
    (j : Fin n) : colSum (act σ τ A) j = colSum A (τ j) := by
  rw [colSum_eq_sum, colSum_eq_sum]
  exact Equiv.sum_comp σ (fun i => ind (A i (τ j)))

theorem weight_act {m n : Nat} (σ : Equiv.Perm (Fin m)) (τ : Equiv.Perm (Fin n)) (A : Mat m n) :
    weight (act σ τ A) = weight A := by
  rw [weight_eq_sum, weight_eq_sum]
  simp only [rowSum_act]
  exact Equiv.sum_comp σ (rowSum A)

theorem Incr.injective {k N : Nat} {f : Fin k → Fin N} (h : Incr f) : Function.Injective f := by
  intro a b hab
  by_contra hne
  rcases lt_or_gt_of_ne hne with hlt | hlt
  · exact absurd hab (ne_of_lt (h a b hlt))
  · exact absurd hab.symm (ne_of_lt (h b a hlt))

/-- A `K_{s,t}` in a permuted matrix is a `K_{s,t}` in the original (the image tuples are
re-indexed increasingly by `hasKst_of_subsets`). -/
theorem hasKst_of_act (P : Params) (σ : Equiv.Perm (Fin P.m)) (τ : Equiv.Perm (Fin P.n))
    (A : Mat P.m P.n) (h : HasKst P (act σ τ A)) : HasKst P A := by
  obtain ⟨R, C, hR, hC, hall⟩ := h
  refine hasKst_of_subsets P A (univ.image (fun a => σ (R a))) ?_
    (univ.image (fun b => τ (C b))) ?_ ?_
  · have hinj : Function.Injective (fun a => σ (R a)) :=
      fun a b hab => hR.injective (σ.injective hab)
    rw [Finset.card_image_of_injective univ hinj, Finset.card_univ, Fintype.card_fin]
  · have hinj : Function.Injective (fun b => τ (C b)) :=
      fun a b hab => hC.injective (τ.injective hab)
    rw [Finset.card_image_of_injective univ hinj, Finset.card_univ, Fintype.card_fin]
  · intro j hj i hi
    rw [Finset.mem_image] at hj hi
    obtain ⟨b, _, rfl⟩ := hj
    obtain ⟨a, _, rfl⟩ := hi
    exact (mem_support A _ _).mpr (hall a b)

theorem act_symm_act {m n : Nat} (σ : Equiv.Perm (Fin m)) (τ : Equiv.Perm (Fin n)) (A : Mat m n) :
    act σ.symm τ.symm (act σ τ A) = A := by
  funext i j
  simp [act]

theorem hasKst_act_iff (P : Params) (σ : Equiv.Perm (Fin P.m)) (τ : Equiv.Perm (Fin P.n))
    (A : Mat P.m P.n) : HasKst P (act σ τ A) ↔ HasKst P A :=
  ⟨hasKst_of_act P σ τ A, fun h =>
    hasKst_of_act P σ.symm τ.symm (act σ τ A) (by rw [act_symm_act]; exact h)⟩

theorem valid_act_iff (P : Params) (σ : Equiv.Perm (Fin P.m)) (τ : Equiv.Perm (Fin P.n))
    (A : Mat P.m P.n) : Valid P (act σ τ A) ↔ Valid P A := by
  unfold Valid
  rw [hasKst_act_iff, weight_act]

/-! ## 3. Sorting -/

/-- Sort a list of naturals into non-increasing order. -/
def sortDesc (l : List Nat) : List Nat := l.mergeSort (fun a b => decide (a ≥ b))

/-- The row sums of `A` as a list (index order). -/
def rowList {m n : Nat} (A : Mat m n) : List Nat := List.ofFn (rowSum A)

/-- The column sums of `A` as a list (index order). -/
def colList {m n : Nat} (A : Mat m n) : List Nat := List.ofFn (colSum A)

/-- The case index of `A`: its row sums and its column sums, each sorted non-increasingly.
This is the meaning of a case `(rows, cols)` handed to the SAT solver. -/
def sortedProfileOf {m n : Nat} (A : Mat m n) : List Nat × List Nat :=
  (sortDesc (rowList A), sortDesc (colList A))

theorem sortDesc_perm (l : List Nat) : (sortDesc l).Perm l := List.mergeSort_perm l _

theorem sortDesc_sortedGE (l : List Nat) : (sortDesc l).SortedGE := by
  apply List.Pairwise.sortedGE
  have h := List.pairwise_mergeSort (le := fun a b : Nat => decide (a ≥ b))
    (fun a b c hab hbc => by simp only [decide_eq_true_eq] at *; omega)
    (fun a b => by simp only [Bool.or_eq_true, decide_eq_true_eq]; omega) l
  exact h.imp (fun hab => of_decide_eq_true hab)

/-- Every matrix can be row- and column-permuted into one with non-increasing row sums
and non-increasing column sums (Mathlib's `Tuple.sort`, applied on the order dual). -/
theorem exists_sorted {m n : Nat} (A : Mat m n) :
    ∃ (σ : Equiv.Perm (Fin m)) (τ : Equiv.Perm (Fin n)),
      Antitone (rowSum (act σ τ A)) ∧ Antitone (colSum (act σ τ A)) := by
  refine ⟨Tuple.sort (OrderDual.toDual ∘ rowSum A), Tuple.sort (OrderDual.toDual ∘ colSum A),
    ?_, ?_⟩
  · have h := Tuple.monotone_sort (OrderDual.toDual ∘ rowSum A)
    rw [Function.comp_assoc, monotone_toDual_comp_iff] at h
    intro a b hab
    rw [rowSum_act, rowSum_act]
    exact h hab
  · have h := Tuple.monotone_sort (OrderDual.toDual ∘ colSum A)
    rw [Function.comp_assoc, monotone_toDual_comp_iff] at h
    intro a b hab
    rw [colSum_act, colSum_act]
    exact h hab

theorem rowList_act_perm {m n : Nat} (σ : Equiv.Perm (Fin m)) (τ : Equiv.Perm (Fin n))
    (A : Mat m n) : (rowList (act σ τ A)).Perm (rowList A) := by
  unfold rowList
  rw [List.ofFn_eq_map, List.ofFn_eq_map]
  have e : (List.finRange m).map (rowSum (act σ τ A))
      = ((List.finRange m).map σ).map (rowSum A) := by
    rw [List.map_map]
    exact List.map_congr_left (fun i _ => rowSum_act σ τ A i)
  rw [e]
  exact (σ.map_finRange_perm).map (rowSum A)

theorem colList_act_perm {m n : Nat} (σ : Equiv.Perm (Fin m)) (τ : Equiv.Perm (Fin n))
    (A : Mat m n) : (colList (act σ τ A)).Perm (colList A) := by
  unfold colList
  rw [List.ofFn_eq_map, List.ofFn_eq_map]
  have e : (List.finRange n).map (colSum (act σ τ A))
      = ((List.finRange n).map τ).map (colSum A) := by
    rw [List.map_map]
    exact List.map_congr_left (fun j _ => colSum_act σ τ A j)
  rw [e]
  exact (τ.map_finRange_perm).map (colSum A)

/-- The sorted profile of `A` is the (index-order) profile of any sorted permutation of `A`. -/
theorem sortedProfileOf_eq_of_antitone {m n : Nat} (A : Mat m n)
    (σ : Equiv.Perm (Fin m)) (τ : Equiv.Perm (Fin n))
    (hr : Antitone (rowSum (act σ τ A))) (hc : Antitone (colSum (act σ τ A))) :
    sortedProfileOf A = (rowList (act σ τ A), colList (act σ τ A)) := by
  unfold sortedProfileOf
  congr 1
  · apply List.Perm.eq_of_sortedGE (sortDesc_sortedGE _) (List.sortedGE_ofFn_iff.mpr hr)
    exact (sortDesc_perm _).trans (rowList_act_perm σ τ A).symm
  · apply List.Perm.eq_of_sortedGE (sortDesc_sortedGE _) (List.sortedGE_ofFn_iff.mpr hc)
    exact (sortDesc_perm _).trans (colList_act_perm σ τ A).symm

/-- A case `(rows, cols)` as a `Profile` (missing entries read as `0`). -/
def mkProfile (P : Params) (q : List Nat × List Nat) : Profile P.m P.n :=
  { row := fun i => q.1.getD i.val 0, col := fun j => q.2.getD j.val 0 }

theorem getD_ofFn {α : Type} {k : Nat} (f : Fin k → α) (i : Fin k) (d : α) :
    (List.ofFn f).getD i.val d = f i := by
  rw [List.getD_eq_getElem?_getD, List.getElem?_ofFn]
  simp [i.isLt]

theorem mkProfile_lists (P : Params) (B : Mat P.m P.n) :
    mkProfile P (rowList B, colList B) = profileOf B := by
  unfold mkProfile profileOf rowList colList
  congr 1
  · funext i; exact getD_ofFn _ i 0
  · funext j; exact getD_ofFn _ j 0

/-! ## 4. The enumerator (Tan 2022, Algorithm 1) -/

/-- One level of Tan's Algorithm 1.  `left` parts remain to be chosen, `k` have been
chosen (prefix sum `psum`, `choose`-cost `cost`, last part `maxp`), `remaining` is the
sum still to be distributed.  A part `p` is tried in increasing order and kept when the
remaining parts can still exhaust the sum (`remaining ≤ p * (left+1)`), the budget is
not exceeded, and the prefix bound `ub (k+1)` holds (proper prefixes only: `k+1 < len`). -/
def genAux (cap r budget len : Nat) (ub : Nat → Nat) :
    (left k maxp remaining cost psum : Nat) → List (List Nat)
  | 0, _, _, remaining, _, _ => if remaining = 0 then [[]] else []
  | left + 1, k, maxp, remaining, cost, psum =>
    (List.range (min maxp remaining + 1)).flatMap fun p =>
      if remaining ≤ p * (left + 1) ∧ cost + p.choose r ≤ budget
          ∧ (k + 1 < len → psum + p ≤ ub (k + 1)) then
        (genAux cap r budget len ub left (k + 1) p (remaining - p) (cost + p.choose r) (psum + p)).map
          (p :: ·)
      else []

/-- All non-increasing lists of length `len` with entries `≤ cap`, sum `total`,
`Σ choose xᵢ r ≤ budget` and every proper prefix sum `x₁ + ⋯ + xₖ ≤ ub k` (`0 < k < len`). -/
def genParts (len cap total r budget : Nat) (ub : Nat → Nat) : List (List Nat) :=
  genAux cap r budget len ub len 0 cap total 0 0

theorem mem_genAux (cap r budget len : Nat) (ub : Nat → Nat) :
    ∀ (left k maxp remaining cost psum : Nat) (l : List Nat),
      l.length = left → (∀ x ∈ l, x ≤ maxp) → l.Pairwise (· ≥ ·) → l.sum = remaining →
      cost + (l.map (fun x => x.choose r)).sum ≤ budget →
      (∀ j, k < j → j < len → psum + (l.take (j - k)).sum ≤ ub j) →
      l ∈ genAux cap r budget len ub left k maxp remaining cost psum := by
  intro left
  induction left with
  | zero =>
    intro k maxp remaining cost psum l hlen _ _ hsum _ _
    rw [List.length_eq_zero_iff] at hlen
    subst hlen
    simp only [List.sum_nil] at hsum
    subst hsum
    simp [genAux]
  | succ left ih =>
    intro k maxp remaining cost psum l hlen hle hpw hsum hbud hpre
    obtain ⟨p, rest, rfl⟩ : ∃ p rest, l = p :: rest := by
      cases l with
      | nil => simp at hlen
      | cons p rest => exact ⟨p, rest, rfl⟩
    have hlen' : rest.length = left := by simp at hlen; omega
    have hp_le : p ≤ maxp := hle p (List.mem_cons_self ..)
    have hsum' : p + rest.sum = remaining := by simpa using hsum
    have hrest_le : ∀ x ∈ rest, x ≤ p := fun x hx => (List.pairwise_cons.mp hpw).1 x hx
    have hbud' : cost + p.choose r + (rest.map (fun x => x.choose r)).sum ≤ budget := by
      simp only [List.map_cons, List.sum_cons] at hbud; omega
    have hrest_sum : rest.sum ≤ left * p := by
      have := List.sum_le_length_nsmul rest p hrest_le
      rw [smul_eq_mul, hlen'] at this
      exact this
    simp only [genAux]
    rw [List.mem_flatMap]
    refine ⟨p, ?_, ?_⟩
    · rw [List.mem_range]
      exact Nat.lt_succ_iff.mpr (Nat.le_min.mpr ⟨hp_le, by omega⟩)
    · have hcond : remaining ≤ p * (left + 1) ∧ cost + p.choose r ≤ budget
          ∧ (k + 1 < len → psum + p ≤ ub (k + 1)) := by
        refine ⟨?_, by omega, ?_⟩
        · rw [Nat.mul_succ]; nlinarith [hrest_sum, hsum']
        · intro hj
          have h := hpre (k + 1) (by omega) hj
          simp only [Nat.add_sub_cancel_left, List.take_succ_cons, List.take_zero,
            List.sum_cons, List.sum_nil, Nat.add_zero] at h
          exact h
      split
      · rw [List.mem_map]
        refine ⟨rest, ih (k + 1) p (remaining - p) (cost + p.choose r) (psum + p) rest hlen'
          hrest_le (List.pairwise_cons.mp hpw).2 (by omega) hbud' ?_, rfl⟩
        intro j hj hjl
        have h := hpre j (by omega) hjl
        have e : j - k = (j - (k + 1)) + 1 := by omega
        rw [e, List.take_succ_cons, List.sum_cons] at h
        omega
      · exact absurd hcond ‹_›

/-- **Completeness of the enumerator.** -/
theorem mem_genParts (len cap total r budget : Nat) (ub : Nat → Nat) (l : List Nat)
    (hlen : l.length = len) (hcap : ∀ x ∈ l, x ≤ cap) (hpw : l.Pairwise (· ≥ ·))
    (hsum : l.sum = total) (hbud : (l.map (fun x => x.choose r)).sum ≤ budget)
    (hpre : ∀ j, 0 < j → j < len → (l.take j).sum ≤ ub j) :
    l ∈ genParts len cap total r budget ub :=
  mem_genAux cap r budget len ub len 0 cap total 0 0 l hlen hcap hpw hsum (by simpa using hbud)
    (fun j hj hjl => by simpa using hpre j hj hjl)

/-! ### Prefix bounds from facts -/

/-- The tightest bound among the facts selected by `q k`, or `default` when none applies. -/
def ubOf (facts : List Fact) (q : Nat → Fact → Bool) (default : Nat) (k : Nat) : Nat :=
  facts.foldr (fun f acc => if q k f then min f.z acc else acc) default

theorem le_ubOf (facts : List Fact) (q : Nat → Fact → Bool) (default k x : Nat)
    (hd : x ≤ default) (hf : ∀ f ∈ facts, q k f = true → x ≤ f.z) :
    x ≤ ubOf facts q default k := by
  induction facts with
  | nil => simpa [ubOf]
  | cons f fs ih =>
    have ih' : x ≤ ubOf fs q default k := ih (fun g hg => hf g (List.mem_cons_of_mem f hg))
    unfold ubOf at ih' ⊢
    simp only [List.foldr_cons]
    split
    · exact Nat.le_min.mpr ⟨hf f (List.mem_cons_self ..) ‹_›, ih'⟩
    · exact ih'

/-- Column prefix bounds: facts about `(P.m, k)` (Argument I on the `k` heaviest columns). -/
def colUb (P : Params) (facts : List Fact) : Nat → Nat :=
  ubOf facts (fun k f => decide (f.m = P.m ∧ f.n = k ∧ f.s = P.s ∧ f.t = P.t)) P.w

/-- Row prefix bounds: facts about `(k, P.n)`. -/
def rowUb (P : Params) (facts : List Fact) : Nat → Nat :=
  ubOf facts (fun k f => decide (f.m = k ∧ f.n = P.n ∧ f.s = P.s ∧ f.t = P.t)) P.w

/-- Admissible column-sum vectors (Tan Algorithm 1 with the Argument A column budget). -/
def genCols (P : Params) (facts : List Fact) : List (List Nat) :=
  genParts P.n P.m P.w P.s ((P.t - 1) * P.m.choose P.s) (colUb P facts)

/-- Admissible row-sum vectors. -/
def genRows (P : Params) (facts : List Fact) : List (List Nat) :=
  genParts P.m P.n P.w P.t ((P.s - 1) * P.n.choose P.t) (rowUb P facts)

theorem incr_castLE {k n : Nat} (hk : k ≤ n) : Incr (Fin.castLE hk) :=
  fun _ _ hab => (Fin.castLE_lt_castLE_iff hk).mpr hab

theorem sum_take_ofFn_castLE :
    ∀ (k n : Nat) (hk : k ≤ n) (g : Fin n → Nat),
      ((List.ofFn g).take k).sum = ∑ a : Fin k, g (Fin.castLE hk a)
  | 0, _, _, _ => by simp
  | k + 1, 0, hk, _ => by omega
  | k + 1, n + 1, hk, g => by
    rw [List.ofFn_succ, List.take_succ_cons, List.sum_cons, Fin.sum_univ_succ,
      sum_take_ofFn_castLE k n (by omega) (fun i => g i.succ)]
    congr 1

/-- The `k × n` minor of `A` on the rows enumerated by `e`. -/
def minorRows {m n k : Nat} (A : Mat m n) (e : Fin k → Fin m) : Mat k n :=
  fun a j => A (e a) j

theorem weight_minorRows {m n k : Nat} (A : Mat m n) (e : Fin k → Fin m) :
    weight (minorRows A e) = ∑ a, rowSum A (e a) := by
  rw [weight_eq_sum]
  rfl

theorem not_hasKst_minorRows {m n k s t w w' : Nat} (A : Mat m n) (e : Fin k → Fin m)
    (he : Incr e) (h : ¬ HasKst ⟨m, n, s, t, w⟩ A) :
    ¬ HasKst ⟨k, n, s, t, w'⟩ (minorRows A e) := by
  rintro ⟨R, C, hR, hC, hall⟩
  exact h ⟨fun a => e (R a), C, fun a b hab => he _ _ (hR a b hab), hC, hall⟩

/-- **Argument I (columns), list form.**  The first `k` columns of a `K_{s,t}`-free matrix
form a `K_{s,t}`-free `m × k` minor, so their sums total at most `z(m,k)`. -/
theorem sum_take_colList_le (P : Params) (B : Mat P.m P.n) (hB : ¬ HasKst P B)
    (k : Nat) (hk : k ≤ P.n) (f : Fact) (hf : FactHolds f)
    (h : f.m = P.m ∧ f.n = k ∧ f.s = P.s ∧ f.t = P.t) :
    ((colList B).take k).sum ≤ f.z := by
  obtain ⟨m, n, s, t, w⟩ := P
  obtain ⟨fm, fn, fs, ft, z, tag⟩ := f
  simp only at h hf hB hk B ⊢
  obtain ⟨rfl, rfl, rfl, rfl⟩ := h
  have hw := hf (minorCols B (Fin.castLE hk)) (not_hasKst_minorCols B _ (incr_castLE hk) hB)
  rw [weight_minorCols] at hw
  unfold colList
  rw [sum_take_ofFn_castLE fn n hk (colSum B)]
  exact hw

/-- **Argument I (rows), list form.** -/
theorem sum_take_rowList_le (P : Params) (B : Mat P.m P.n) (hB : ¬ HasKst P B)
    (k : Nat) (hk : k ≤ P.m) (f : Fact) (hf : FactHolds f)
    (h : f.m = k ∧ f.n = P.n ∧ f.s = P.s ∧ f.t = P.t) :
    ((rowList B).take k).sum ≤ f.z := by
  obtain ⟨m, n, s, t, w⟩ := P
  obtain ⟨fm, fn, fs, ft, z, tag⟩ := f
  simp only at h hf hB hk B ⊢
  obtain ⟨rfl, rfl, rfl, rfl⟩ := h
  have hw := hf (minorRows B (Fin.castLE hk)) (not_hasKst_minorRows B _ (incr_castLE hk) hB)
  rw [weight_minorRows] at hw
  unfold rowList
  rw [sum_take_ofFn_castLE fm m hk (rowSum B)]
  exact hw

theorem colList_mem_genCols (P : Params) (facts : List Fact) (hF : ∀ f ∈ facts, FactHolds f)
    (B : Mat P.m P.n) (hB : ¬ HasKst P B) (hw : weight B = P.w) (hc : Antitone (colSum B)) :
    colList B ∈ genCols P facts := by
  apply mem_genParts
  · exact List.length_ofFn
  · intro x hx
    rw [colList, List.mem_ofFn] at hx
    obtain ⟨j, rfl⟩ := hx
    exact colSum_le B j
  · exact (List.sortedGE_ofFn_iff.mpr hc).pairwise
  · rw [colList, List.sum_ofFn, weight_eq_sum_colSum, sumFin_eq_sum] at *; exact hw
  · rw [colList, List.map_ofFn, List.sum_ofFn]
    exact colBudget P B hB
  · intro j hj hjl
    apply le_ubOf
    · calc ((colList B).take j).sum ≤ (colList B).sum :=
            List.Sublist.sum_le_sum (List.take_sublist _ _) (fun _ _ => Nat.zero_le _)
        _ = P.w := by rw [colList, List.sum_ofFn, ← sumFin_eq_sum, ← weight_eq_sum_colSum, hw]
    · intro f hf hq
      rw [decide_eq_true_eq] at hq
      exact sum_take_colList_le P B hB j (le_of_lt hjl) f (hF f hf) hq

theorem rowList_mem_genRows (P : Params) (facts : List Fact) (hF : ∀ f ∈ facts, FactHolds f)
    (B : Mat P.m P.n) (hB : ¬ HasKst P B) (hw : weight B = P.w) (hr : Antitone (rowSum B)) :
    rowList B ∈ genRows P facts := by
  apply mem_genParts
  · exact List.length_ofFn
  · intro x hx
    rw [rowList, List.mem_ofFn] at hx
    obtain ⟨i, rfl⟩ := hx
    exact rowSum_le B i
  · exact (List.sortedGE_ofFn_iff.mpr hr).pairwise
  · rw [rowList, List.sum_ofFn, ← weight_eq_sum]; exact hw
  · rw [rowList, List.map_ofFn, List.sum_ofFn]
    exact rowBudget P B hB
  · intro j hj hjl
    apply le_ubOf
    · calc ((rowList B).take j).sum ≤ (rowList B).sum :=
            List.Sublist.sum_le_sum (List.take_sublist _ _) (fun _ _ => Nat.zero_le _)
        _ = P.w := by rw [rowList, List.sum_ofFn, ← weight_eq_sum, hw]
    · intro f hf hq
      rw [decide_eq_true_eq] at hq
      exact sum_take_rowList_le P B hB j (le_of_lt hjl) f (hF f hf) hq

/-! ## 5. Survivors and the closure theorem -/

/-- Cartesian product, row-major (the order of Python's `itertools.product`). -/
def pairs {α β : Type} (xs : List α) (ys : List β) : List (α × β) :=
  xs.flatMap fun x => ys.map fun y => (x, y)

theorem mem_pairs {α β : Type} (xs : List α) (ys : List β) (x : α) (y : β) :
    (x, y) ∈ pairs xs ys ↔ x ∈ xs ∧ y ∈ ys := by
  unfold pairs
  simp only [List.mem_flatMap, List.mem_map, Prod.mk.injEq]
  constructor
  · rintro ⟨x', hx', y', hy', rfl, rfl⟩; exact ⟨hx', hy'⟩
  · rintro ⟨hx, hy⟩; exact ⟨x, hx, y, hy, rfl, rfl⟩

/-- The cases of the enumerator not killed by `kill`. -/
def survivorsK (P : Params) (facts : List Fact) (kill : Profile P.m P.n → Bool) :
    List (List Nat × List Nat) :=
  (pairs (genRows P facts) (genCols P facts)).filter (fun q => !kill (mkProfile P q))

/-- The cases of the enumerator not killed by the prune `p`: what the SAT solver must refute. -/
def survivors (P : Params) (facts : List Fact) (p : Prune P) : List (List Nat × List Nat) :=
  survivorsK P facts p.kill

/-- **Cover.**  A `K_{s,t}`-free matrix of weight exactly `P.w` is either killed (its sorted
profile, which is the profile of a permuted copy) or listed among the survivors. -/
theorem cover_of_survivors (P : Params) (facts : List Fact) (kill : Profile P.m P.n → Bool)
    (hF : ∀ f ∈ facts, FactHolds f) (A : Mat P.m P.n) (hA : ¬ HasKst P A) (hw : weight A = P.w) :
    kill (mkProfile P (sortedProfileOf A)) = true ∨ sortedProfileOf A ∈ survivorsK P facts kill := by
  obtain ⟨σ, τ, hr, hc⟩ := exists_sorted A
  rw [sortedProfileOf_eq_of_antitone A σ τ hr hc]
  have hB : ¬ HasKst P (act σ τ A) := (hasKst_act_iff P σ τ A).not.mpr hA
  have hwB : weight (act σ τ A) = P.w := by rw [weight_act]; exact hw
  cases hk : kill (mkProfile P (rowList (act σ τ A), colList (act σ τ A))) with
  | true => exact Or.inl rfl
  | false =>
    right
    unfold survivorsK
    rw [List.mem_filter, mem_pairs]
    exact ⟨⟨rowList_mem_genRows P facts hF _ hB hwB hr, colList_mem_genCols P facts hF _ hB hwB hc⟩,
      by rw [hk]; rfl⟩

/-- The `Valid`-form of the cover, as stated in design §4.6. -/
theorem cover_of_survivors_valid (P : Params) (facts : List Fact) (p : Prune P)
    (hF : ∀ f ∈ facts, FactHolds f) (A : Mat P.m P.n) (hv : Valid P A) (hw : weight A = P.w) :
    p.kill (mkProfile P (sortedProfileOf A)) = true ∨ sortedProfileOf A ∈ survivors P facts p :=
  cover_of_survivors P facts p.kill hF A hv.1 hw

/-- **The closure theorem.**  With `P.w = u + 1`: if the facts hold, the prune is verified,
the Lean-computed survivor list is the literal `surv`, and every case in `surv` is refuted,
then every `K_{s,t}`-free `m × n` matrix has at most `u` ones. -/
theorem upper_bound_succ_of_sorted_cover (P : Params) (u : Nat) (hu : P.w = u + 1)
    (facts : List Fact) (hF : ∀ f ∈ facts, FactHolds f) (p : Prune P)
    (surv : List (List Nat × List Nat)) (hs : survivors P facts p = surv)
    (refuted : ∀ q ∈ surv, ∀ A : Mat P.m P.n, sortedProfileOf A = q → ¬ Valid P A) :
    ∀ A : Mat P.m P.n, ¬ HasKst P A → weight A ≤ u := by
  subst hs
  have hne : ∀ A : Mat P.m P.n, ¬ HasKst P A → weight A ≠ P.w := by
    intro A hA hw
    obtain ⟨σ, τ, hr, hc⟩ := exists_sorted A
    have hsp := sortedProfileOf_eq_of_antitone A σ τ hr hc
    rcases cover_of_survivors P facts p.kill hF A hA hw with hk | hmem
    · rw [hsp, mkProfile_lists] at hk
      exact p.sound _ hk ⟨(hasKst_act_iff P σ τ A).not.mpr hA, by rw [weight_act, hw]⟩
    · exact refuted _ hmem A rfl ⟨hA, by rw [hw]⟩
  intro A hA
  have := lt_of_no_exact P hne A hA
  omega

/-- The same, for a prune given with its facts already discharged inside a `CondPrune`
(the shape the generated closure files use, so that `survivors_eq` is a closed statement). -/
theorem upper_bound_succ_of_condPrune (P : Params) (u : Nat) (hu : P.w = u + 1)
    (facts : List Fact) (hF : ∀ f ∈ facts, FactHolds f) (q : CondPrune P facts)
    (surv : List (List Nat × List Nat)) (hs : survivorsK P facts q.kill = surv)
    (refuted : ∀ q ∈ surv, ∀ A : Mat P.m P.n, sortedProfileOf A = q → ¬ Valid P A) :
    ∀ A : Mat P.m P.n, ¬ HasKst P A → weight A ≤ u :=
  upper_bound_succ_of_sorted_cover P u hu facts hF (q.discharge hF) surv hs refuted

/-! ## 6. Pure-mode facts, discharged in place -/

/-- The waterfilled column budget (Argument A) proves any fact it dominates. -/
theorem factHolds_of_waterfill_le (m n s t z : Nat) (tag : String) (hs : 1 ≤ s)
    (h : waterfillBound m n s (colBudgetOf ⟨m, n, s, t, 0⟩) ≤ z) :
    FactHolds ⟨m, n, s, t, z, tag⟩ :=
  fun B hB => Nat.le_trans (weight_le_waterfill ⟨m, n, s, t, 0⟩ hs B hB) h

/-- The row-side waterfill (Argument A on the transpose) proves any fact it dominates. -/
theorem factHolds_of_waterfillT_le (m n s t z : Nat) (tag : String) (ht : 1 ≤ t)
    (h : waterfillBound n m t (colBudgetOf ⟨n, m, t, s, 0⟩) ≤ z) :
    FactHolds ⟨m, n, s, t, z, tag⟩ :=
  (factHolds_transpose ⟨m, n, s, t, z, tag⟩).mp (factHolds_of_waterfill_le n m t s z tag ht h)

end ZarPrune
-- ===== end of inlined Closure.lean =====


namespace ZarPrune.ClosureAudit
open ZarPrune

#print axioms ZarPrune.clearCell
#print axioms ZarPrune.clearCell_le
#print axioms ZarPrune.hasKst_mono
#print axioms ZarPrune.weight_eq_double_sum
#print axioms ZarPrune.weight_clearCell
#print axioms ZarPrune.exists_true_of_weight_ne_zero
#print axioms ZarPrune.lt_of_no_exact
#print axioms ZarPrune.act
#print axioms ZarPrune.rowSum_act
#print axioms ZarPrune.colSum_act
#print axioms ZarPrune.weight_act
#print axioms ZarPrune.Incr.injective
#print axioms ZarPrune.hasKst_of_act
#print axioms ZarPrune.act_symm_act
#print axioms ZarPrune.hasKst_act_iff
#print axioms ZarPrune.valid_act_iff
#print axioms ZarPrune.sortDesc
#print axioms ZarPrune.rowList
#print axioms ZarPrune.colList
#print axioms ZarPrune.sortedProfileOf
#print axioms ZarPrune.sortDesc_perm
#print axioms ZarPrune.sortDesc_sortedGE
#print axioms ZarPrune.exists_sorted
#print axioms ZarPrune.rowList_act_perm
#print axioms ZarPrune.colList_act_perm
#print axioms ZarPrune.sortedProfileOf_eq_of_antitone
#print axioms ZarPrune.mkProfile
#print axioms ZarPrune.getD_ofFn
#print axioms ZarPrune.mkProfile_lists
#print axioms ZarPrune.genAux
#print axioms ZarPrune.genParts
#print axioms ZarPrune.mem_genAux
#print axioms ZarPrune.mem_genParts
#print axioms ZarPrune.ubOf
#print axioms ZarPrune.le_ubOf
#print axioms ZarPrune.colUb
#print axioms ZarPrune.rowUb
#print axioms ZarPrune.genCols
#print axioms ZarPrune.genRows
#print axioms ZarPrune.incr_castLE
#print axioms ZarPrune.sum_take_ofFn_castLE
#print axioms ZarPrune.minorRows
#print axioms ZarPrune.weight_minorRows
#print axioms ZarPrune.not_hasKst_minorRows
#print axioms ZarPrune.sum_take_colList_le
#print axioms ZarPrune.sum_take_rowList_le
#print axioms ZarPrune.colList_mem_genCols
#print axioms ZarPrune.rowList_mem_genRows
#print axioms ZarPrune.pairs
#print axioms ZarPrune.mem_pairs
#print axioms ZarPrune.survivorsK
#print axioms ZarPrune.survivors
#print axioms ZarPrune.cover_of_survivors
#print axioms ZarPrune.cover_of_survivors_valid
#print axioms ZarPrune.upper_bound_succ_of_sorted_cover
#print axioms ZarPrune.upper_bound_succ_of_condPrune
#print axioms ZarPrune.factHolds_of_waterfill_le
#print axioms ZarPrune.factHolds_of_waterfillT_le

abbrev P0 : Params := ⟨9, 9, 3, 3, 50⟩
abbrev facts0 : List Fact := [⟨3, 9, 3, 3, 20, "lean-here"⟩, ⟨4, 9, 3, 3, 26, "lean-here"⟩, ⟨5, 9, 3, 3, 30, "lean-here"⟩, ⟨6, 9, 3, 3, 36, "lean-here"⟩, ⟨7, 9, 3, 3, 41, "lean-here"⟩, ⟨8, 9, 3, 3, 47, "lean-here"⟩, ⟨9, 3, 3, 3, 20, "lean-here"⟩, ⟨9, 4, 3, 3, 26, "lean-here"⟩, ⟨9, 5, 3, 3, 30, "lean-here"⟩, ⟨9, 6, 3, 3, 36, "lean-here"⟩, ⟨9, 7, 3, 3, 41, "lean-here"⟩, ⟨9, 8, 3, 3, 47, "lean-here"⟩]
#eval IO.println ("ROWS0 " ++ toString (genRows P0 facts0))
#eval IO.println ("COLS0 " ++ toString (genCols P0 facts0))
abbrev P1 : Params := ⟨9, 10, 3, 3, 55⟩
abbrev facts1 : List Fact := [⟨3, 10, 3, 3, 22, "lean-here"⟩, ⟨4, 10, 3, 3, 28, "lean-here"⟩, ⟨5, 10, 3, 3, 33, "lean-here"⟩, ⟨6, 10, 3, 3, 40, "lean-here"⟩, ⟨7, 10, 3, 3, 45, "lean-here"⟩, ⟨8, 10, 3, 3, 51, "lean-here"⟩, ⟨9, 3, 3, 3, 20, "lean-here"⟩, ⟨9, 4, 3, 3, 26, "lean-here"⟩, ⟨9, 5, 3, 3, 30, "lean-here"⟩, ⟨9, 6, 3, 3, 36, "lean-here"⟩, ⟨9, 7, 3, 3, 41, "lean-here"⟩, ⟨9, 8, 3, 3, 47, "lean-here"⟩, ⟨9, 9, 3, 3, 52, "lean-here"⟩]
#eval IO.println ("ROWS1 " ++ toString (genRows P1 facts1))
#eval IO.println ("COLS1 " ++ toString (genCols P1 facts1))
abbrev P2 : Params := ⟨10, 20, 3, 3, 103⟩
abbrev facts2 : List Fact := [⟨3, 20, 3, 3, 42, "lean-here"⟩, ⟨4, 20, 3, 3, 48, "lean-here"⟩, ⟨5, 20, 3, 3, 60, "lean-here"⟩, ⟨6, 20, 3, 3, 66, "lean-here"⟩, ⟨7, 20, 3, 3, 76, "lean-here"⟩, ⟨8, 20, 3, 3, 85, "lean-here"⟩, ⟨9, 20, 3, 3, 94, "lean-here"⟩, ⟨10, 3, 3, 3, 22, "lean-here"⟩, ⟨10, 4, 3, 3, 28, "lean-here"⟩, ⟨10, 5, 3, 3, 33, "lean-here"⟩, ⟨10, 6, 3, 3, 40, "lean-here"⟩, ⟨10, 7, 3, 3, 45, "lean-here"⟩, ⟨10, 8, 3, 3, 51, "lean-here"⟩, ⟨10, 9, 3, 3, 56, "lean-here"⟩, ⟨10, 10, 3, 3, 62, "lean-here"⟩, ⟨10, 11, 3, 3, 67, "lean-here"⟩, ⟨10, 12, 3, 3, 72, "lean-here"⟩, ⟨10, 13, 3, 3, 76, "lean-here"⟩, ⟨10, 14, 3, 3, 80, "lean-here"⟩, ⟨10, 15, 3, 3, 84, "lean-here"⟩, ⟨10, 16, 3, 3, 88, "lean-here"⟩, ⟨10, 17, 3, 3, 92, "lean-here"⟩, ⟨10, 18, 3, 3, 96, "lean-here"⟩, ⟨10, 19, 3, 3, 100, "lean-here"⟩, ⟨7, 20, 3, 3, 75, "tan2022"⟩, ⟨8, 20, 3, 3, 84, "tan2022"⟩, ⟨9, 20, 3, 3, 93, "tan2022"⟩, ⟨10, 6, 3, 3, 39, "tan2022"⟩, ⟨10, 7, 3, 3, 44, "tan2022"⟩, ⟨10, 8, 3, 3, 50, "tan2022"⟩, ⟨10, 9, 3, 3, 54, "tan2022"⟩, ⟨10, 10, 3, 3, 60, "tan2022"⟩, ⟨10, 11, 3, 3, 64, "tan2022"⟩, ⟨10, 12, 3, 3, 68, "tan2022"⟩, ⟨10, 13, 3, 3, 73, "tan2022"⟩, ⟨10, 14, 3, 3, 77, "tan2022"⟩, ⟨10, 15, 3, 3, 81, "tan2022"⟩, ⟨10, 16, 3, 3, 85, "tan2022"⟩, ⟨10, 17, 3, 3, 90, "tan2022"⟩, ⟨10, 18, 3, 3, 94, "tan2022"⟩, ⟨10, 19, 3, 3, 98, "tan2022"⟩]
#eval IO.println ("ROWS2 " ++ toString (genRows P2 facts2))
#eval IO.println ("COLS2 " ++ toString (genCols P2 facts2))
abbrev P3 : Params := ⟨7, 7, 3, 3, 34⟩
abbrev facts3 : List Fact := [⟨3, 7, 3, 3, 16, "lean-here"⟩, ⟨4, 7, 3, 3, 21, "lean-here"⟩, ⟨5, 7, 3, 3, 25, "lean-here"⟩, ⟨6, 7, 3, 3, 30, "lean-here"⟩, ⟨7, 3, 3, 3, 16, "lean-here"⟩, ⟨7, 4, 3, 3, 21, "lean-here"⟩, ⟨7, 5, 3, 3, 25, "lean-here"⟩, ⟨7, 6, 3, 3, 30, "lean-here"⟩, ⟨6, 7, 3, 3, 29, "tan2022"⟩, ⟨7, 6, 3, 3, 29, "tan2022"⟩]
#eval IO.println ("ROWS3 " ++ toString (genRows P3 facts3))
#eval IO.println ("COLS3 " ++ toString (genCols P3 facts3))
abbrev P4 : Params := ⟨8, 8, 2, 2, 25⟩
abbrev facts4 : List Fact := [⟨2, 8, 2, 2, 9, "lean-here"⟩, ⟨3, 8, 2, 2, 11, "lean-here"⟩, ⟨4, 8, 2, 2, 14, "lean-here"⟩, ⟨5, 8, 2, 2, 17, "lean-here"⟩, ⟨6, 8, 2, 2, 19, "lean-here"⟩, ⟨7, 8, 2, 2, 22, "lean-here"⟩, ⟨8, 2, 2, 2, 9, "lean-here"⟩, ⟨8, 3, 2, 2, 11, "lean-here"⟩, ⟨8, 4, 2, 2, 14, "lean-here"⟩, ⟨8, 5, 2, 2, 17, "lean-here"⟩, ⟨8, 6, 2, 2, 19, "lean-here"⟩, ⟨8, 7, 2, 2, 22, "lean-here"⟩]
#eval IO.println ("ROWS4 " ++ toString (genRows P4 facts4))
#eval IO.println ("COLS4 " ++ toString (genCols P4 facts4))
abbrev P5 : Params := ⟨9, 9, 4, 4, 62⟩
abbrev facts5 : List Fact := [⟨4, 9, 4, 4, 30, "lean-here"⟩, ⟨5, 9, 4, 4, 37, "lean-here"⟩, ⟨6, 9, 4, 4, 45, "lean-here"⟩, ⟨7, 9, 4, 4, 51, "lean-here"⟩, ⟨8, 9, 4, 4, 57, "lean-here"⟩, ⟨9, 4, 4, 4, 30, "lean-here"⟩, ⟨9, 5, 4, 4, 37, "lean-here"⟩, ⟨9, 6, 4, 4, 45, "lean-here"⟩, ⟨9, 7, 4, 4, 51, "lean-here"⟩, ⟨9, 8, 4, 4, 57, "lean-here"⟩]
#eval IO.println ("ROWS5 " ++ toString (genRows P5 facts5))
#eval IO.println ("COLS5 " ++ toString (genCols P5 facts5))
abbrev P6 : Params := ⟨11, 21, 3, 3, 117⟩
abbrev facts6 : List Fact := [⟨3, 21, 3, 3, 44, "lean-here"⟩, ⟨4, 21, 3, 3, 50, "lean-here"⟩, ⟨5, 21, 3, 3, 62, "lean-here"⟩, ⟨6, 21, 3, 3, 69, "lean-here"⟩, ⟨7, 21, 3, 3, 79, "lean-here"⟩, ⟨8, 21, 3, 3, 88, "lean-here"⟩, ⟨9, 21, 3, 3, 98, "lean-here"⟩, ⟨10, 21, 3, 3, 108, "lean-here"⟩, ⟨11, 3, 3, 3, 24, "lean-here"⟩, ⟨11, 4, 3, 3, 30, "lean-here"⟩, ⟨11, 5, 3, 3, 36, "lean-here"⟩, ⟨11, 6, 3, 3, 42, "lean-here"⟩, ⟨11, 7, 3, 3, 48, "lean-here"⟩, ⟨11, 8, 3, 3, 55, "lean-here"⟩, ⟨11, 9, 3, 3, 60, "lean-here"⟩, ⟨11, 10, 3, 3, 67, "lean-here"⟩, ⟨11, 11, 3, 3, 73, "lean-here"⟩, ⟨11, 12, 3, 3, 78, "lean-here"⟩, ⟨11, 13, 3, 3, 82, "lean-here"⟩, ⟨11, 14, 3, 3, 87, "lean-here"⟩, ⟨11, 15, 3, 3, 92, "lean-here"⟩, ⟨11, 16, 3, 3, 96, "lean-here"⟩, ⟨11, 17, 3, 3, 101, "lean-here"⟩, ⟨11, 18, 3, 3, 105, "lean-here"⟩, ⟨11, 19, 3, 3, 109, "lean-here"⟩, ⟨11, 20, 3, 3, 113, "lean-here"⟩, ⟨7, 21, 3, 3, 78, "tan2022"⟩, ⟨8, 21, 3, 3, 87, "tan2022"⟩, ⟨9, 21, 3, 3, 96, "tan2022"⟩, ⟨11, 7, 3, 3, 47, "tan2022"⟩, ⟨11, 8, 3, 3, 53, "tan2022"⟩, ⟨11, 9, 3, 3, 59, "tan2022"⟩, ⟨11, 10, 3, 3, 64, "tan2022"⟩, ⟨11, 11, 3, 3, 69, "tan2022"⟩, ⟨11, 12, 3, 3, 74, "tan2022"⟩, ⟨11, 13, 3, 3, 80, "tan2022"⟩, ⟨11, 14, 3, 3, 84, "tan2022"⟩, ⟨11, 15, 3, 3, 88, "tan2022"⟩, ⟨11, 16, 3, 3, 92, "tan2022"⟩, ⟨11, 17, 3, 3, 96, "tan2022"⟩, ⟨11, 18, 3, 3, 101, "tan2022"⟩]
#eval IO.println ("ROWS6 " ++ toString (genRows P6 facts6))
#eval IO.println ("COLS6 " ++ toString (genCols P6 facts6))
abbrev P7 : Params := ⟨10, 21, 3, 3, 107⟩
abbrev facts7 : List Fact := [⟨3, 21, 3, 3, 44, "lean-here"⟩, ⟨4, 21, 3, 3, 50, "lean-here"⟩, ⟨5, 21, 3, 3, 62, "lean-here"⟩, ⟨6, 21, 3, 3, 69, "lean-here"⟩, ⟨7, 21, 3, 3, 79, "lean-here"⟩, ⟨8, 21, 3, 3, 88, "lean-here"⟩, ⟨9, 21, 3, 3, 98, "lean-here"⟩, ⟨10, 3, 3, 3, 22, "lean-here"⟩, ⟨10, 4, 3, 3, 28, "lean-here"⟩, ⟨10, 5, 3, 3, 33, "lean-here"⟩, ⟨10, 6, 3, 3, 40, "lean-here"⟩, ⟨10, 7, 3, 3, 45, "lean-here"⟩, ⟨10, 8, 3, 3, 51, "lean-here"⟩, ⟨10, 9, 3, 3, 56, "lean-here"⟩, ⟨10, 10, 3, 3, 62, "lean-here"⟩, ⟨10, 11, 3, 3, 67, "lean-here"⟩, ⟨10, 12, 3, 3, 72, "lean-here"⟩, ⟨10, 13, 3, 3, 76, "lean-here"⟩, ⟨10, 14, 3, 3, 80, "lean-here"⟩, ⟨10, 15, 3, 3, 84, "lean-here"⟩, ⟨10, 16, 3, 3, 88, "lean-here"⟩, ⟨10, 17, 3, 3, 92, "lean-here"⟩, ⟨10, 18, 3, 3, 96, "lean-here"⟩, ⟨10, 19, 3, 3, 100, "lean-here"⟩, ⟨10, 20, 3, 3, 104, "lean-here"⟩, ⟨7, 21, 3, 3, 78, "tan2022"⟩, ⟨8, 21, 3, 3, 87, "tan2022"⟩, ⟨9, 21, 3, 3, 96, "tan2022"⟩, ⟨10, 6, 3, 3, 39, "tan2022"⟩, ⟨10, 7, 3, 3, 44, "tan2022"⟩, ⟨10, 8, 3, 3, 50, "tan2022"⟩, ⟨10, 9, 3, 3, 54, "tan2022"⟩, ⟨10, 10, 3, 3, 60, "tan2022"⟩, ⟨10, 11, 3, 3, 64, "tan2022"⟩, ⟨10, 12, 3, 3, 68, "tan2022"⟩, ⟨10, 13, 3, 3, 73, "tan2022"⟩, ⟨10, 14, 3, 3, 77, "tan2022"⟩, ⟨10, 15, 3, 3, 81, "tan2022"⟩, ⟨10, 16, 3, 3, 85, "tan2022"⟩, ⟨10, 17, 3, 3, 90, "tan2022"⟩, ⟨10, 18, 3, 3, 94, "tan2022"⟩, ⟨10, 19, 3, 3, 98, "tan2022"⟩, ⟨10, 20, 3, 3, 102, "lean-here"⟩]
#eval IO.println ("ROWS7 " ++ toString (genRows P7 facts7))
#eval IO.println ("COLS7 " ++ toString (genCols P7 facts7))
abbrev P8 : Params := ⟨11, 19, 3, 3, 107⟩
abbrev facts8 : List Fact := [⟨3, 19, 3, 3, 40, "lean-here"⟩, ⟨4, 19, 3, 3, 46, "lean-here"⟩, ⟨5, 19, 3, 3, 57, "lean-here"⟩, ⟨6, 19, 3, 3, 64, "lean-here"⟩, ⟨7, 19, 3, 3, 74, "lean-here"⟩, ⟨8, 19, 3, 3, 82, "lean-here"⟩, ⟨9, 19, 3, 3, 91, "lean-here"⟩, ⟨10, 19, 3, 3, 100, "lean-here"⟩, ⟨11, 3, 3, 3, 24, "lean-here"⟩, ⟨11, 4, 3, 3, 30, "lean-here"⟩, ⟨11, 5, 3, 3, 36, "lean-here"⟩, ⟨11, 6, 3, 3, 42, "lean-here"⟩, ⟨11, 7, 3, 3, 48, "lean-here"⟩, ⟨11, 8, 3, 3, 55, "lean-here"⟩, ⟨11, 9, 3, 3, 60, "lean-here"⟩, ⟨11, 10, 3, 3, 67, "lean-here"⟩, ⟨11, 11, 3, 3, 73, "lean-here"⟩, ⟨11, 12, 3, 3, 78, "lean-here"⟩, ⟨11, 13, 3, 3, 82, "lean-here"⟩, ⟨11, 14, 3, 3, 87, "lean-here"⟩, ⟨11, 15, 3, 3, 92, "lean-here"⟩, ⟨11, 16, 3, 3, 96, "lean-here"⟩, ⟨11, 17, 3, 3, 101, "lean-here"⟩, ⟨11, 18, 3, 3, 105, "lean-here"⟩, ⟨7, 19, 3, 3, 72, "tan2022"⟩, ⟨8, 19, 3, 3, 81, "tan2022"⟩, ⟨9, 19, 3, 3, 89, "tan2022"⟩, ⟨10, 19, 3, 3, 98, "tan2022"⟩, ⟨11, 7, 3, 3, 47, "tan2022"⟩, ⟨11, 8, 3, 3, 53, "tan2022"⟩, ⟨11, 9, 3, 3, 59, "tan2022"⟩, ⟨11, 10, 3, 3, 64, "tan2022"⟩, ⟨11, 11, 3, 3, 69, "tan2022"⟩, ⟨11, 12, 3, 3, 74, "tan2022"⟩, ⟨11, 13, 3, 3, 80, "tan2022"⟩, ⟨11, 14, 3, 3, 84, "tan2022"⟩, ⟨11, 15, 3, 3, 88, "tan2022"⟩, ⟨11, 16, 3, 3, 92, "tan2022"⟩, ⟨11, 17, 3, 3, 96, "tan2022"⟩, ⟨11, 18, 3, 3, 101, "tan2022"⟩]
#eval IO.println ("ROWS8 " ++ toString (genRows P8 facts8))
#eval IO.println ("COLS8 " ++ toString (genCols P8 facts8))
abbrev P9 : Params := ⟨11, 20, 3, 3, 112⟩
abbrev facts9 : List Fact := [⟨3, 20, 3, 3, 42, "lean-here"⟩, ⟨4, 20, 3, 3, 48, "lean-here"⟩, ⟨5, 20, 3, 3, 60, "lean-here"⟩, ⟨6, 20, 3, 3, 66, "lean-here"⟩, ⟨7, 20, 3, 3, 76, "lean-here"⟩, ⟨8, 20, 3, 3, 85, "lean-here"⟩, ⟨9, 20, 3, 3, 94, "lean-here"⟩, ⟨10, 20, 3, 3, 104, "lean-here"⟩, ⟨11, 3, 3, 3, 24, "lean-here"⟩, ⟨11, 4, 3, 3, 30, "lean-here"⟩, ⟨11, 5, 3, 3, 36, "lean-here"⟩, ⟨11, 6, 3, 3, 42, "lean-here"⟩, ⟨11, 7, 3, 3, 48, "lean-here"⟩, ⟨11, 8, 3, 3, 55, "lean-here"⟩, ⟨11, 9, 3, 3, 60, "lean-here"⟩, ⟨11, 10, 3, 3, 67, "lean-here"⟩, ⟨11, 11, 3, 3, 73, "lean-here"⟩, ⟨11, 12, 3, 3, 78, "lean-here"⟩, ⟨11, 13, 3, 3, 82, "lean-here"⟩, ⟨11, 14, 3, 3, 87, "lean-here"⟩, ⟨11, 15, 3, 3, 92, "lean-here"⟩, ⟨11, 16, 3, 3, 96, "lean-here"⟩, ⟨11, 17, 3, 3, 101, "lean-here"⟩, ⟨11, 18, 3, 3, 105, "lean-here"⟩, ⟨11, 19, 3, 3, 109, "lean-here"⟩, ⟨7, 20, 3, 3, 75, "tan2022"⟩, ⟨8, 20, 3, 3, 84, "tan2022"⟩, ⟨9, 20, 3, 3, 93, "tan2022"⟩, ⟨10, 20, 3, 3, 102, "lean-here"⟩, ⟨11, 7, 3, 3, 47, "tan2022"⟩, ⟨11, 8, 3, 3, 53, "tan2022"⟩, ⟨11, 9, 3, 3, 59, "tan2022"⟩, ⟨11, 10, 3, 3, 64, "tan2022"⟩, ⟨11, 11, 3, 3, 69, "tan2022"⟩, ⟨11, 12, 3, 3, 74, "tan2022"⟩, ⟨11, 13, 3, 3, 80, "tan2022"⟩, ⟨11, 14, 3, 3, 84, "tan2022"⟩, ⟨11, 15, 3, 3, 88, "tan2022"⟩, ⟨11, 16, 3, 3, 92, "tan2022"⟩, ⟨11, 17, 3, 3, 96, "tan2022"⟩, ⟨11, 18, 3, 3, 101, "tan2022"⟩]
#eval IO.println ("ROWS9 " ++ toString (genRows P9 facts9))
#eval IO.println ("COLS9 " ++ toString (genCols P9 facts9))
def A0 : Mat 3 4 := fun i j => decide ((i.val + j.val) % 3 = 0)
#eval IO.println ("PROF " ++ toString (rowList A0) ++ " " ++ toString (colList A0) ++ " " ++ toString (sortedProfileOf A0))
#eval IO.println ("SORT " ++ toString (sortDesc [3,1,4,1,5,9,2,6]))
#eval IO.println ("PAIRS " ++ toString (pairs [1,2] ["a","b"]))
#eval IO.println ("MK " ++ toString ((mkProfile ⟨3,4,3,3,0⟩ ([5,4,3],[2,2,2,1])).row 1) ++ " " ++ toString ((mkProfile ⟨3,4,3,3,0⟩ ([5,4,3],[2,2,2,1])).col 3))
#eval IO.println ("GEN " ++ toString (genParts 3 4 6 2 100 (fun _ => 100)))
end ZarPrune.ClosureAudit
