import ZarPrune.Counting
-- AUDIT SCRATCH (generated by the E-schemas builder): inlines lean/ZarPrune/Schemas.lean and
-- runs #print axioms on every new declaration plus #eval semantic / timing checks.

/-!
# Verified schemas: the Farkas prune over hidden pair codegrees (design §2.3, §8.4)

The evolutionary loop may supply *parameters* for a schema whose soundness is proved
here once.  This module proves the Farkas schema `Prune.ofFarkas` (catalogue P3 / P11)
with **hidden variables**: the pair codegrees `λ_{i,i'} = |N(i) ∩ N(i')|` of a matrix,
which the profile does not determine but constrains linearly:

* **F1** `∑_i ∑_{i' ≠ i} λ_{i,i'} = ∑_j c_j (c_j − 1)` (`sum_sum_codeg`; the unordered
  form `2 · ∑_{i<i'} λ = ... = 2 ∑_j C(c_j, 2)` is `sum_sum_codeg_choose`).
* **F2** per row `i`: `∑_{i' ≠ i} λ_{i,i'} = ∑_{j ∈ N(i)} (c_j − 1)` (`sum_codeg_row`), hence
  between the sum of the `r_i` lightest and the `r_i` heaviest values of `(c_j − 1)`
  computed from the profile (`lowSum_le`, `le_topSumF`: the layer-cake machinery of
  `Counting.lean` generalised to any monotone `f : ℕ → ℕ`, plus its heaviest-sum dual).
* **F3** for `K_{s,t}`-free `A` with `2 ≤ s`: `∑_{j ∈ N(i) ∩ N(i')} C(c_j − 2, s − 2)
  ≤ (t − 1) · C(m − 2, s − 2)` (`pairLocalBudget`; for `s = t = 3` this is
  `∑ (c_j − 2) ≤ 2(m − 2)`: the other `m − 2` rows each meet the common columns in at
  most two places), hence `λ_{i,i'} ≤ Lcap`, the largest `k ≤ n` whose `k` lightest
  values of `C(c_j − 2, s − 2)` fit the budget; also `λ ≤ r_i, r_{i'}` (`codeg_le_cap`).
* **F4** `λ_{i,i'} ≥ r_i + r_{i'} − n` (inclusion–exclusion, `floor_le_codeg`).

`Prune.ofFarkas P ys` takes a list of non-negative integer multiplier vectors (one
per constraint, layout in `decode`) and kills a profile when some vector `y` satisfies
the Farkas conditions `∑_k y_k a_k ≥ 0` coefficientwise on every `λ` and `∑_k y_k b_k < 0`
(`certKills`, Int arithmetic, no LP solving).  Malformed vectors read as zeros
(`Array.getD`), so a malformed certificate can only fail to kill, never kill unsoundly:
the soundness proof `farkas_sound` never looks at the list layout.

Gate: no `sorry`, no `native_decide`, no new axioms.  Every `kill` is computable and
fast (arrays are materialised once per profile in `sysOf`, then each certificate costs
`O(m²)` integer operations).
-/

namespace ZarPrune

open Finset

/-! ## Layer-cake bounds for a monotone `f` (generalising `boundD`) -/

/-- Number of columns of the profile whose sum is `> x`. -/
def cntGt {m n : ℕ} (pf : Profile m n) (x : ℕ) : ℕ :=
  (univ.filter (fun j => x < pf.col j)).card

/-- Lower bound on `∑_{j ∈ S} f (c_j)` over any `k`-set `S` of columns, from the profile
alone: equal to the sum of `f` over the `k` lightest columns (layer-cake form). -/
def lowSum (f : ℕ → ℕ) {m n : ℕ} (pf : Profile m n) (k : ℕ) : ℕ :=
  k * f 0 + ∑ x ∈ range m, (k - cntLt pf (x + 1)) * (f (x + 1) - f x)

/-- Upper bound on `∑_{j ∈ S} f (c_j)` over any `k`-set `S`: the sum of `f` over the `k`
heaviest columns (layer-cake form). -/
def topSumF (f : ℕ → ℕ) {m n : ℕ} (pf : Profile m n) (k : ℕ) : ℕ :=
  k * f 0 + ∑ x ∈ range m, min k (cntGt pf x) * (f (x + 1) - f x)

theorem layer_cake (f : ℕ → ℕ) (hf : Monotone f) (c : ℕ) :
    f c = f 0 + ∑ x ∈ range c, (f (x + 1) - f x) := by
  induction c with
  | zero => simp
  | succ c ih =>
    rw [sum_range_succ, ← add_assoc, ← ih]
    have := hf (Nat.le_add_right c 1)
    omega

theorem layer_cake_le (f : ℕ → ℕ) (hf : Monotone f) (c m : ℕ) (hc : c ≤ m) :
    f c = f 0 + ∑ x ∈ range m, if x < c then f (x + 1) - f x else 0 := by
  rw [layer_cake f hf, sum_range_eq_sum_ite _ hc]

theorem sum_f_eq (f : ℕ → ℕ) (hf : Monotone f) {m n : ℕ} (pf : Profile m n)
    (hc : ∀ j, pf.col j ≤ m) (S : Finset (Fin n)) :
    ∑ j ∈ S, f (pf.col j)
      = S.card * f 0 + ∑ x ∈ range m, (S.filter (fun j => x < pf.col j)).card * (f (x + 1) - f x) := by
  have h1 : ∀ j ∈ S, f (pf.col j)
      = f 0 + ∑ x ∈ range m, if x < pf.col j then f (x + 1) - f x else 0 :=
    fun j _ => layer_cake_le f hf _ m (hc j)
  rw [sum_congr rfl h1, sum_add_distrib, sum_const, smul_eq_mul, sum_comm]
  congr 1
  apply sum_congr rfl
  intro x _
  rw [← sum_filter, sum_const, smul_eq_mul]

/-- At least `|S| - cntLt (x+1)` of the columns of `S` have sum `> x`. -/
theorem card_filter_ge_of_set {m n : ℕ} (pf : Profile m n) (S : Finset (Fin n)) (x : ℕ) :
    S.card - cntLt pf (x + 1) ≤ (S.filter (fun j => x < pf.col j)).card := by
  have h1 := card_filter_add_card_filter_not (s := S) (fun j => x < pf.col j)
  have h2 : (S.filter (fun j => ¬ x < pf.col j)).card ≤ cntLt pf (x + 1) := by
    apply card_le_card
    intro j hj
    rw [mem_filter] at hj ⊢
    exact ⟨mem_univ _, by omega⟩
  omega

/-- **Lightest-sum bound.** -/
theorem lowSum_le (f : ℕ → ℕ) (hf : Monotone f) {m n : ℕ} (pf : Profile m n)
    (hc : ∀ j, pf.col j ≤ m) (S : Finset (Fin n)) :
    lowSum f pf S.card ≤ ∑ j ∈ S, f (pf.col j) := by
  rw [sum_f_eq f hf pf hc]
  unfold lowSum
  apply Nat.add_le_add_left
  apply sum_le_sum
  intro x _
  exact Nat.mul_le_mul_right _ (card_filter_ge_of_set pf S x)

/-- **Heaviest-sum bound** (the dual). -/
theorem le_topSumF (f : ℕ → ℕ) (hf : Monotone f) {m n : ℕ} (pf : Profile m n)
    (hc : ∀ j, pf.col j ≤ m) (S : Finset (Fin n)) :
    ∑ j ∈ S, f (pf.col j) ≤ topSumF f pf S.card := by
  rw [sum_f_eq f hf pf hc]
  unfold topSumF
  apply Nat.add_le_add_left
  apply sum_le_sum
  intro x _
  apply Nat.mul_le_mul_right
  apply le_min (card_filter_le _ _)
  exact card_le_card (filter_subset_filter _ (subset_univ S))

/-! ## Pair codegrees -/

/-- `λ_{i,i'} = |N(i) ∩ N(i')|`: the number of columns with a one in both rows. -/
def codeg {m n : ℕ} (A : Mat m n) (i i' : Fin m) : ℕ :=
  (rowSupport A i ∩ rowSupport A i').card

theorem codeg_comm {m n : ℕ} (A : Mat m n) (i i' : Fin m) : codeg A i i' = codeg A i' i := by
  unfold codeg
  rw [inter_comm]

theorem codeg_le_left {m n : ℕ} (A : Mat m n) (i i' : Fin m) : codeg A i i' ≤ rowSum A i := by
  rw [← card_rowSupport]
  exact card_le_card inter_subset_left

theorem codeg_le_right {m n : ℕ} (A : Mat m n) (i i' : Fin m) : codeg A i i' ≤ rowSum A i' := by
  rw [codeg_comm]
  exact codeg_le_left A i' i

theorem codeg_le_n {m n : ℕ} (A : Mat m n) (i i' : Fin m) : codeg A i i' ≤ n := by
  have := card_le_univ (rowSupport A i ∩ rowSupport A i')
  rw [Fintype.card_fin] at this
  exact this

/-- **F4**: inclusion–exclusion, `|N(i)| + |N(i')| − n ≤ |N(i) ∩ N(i')|`. -/
theorem floor_le_codeg {m n : ℕ} (A : Mat m n) (i i' : Fin m) :
    rowSum A i + rowSum A i' - n ≤ codeg A i i' := by
  have h1 := card_union_add_card_inter (rowSupport A i) (rowSupport A i')
  have h2 := card_le_univ (rowSupport A i ∪ rowSupport A i')
  rw [Fintype.card_fin] at h2
  rw [card_rowSupport, card_rowSupport] at h1
  unfold codeg
  omega

theorem codeg_eq_sum {m n : ℕ} (A : Mat m n) (i i' : Fin m) :
    codeg A i i' = ∑ j ∈ rowSupport A i, if A i' j = true then 1 else 0 := by
  unfold codeg
  have e : rowSupport A i ∩ rowSupport A i' = (rowSupport A i).filter (fun j => A i' j = true) := by
    ext j
    simp [rowSupport, mem_inter, mem_filter]
  rw [e, card_filter]

/-- **F2**: the codegrees of row `i` add up to `∑_{j ∈ N(i)} (c_j − 1)`. -/
theorem sum_codeg_row {m n : ℕ} (A : Mat m n) (i : Fin m) :
    ∑ i' ∈ univ.erase i, codeg A i i' = ∑ j ∈ rowSupport A i, (colSum A j - 1) := by
  simp_rw [codeg_eq_sum]
  rw [sum_comm]
  apply sum_congr rfl
  intro j hj
  rw [← card_filter]
  have e : (univ.erase i).filter (fun i' => A i' j = true) = (support A j).erase i := by
    ext i'
    simp only [support, mem_filter, mem_erase, mem_univ, true_and, and_true]
  rw [e, card_erase_of_mem ((mem_support A j i).mpr ((mem_rowSupport A i j).mp hj)), card_support]

/-- **F1** (ordered form): all codegrees add up to `∑_j c_j (c_j − 1)`. -/
theorem sum_sum_codeg {m n : ℕ} (A : Mat m n) :
    ∑ i, ∑ i' ∈ univ.erase i, codeg A i i' = ∑ j, colSum A j * (colSum A j - 1) := by
  simp_rw [sum_codeg_row]
  have h : ∀ i : Fin m, ∑ j ∈ rowSupport A i, (colSum A j - 1)
      = ∑ j, if A i j = true then colSum A j - 1 else 0 := fun i => by
    unfold rowSupport
    rw [sum_filter]
  simp_rw [h]
  rw [sum_comm]
  apply sum_congr rfl
  intro j _
  rw [← sum_filter, sum_const, smul_eq_mul]
  show (support A j).card * _ = _
  rw [card_support]

/-- **F1** (unordered form): `2 · ∑_{i<i'} λ_{i,i'} = 2 · ∑_j C(c_j, 2)`, stated over ordered
pairs: `∑_i ∑_{i' ≠ i} λ_{i,i'} = 2 · ∑_j C(c_j, 2)`. -/
theorem sum_sum_codeg_choose {m n : ℕ} (A : Mat m n) :
    ∑ i, ∑ i' ∈ univ.erase i, codeg A i i' = 2 * ∑ j, (colSum A j).choose 2 := by
  rw [sum_sum_codeg, mul_sum]
  apply sum_congr rfl
  intro j _
  rw [Nat.choose_two_right, Nat.mul_div_cancel' (Nat.even_mul_pred_self _).two_dvd]

/-! ## F3: the pair-local budget -/

/-- **Pair-local budget.**  For a `K_{s,t}`-free matrix and two distinct rows `i ≠ i'`,
summing `C(c_j − 2, s − 2)` over their common columns gives at most
`(t−1) · C(m−2, s−2)`: if an `(s−2)`-set `R` of the other rows sat in `t` common columns,
`R ∪ {i, i'}` would be an `s`-set of rows common to `t` columns. -/
theorem pairLocalBudget (P : Params) (A : Mat P.m P.n) (h : ¬ HasKst P A) (i i' : Fin P.m)
    (hii : i ≠ i') (hs : 2 ≤ P.s) :
    ∑ j ∈ rowSupport A i ∩ rowSupport A i', (colSum A j - 2).choose (P.s - 2)
      ≤ (P.t - 1) * (P.m - 2).choose (P.s - 2) := by
  have hi'T : i' ∈ (univ : Finset (Fin P.m)).erase i := mem_erase.mpr ⟨hii.symm, mem_univ i'⟩
  have hT : (((univ : Finset (Fin P.m)).erase i).erase i').card = P.m - 2 := by
    rw [card_erase_of_mem hi'T, card_erase_of_mem (mem_univ i), card_univ, Fintype.card_fin]
    omega
  have key := budget_general ((univ.erase i).erase i') (rowSupport A i ∩ rowSupport A i')
    (fun j => ((support A j).erase i).erase i')
    (fun j _ => erase_subset_erase i' (erase_subset_erase i (subset_univ _)))
    (P.s - 2) (P.t - 1) ?_
  · rw [hT] at key
    refine le_trans (le_of_eq ?_) key
    apply sum_congr rfl
    intro j hj
    rw [mem_inter, mem_rowSupport, mem_rowSupport] at hj
    have hij : i ∈ support A j := (mem_support A j i).mpr hj.1
    have hi'j : i' ∈ (support A j).erase i := mem_erase.mpr ⟨hii.symm, (mem_support A j i').mpr hj.2⟩
    rw [card_erase_of_mem hi'j, card_erase_of_mem hij, card_support]
    congr 1
  · intro R hR
    by_contra hcon
    have ht : P.t ≤ ((rowSupport A i ∩ rowSupport A i').filter
        (fun j => R ⊆ ((support A j).erase i).erase i')).card := by
      omega
    obtain ⟨C, hCsub, hC⟩ := Finset.exists_subset_card_eq ht
    rw [Finset.mem_powersetCard] at hR
    have hiR : i ∉ R := fun hi => by
      have := hR.1 hi
      simp at this
    have hi'R : i' ∉ R := fun hi => by
      have := hR.1 hi
      simp at this
    have hi_ins : i ∉ insert i' R := by
      rw [mem_insert]
      rintro (h1 | h1)
      · exact hii h1
      · exact hiR h1
    apply h
    refine hasKst_of_subsets P A (insert i (insert i' R)) ?_ C hC ?_
    · rw [card_insert_of_notMem hi_ins, card_insert_of_notMem hi'R, hR.2]
      omega
    · intro j hj
      have hj' := Finset.mem_filter.mp (hCsub hj)
      rw [mem_inter, mem_rowSupport, mem_rowSupport] at hj'
      rw [Finset.insert_subset_iff, Finset.insert_subset_iff]
      refine ⟨(mem_support A j i).mpr hj'.1.1, (mem_support A j i').mpr hj'.1.2, ?_⟩
      exact hj'.2.trans ((erase_subset i' _).trans (erase_subset i _))

/-- The F2 weight `c ↦ c − 1`. -/
def f2 (c : ℕ) : ℕ := c - 1

theorem f2_mono : Monotone f2 := fun _ _ h => Nat.sub_le_sub_right h 1

/-- The F3 weight `c ↦ C(c − 2, s − 2)`. -/
def f3 (s c : ℕ) : ℕ := (c - 2).choose (s - 2)

theorem f3_mono (s : ℕ) : Monotone (f3 s) := fun _ _ h => Nat.choose_le_choose _ (by omega)

/-- The F3 budget `(t − 1) · C(m − 2, s − 2)`. -/
def budget3 (P : Params) : ℕ := (P.t - 1) * (P.m - 2).choose (P.s - 2)

/-- The largest `k ≤ n` whose `k` lightest values of `C(c_j − 2, s − 2)` fit the budget. -/
def Lcap (P : Params) (pf : Profile P.m P.n) : ℕ :=
  Nat.findGreatest (fun k => lowSum (f3 P.s) pf k ≤ budget3 P) P.n

/-- The F3 cap of a pair: `min (Lcap, r_i, r_{i'})`. -/
def cap (P : Params) (pf : Profile P.m P.n) (i i' : Fin P.m) : ℕ :=
  min (Lcap P pf) (min (pf.row i) (pf.row i'))

/-- The F4 floor of a pair: `r_i + r_{i'} − n` (truncated). -/
def floor (P : Params) (pf : Profile P.m P.n) (i i' : Fin P.m) : ℕ :=
  pf.row i + pf.row i' - P.n

/-- The sum `T2 = ∑_j c_j (c_j − 1)` of the profile. -/
def T2 {m n : ℕ} (pf : Profile m n) : ℕ := ∑ j, pf.col j * (pf.col j - 1)

/-- **F3 as a cap**: `λ_{i,i'} ≤ cap` for a `K_{s,t}`-free matrix with `2 ≤ s`. -/
theorem codeg_le_cap (P : Params) (A : Mat P.m P.n) (h : ¬ HasKst P A) (i i' : Fin P.m)
    (hii : i ≠ i') (hs : 2 ≤ P.s) : codeg A i i' ≤ cap P (profileOf A) i i' := by
  unfold cap
  refine le_min ?_ (le_min (codeg_le_left A i i') (codeg_le_right A i i'))
  apply Nat.le_findGreatest (codeg_le_n A i i')
  have h1 := lowSum_le (f3 P.s) (f3_mono P.s) (profileOf A) (colSum_le A)
    (rowSupport A i ∩ rowSupport A i')
  have h2 := pairLocalBudget P A h i i' hii hs
  exact le_trans h1 h2

/-! ## The Farkas checker -/

/-- Index of the unordered pair `{i, i'}` (`i ≠ i'`) in the lexicographic list of pairs
`(0,1), (0,2), …, (m−2, m−1)`.  Only the Python mirror depends on this layout; the
soundness proof does not. -/
def pairIdx (m i i' : ℕ) : ℕ :=
  if i < i' then i * (2 * m - i - 1) / 2 + (i' - i - 1)
  else i' * (2 * m - i' - 1) / 2 + (i - i' - 1)

/-- Decoded multipliers of one certificate: `y1p, y1m` for `∑ λ ≤ T2` / `≥ T2`, `l i, u i`
for the row lower / upper bounds (F2), `y3` for the pair caps (F3), `y4` for the pair
floors (F4).  All read from a flat `List ℕ` laid out as
`[y1p, y1m, l_0 … l_{m−1}, u_0 … u_{m−1}, y3 (pairs), y4 (pairs)]`; missing entries are 0. -/
structure Mult (m : ℕ) where
  y1p : ℕ
  y1m : ℕ
  l : Fin m → ℕ
  u : Fin m → ℕ
  y3 : Fin m → Fin m → ℕ
  y4 : Fin m → Fin m → ℕ

def decode (m : ℕ) (y : List ℕ) : Mult m :=
  let a := y.toArray
  let np := m * (m - 1) / 2
  { y1p := a.getD 0 0
    y1m := a.getD 1 0
    l := fun i => a.getD (2 + i.val) 0
    u := fun i => a.getD (2 + m + i.val) 0
    y3 := fun i i' => a.getD (2 + 2 * m + pairIdx m i.val i'.val) 0
    y4 := fun i i' => a.getD (2 + 2 * m + np + pairIdx m i.val i'.val) 0 }

/-- The combined coefficient of `λ_{i,i'}` in `∑_k y_k a_k`. -/
def coef (m : ℕ) (Y : Mult m) (i i' : Fin m) : ℤ :=
  (Y.y1p : ℤ) - (Y.y1m : ℤ) + (Y.u i : ℤ) - (Y.l i : ℤ) + (Y.u i' : ℤ) - (Y.l i' : ℤ)
    + (Y.y3 i i' : ℤ) - (Y.y4 i i' : ℤ)

/-- `∑_k y_k a_k ≥ 0` on every off-diagonal pair. -/
def coefOK (m : ℕ) (Y : Mult m) : Bool :=
  allFin m (fun i => allFin m (fun i' => decide (i = i') || decide (0 ≤ coef m Y i i')))

/-- The profile-derived constants of the constraint system, materialised once per profile. -/
structure Sys (m : ℕ) where
  t2 : ℤ
  lo : Array ℤ
  hi : Array ℤ
  cap : Fin m → Fin m → ℤ
  flo : Fin m → Fin m → ℤ

def sysOf (P : Params) (pf : Profile P.m P.n) : Sys P.m :=
  let L := Lcap P pf
  { t2 := (T2 pf : ℤ)
    lo := Array.ofFn (fun i : Fin P.m => (lowSum f2 pf (pf.row i) : ℤ))
    hi := Array.ofFn (fun i : Fin P.m => (topSumF f2 pf (pf.row i) : ℤ))
    cap := fun i i' => ((min L (min (pf.row i) (pf.row i')) : ℕ) : ℤ)
    flo := fun i i' => (pf.row i + pf.row i' - P.n : ℕ) }

/-- `∑_k y_k b_k`, with the row terms counted twice because the ordered sum over
`(i, i')` and `(i', i)` sees each unordered pair twice. -/
def rhs (m : ℕ) (S : Sys m) (Y : Mult m) : ℤ :=
  ((Y.y1p : ℤ) - (Y.y1m : ℤ)) * S.t2
    + 2 * (∑ i, (Y.u i : ℤ) * S.hi.getD i.val 0 - ∑ i, (Y.l i : ℤ) * S.lo.getD i.val 0)
    + ∑ i, ∑ i' ∈ univ.erase i, ((Y.y3 i i' : ℤ) * S.cap i i' - (Y.y4 i i' : ℤ) * S.flo i i')

/-- One certificate kills iff `∑ y_k a_k ≥ 0` coefficientwise and `∑ y_k b_k < 0`. -/
def certKills (m : ℕ) (S : Sys m) (y : List ℕ) : Bool :=
  let Y := decode m y
  coefOK m Y && decide (rhs m S Y < 0)

theorem arrayGetD_ofFn {m : ℕ} (f : Fin m → ℤ) (i : Fin m) : (Array.ofFn f).getD i.val 0 = f i := by
  simp [Array.getD, Array.getElem_ofFn]

theorem coefOK_iff {m : ℕ} (Y : Mult m) (h : coefOK m Y = true) :
    ∀ i, ∀ i' ∈ (univ : Finset (Fin m)).erase i, 0 ≤ coef m Y i i' := by
  intro i i' hi'
  have h1 := (allFin_iff _ _).mp h i
  have h2 := (allFin_iff _ _).mp h1 i'
  rw [Bool.or_eq_true, decide_eq_true_eq, decide_eq_true_eq] at h2
  rcases h2 with h2 | h2
  · exact absurd h2.symm (mem_erase.mp hi').1
  · exact h2

/-- **Soundness of one certificate**: no `K_{s,t}`-free matrix (with `2 ≤ s`) has a profile
on which `certKills` fires. -/
theorem farkas_sound (P : Params) (A : Mat P.m P.n) (hfree : ¬ HasKst P A) (hs : 2 ≤ P.s)
    (y : List ℕ) (hk : certKills P.m (sysOf P (profileOf A)) y = true) : False := by
  simp only [certKills, Bool.and_eq_true, decide_eq_true_eq] at hk
  obtain ⟨hcoef, hrhs⟩ := hk
  have hc := coefOK_iff _ hcoef
  -- the constants of the system, unfolded
  have eT2 : (sysOf P (profileOf A)).t2 = ((T2 (profileOf A) : ℕ) : ℤ) := rfl
  have eLo : ∀ i, (sysOf P (profileOf A)).lo.getD i.val 0
      = ((lowSum f2 (profileOf A) (rowSum A i) : ℕ) : ℤ) := fun i => arrayGetD_ofFn _ i
  have eHi : ∀ i, (sysOf P (profileOf A)).hi.getD i.val 0
      = ((topSumF f2 (profileOf A) (rowSum A i) : ℕ) : ℤ) := fun i => arrayGetD_ofFn _ i
  have eCap : ∀ i i', (sysOf P (profileOf A)).cap i i' = ((cap P (profileOf A) i i' : ℕ) : ℤ) :=
    fun _ _ => rfl
  have eFlo : ∀ i i', (sysOf P (profileOf A)).flo i i' = ((rowSum A i + rowSum A i' - P.n : ℕ) : ℤ) :=
    fun _ _ => rfl
  -- the hidden variables and the facts about them
  have hnn : ∀ i i', (0 : ℤ) ≤ (codeg A i i' : ℤ) := fun i i' => Int.natCast_nonneg _
  have hT : ∑ i, ∑ i' ∈ univ.erase i, (codeg A i i' : ℤ) = (sysOf P (profileOf A)).t2 := by
    rw [eT2]
    have e : T2 (profileOf A) = ∑ i, ∑ i' ∈ univ.erase i, codeg A i i' := by
      unfold T2
      exact (sum_sum_codeg A).symm
    rw [e]
    push_cast
    rfl
  have hlo : ∀ i, (sysOf P (profileOf A)).lo.getD i.val 0 ≤ ∑ i' ∈ univ.erase i, (codeg A i i' : ℤ) := by
    intro i
    rw [eLo]
    have h1 := lowSum_le f2 f2_mono (profileOf A) (colSum_le A) (rowSupport A i)
    rw [card_rowSupport] at h1
    have h2 : lowSum f2 (profileOf A) (rowSum A i) ≤ ∑ i' ∈ univ.erase i, codeg A i i' := by
      rw [sum_codeg_row]
      exact h1
    exact_mod_cast h2
  have hhi : ∀ i, ∑ i' ∈ univ.erase i, (codeg A i i' : ℤ) ≤ (sysOf P (profileOf A)).hi.getD i.val 0 := by
    intro i
    rw [eHi]
    have h1 := le_topSumF f2 f2_mono (profileOf A) (colSum_le A) (rowSupport A i)
    rw [card_rowSupport] at h1
    have h2 : ∑ i' ∈ univ.erase i, codeg A i i' ≤ topSumF f2 (profileOf A) (rowSum A i) := by
      rw [sum_codeg_row]
      exact h1
    exact_mod_cast h2
  have hcap : ∀ i, ∀ i' ∈ (univ : Finset (Fin P.m)).erase i,
      (codeg A i i' : ℤ) ≤ (sysOf P (profileOf A)).cap i i' := by
    intro i i' hi'
    have hii : i ≠ i' := fun e => (mem_erase.mp hi').1 e.symm
    rw [eCap]
    exact_mod_cast codeg_le_cap P A hfree i i' hii hs
  have hflo : ∀ i, ∀ i' ∈ (univ : Finset (Fin P.m)).erase i,
      (sysOf P (profileOf A)).flo i i' ≤ (codeg A i i' : ℤ) := by
    intro i i' _
    rw [eFlo]
    exact_mod_cast floor_le_codeg A i i'
  -- the Farkas combination is non-negative …
  have hS : 0 ≤ ∑ i, ∑ i' ∈ univ.erase i, coef P.m (decode P.m y) i i' * (codeg A i i' : ℤ) :=
    sum_nonneg (fun i _ => sum_nonneg (fun i' hi' => mul_nonneg (hc i i' hi') (hnn i i')))
  -- … and bounded by `rhs`
  have hexp : ∀ i i', coef P.m (decode P.m y) i i' * (codeg A i i' : ℤ)
      = (((decode P.m y).y1p : ℤ) - ((decode P.m y).y1m : ℤ)) * (codeg A i i' : ℤ)
        + (((decode P.m y).u i : ℤ) - ((decode P.m y).l i : ℤ)) * (codeg A i i' : ℤ)
        + (((decode P.m y).u i' : ℤ) - ((decode P.m y).l i' : ℤ)) * (codeg A i i' : ℤ)
        + ((decode P.m y).y3 i i' : ℤ) * (codeg A i i' : ℤ)
        - ((decode P.m y).y4 i i' : ℤ) * (codeg A i i' : ℤ) := by
    intro i i'
    unfold coef
    ring
  simp only [hexp, sum_sub_distrib, sum_add_distrib] at hS
  -- piece 1: the total
  have p1 : ∑ i, ∑ i' ∈ univ.erase i,
      (((decode P.m y).y1p : ℤ) - ((decode P.m y).y1m : ℤ)) * (codeg A i i' : ℤ)
      = (((decode P.m y).y1p : ℤ) - ((decode P.m y).y1m : ℤ)) * (sysOf P (profileOf A)).t2 := by
    simp_rw [← mul_sum]
    rw [hT]
  -- piece 2: row factor on the first index
  have rowbound : ∀ i, (((decode P.m y).u i : ℤ) - ((decode P.m y).l i : ℤ))
        * ∑ i' ∈ univ.erase i, (codeg A i i' : ℤ)
      ≤ ((decode P.m y).u i : ℤ) * (sysOf P (profileOf A)).hi.getD i.val 0
        - ((decode P.m y).l i : ℤ) * (sysOf P (profileOf A)).lo.getD i.val 0 := by
    intro i
    have a := mul_le_mul_of_nonneg_left (hhi i) (Int.natCast_nonneg ((decode P.m y).u i))
    have b := mul_le_mul_of_nonneg_left (hlo i) (Int.natCast_nonneg ((decode P.m y).l i))
    rw [sub_mul]
    linarith
  have p2 : ∑ i, ∑ i' ∈ univ.erase i,
      (((decode P.m y).u i : ℤ) - ((decode P.m y).l i : ℤ)) * (codeg A i i' : ℤ)
      ≤ ∑ i, ((decode P.m y).u i : ℤ) * (sysOf P (profileOf A)).hi.getD i.val 0
        - ∑ i, ((decode P.m y).l i : ℤ) * (sysOf P (profileOf A)).lo.getD i.val 0 := by
    rw [← sum_sub_distrib]
    apply sum_le_sum
    intro i _
    rw [← mul_sum]
    exact rowbound i
  -- piece 3: row factor on the second index (swap the sums, use symmetry)
  have p3 : ∑ i, ∑ i' ∈ univ.erase i,
      (((decode P.m y).u i' : ℤ) - ((decode P.m y).l i' : ℤ)) * (codeg A i i' : ℤ)
      ≤ ∑ i, ((decode P.m y).u i : ℤ) * (sysOf P (profileOf A)).hi.getD i.val 0
        - ∑ i, ((decode P.m y).l i : ℤ) * (sysOf P (profileOf A)).lo.getD i.val 0 := by
    have hswap : ∑ i, ∑ i' ∈ univ.erase i,
        (((decode P.m y).u i' : ℤ) - ((decode P.m y).l i' : ℤ)) * (codeg A i i' : ℤ)
        = ∑ i', ∑ i ∈ univ.erase i',
          (((decode P.m y).u i' : ℤ) - ((decode P.m y).l i' : ℤ)) * (codeg A i i' : ℤ) := by
      apply sum_comm'
      intro x y
      simp only [mem_univ, mem_erase, true_and, and_true, ne_eq]
      exact ⟨fun h => fun e => h e.symm, fun h => fun e => h e.symm⟩
    rw [hswap, ← sum_sub_distrib]
    apply sum_le_sum
    intro i' _
    rw [← mul_sum]
    have e : ∑ i ∈ univ.erase i', (codeg A i i' : ℤ) = ∑ i ∈ univ.erase i', (codeg A i' i : ℤ) :=
      sum_congr rfl (fun i _ => by rw [codeg_comm])
    rw [e]
    exact rowbound i'
  -- pieces 4 / 5: caps and floors
  have p4 : ∑ i, ∑ i' ∈ univ.erase i, ((decode P.m y).y3 i i' : ℤ) * (codeg A i i' : ℤ)
      ≤ ∑ i, ∑ i' ∈ univ.erase i, ((decode P.m y).y3 i i' : ℤ) * (sysOf P (profileOf A)).cap i i' :=
    sum_le_sum (fun i _ => sum_le_sum (fun i' hi' =>
      mul_le_mul_of_nonneg_left (hcap i i' hi') (Int.natCast_nonneg _)))
  have p5 : ∑ i, ∑ i' ∈ univ.erase i, ((decode P.m y).y4 i i' : ℤ) * (sysOf P (profileOf A)).flo i i'
      ≤ ∑ i, ∑ i' ∈ univ.erase i, ((decode P.m y).y4 i i' : ℤ) * (codeg A i i' : ℤ) :=
    sum_le_sum (fun i _ => sum_le_sum (fun i' hi' =>
      mul_le_mul_of_nonneg_left (hflo i i' hi') (Int.natCast_nonneg _)))
  have hr : rhs P.m (sysOf P (profileOf A)) (decode P.m y)
      = (((decode P.m y).y1p : ℤ) - ((decode P.m y).y1m : ℤ)) * (sysOf P (profileOf A)).t2
        + 2 * (∑ i, ((decode P.m y).u i : ℤ) * (sysOf P (profileOf A)).hi.getD i.val 0
               - ∑ i, ((decode P.m y).l i : ℤ) * (sysOf P (profileOf A)).lo.getD i.val 0)
        + (∑ i, ∑ i' ∈ univ.erase i, ((decode P.m y).y3 i i' : ℤ) * (sysOf P (profileOf A)).cap i i'
           - ∑ i, ∑ i' ∈ univ.erase i, ((decode P.m y).y4 i i' : ℤ) * (sysOf P (profileOf A)).flo i i') := by
    unfold rhs
    simp only [sum_sub_distrib]
  rw [p1] at hS
  linarith

/-- **The Farkas schema.**  `ys` is a list of multiplier vectors (layout: `decode`); a
profile is killed when some vector certifies the infeasibility of the pair-codegree
system F1–F4.  Sound for every `P` with `2 ≤ P.s` (the guard is part of `kill`). -/
def Prune.ofFarkas (P : Params) (ys : List (List ℕ)) : Prune P where
  name := "farkas over pair codegrees"
  kill := fun pf => decide (2 ≤ P.s) && (let S := sysOf P pf; ys.any (fun y => certKills P.m S y))
  sound := by
    intro A hk hv
    rw [Bool.and_eq_true, decide_eq_true_eq] at hk
    obtain ⟨hs, hany⟩ := hk
    rw [List.any_eq_true] at hany
    obtain ⟨y, _, hy⟩ := hany
    exact farkas_sound P A hv.1 hs y hy

end ZarPrune


#print axioms ZarPrune.cntGt
#print axioms ZarPrune.lowSum
#print axioms ZarPrune.topSumF
#print axioms ZarPrune.layer_cake
#print axioms ZarPrune.layer_cake_le
#print axioms ZarPrune.sum_f_eq
#print axioms ZarPrune.card_filter_ge_of_set
#print axioms ZarPrune.lowSum_le
#print axioms ZarPrune.le_topSumF
#print axioms ZarPrune.codeg
#print axioms ZarPrune.codeg_comm
#print axioms ZarPrune.codeg_le_left
#print axioms ZarPrune.codeg_le_right
#print axioms ZarPrune.codeg_le_n
#print axioms ZarPrune.floor_le_codeg
#print axioms ZarPrune.codeg_eq_sum
#print axioms ZarPrune.sum_codeg_row
#print axioms ZarPrune.sum_sum_codeg
#print axioms ZarPrune.sum_sum_codeg_choose
#print axioms ZarPrune.pairLocalBudget
#print axioms ZarPrune.f2
#print axioms ZarPrune.f2_mono
#print axioms ZarPrune.f3
#print axioms ZarPrune.f3_mono
#print axioms ZarPrune.budget3
#print axioms ZarPrune.Lcap
#print axioms ZarPrune.cap
#print axioms ZarPrune.floor
#print axioms ZarPrune.T2
#print axioms ZarPrune.codeg_le_cap
#print axioms ZarPrune.pairIdx
#print axioms ZarPrune.Mult
#print axioms ZarPrune.decode
#print axioms ZarPrune.coef
#print axioms ZarPrune.coefOK
#print axioms ZarPrune.Sys
#print axioms ZarPrune.sysOf
#print axioms ZarPrune.rhs
#print axioms ZarPrune.certKills
#print axioms ZarPrune.arrayGetD_ofFn
#print axioms ZarPrune.coefOK_iff
#print axioms ZarPrune.farkas_sound
#print axioms ZarPrune.Prune.ofFarkas

open ZarPrune in
abbrev T9 : ZarPrune.Params := ⟨9, 9, 3, 3, 50⟩
abbrev T13 : ZarPrune.Params := ⟨13, 13, 3, 3, 93⟩
def pfOf (m n : Nat) (r c : List Nat) : ZarPrune.Profile m n :=
  { row := fun i => r.getD i.val 0, col := fun j => c.getD j.val 0 }

-- semantic checks on (9,9,50): killed [7,7,6,5,5,5,5,5,5]/[6,6,6,6,6,5,5,5,5] (pair of 7-rows must share >= 5 > Lcap = 4),
-- not killed the near-regular [6,6,6,6,6,5,5,5,5] both sides
#eval (ZarPrune.Prune.ofFarkas T9 [[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1]]).kill (pfOf 9 9 [7,7,6,5,5,5,5,5,5] [6,6,6,6,6,5,5,5,5])
#eval (ZarPrune.Prune.ofFarkas T9 [[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1]]).kill (pfOf 9 9 [6,6,6,6,6,5,5,5,5] [6,6,6,6,6,5,5,5,5])
#eval ZarPrune.Lcap T9 (pfOf 9 9 [7,7,6,5,5,5,5,5,5] [6,6,6,6,6,5,5,5,5])
#eval (ZarPrune.sysOf T9 (pfOf 9 9 [7,7,6,5,5,5,5,5,5] [6,6,6,6,6,5,5,5,5])).lo
#eval (ZarPrune.sysOf T9 (pfOf 9 9 [7,7,6,5,5,5,5,5,5] [6,6,6,6,6,5,5,5,5])).hi
#eval (ZarPrune.sysOf T9 (pfOf 9 9 [7,7,6,5,5,5,5,5,5] [6,6,6,6,6,5,5,5,5])).t2
-- malformed certificates never kill unsoundly: empty / short / garbage lists
#eval (ZarPrune.Prune.ofFarkas T9 [[], [1], [5,5,5], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1]]).kill (pfOf 9 9 [7,7,6,5,5,5,5,5,5] [6,6,6,6,6,5,5,5,5])
-- s = 1 guard
#eval (ZarPrune.Prune.ofFarkas ⟨9, 9, 1, 3, 50⟩ [[0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1], [0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1]]).kill (pfOf 9 9 [7,7,6,5,5,5,5,5,5] [6,6,6,6,6,5,5,5,5])

-- timing: the whole (13,13,93) pure table (1024 cases) with 2 certificates; expected 449 kills
def cases13 : List (List Nat × List Nat) := [
  ([8,8,7,7,7,7,7,7,7,7,7,7,7], [8,8,7,7,7,7,7,7,7,7,7,7,7]),
  ([8,8,7,7,7,7,7,7,7,7,7,7,7], [8,8,8,7,7,7,7,7,7,7,7,7,6]),
  ([8,8,7,7,7,7,7,7,7,7,7,7,7], [8,8,8,8,7,7,7,7,7,7,7,6,6]),
  ([8,8,7,7,7,7,7,7,7,7,7,7,7], [8,8,8,8,7,7,7,7,7,7,7,7,5]),
  ([8,8,7,7,7,7,7,7,7,7,7,7,7], [8,8,8,8,8,7,7,7,7,7,6,6,6]),
  ([8,8,7,7,7,7,7,7,7,7,7,7,7], [8,8,8,8,8,7,7,7,7,7,7,6,5]),
  ([8,8,7,7,7,7,7,7,7,7,7,7,7], [8,8,8,8,8,7,7,7,7,7,7,7,4]),
  ([8,8,7,7,7,7,7,7,7,7,7,7,7], [9,7,7,7,7,7,7,7,7,7,7,7,7]),
  ([8,8,7,7,7,7,7,7,7,7,7,7,7], [9,8,7,7,7,7,7,7,7,7,7,7,6]),
  ([8,8,7,7,7,7,7,7,7,7,7,7,7], [9,8,8,7,7,7,7,7,7,7,7,6,6]),
  ([8,8,7,7,7,7,7,7,7,7,7,7,7], [9,8,8,7,7,7,7,7,7,7,7,7,5]),
  ([8,8,7,7,7,7,7,7,7,7,7,7,7], [9,8,8,8,7,7,7,7,7,7,6,6,6]),
  ([8,8,7,7,7,7,7,7,7,7,7,7,7], [9,8,8,8,7,7,7,7,7,7,7,6,5]),
  ([8,8,7,7,7,7,7,7,7,7,7,7,7], [9,8,8,8,7,7,7,7,7,7,7,7,4]),
  ([8,8,7,7,7,7,7,7,7,7,7,7,7], [9,9,7,7,7,7,7,7,7,7,7,6,6]),
  ([8,8,7,7,7,7,7,7,7,7,7,7,7], [9,9,7,7,7,7,7,7,7,7,7,7,5]),
  ([8,8,7,7,7,7,7,7,7,7,7,7,7], [9,9,8,7,7,7,7,7,7,7,6,6,6]),
  ([8,8,7,7,7,7,7,7,7,7,7,7,7], [9,9,8,7,7,7,7,7,7,7,7,6,5]),
  ([8,8,7,7,7,7,7,7,7,7,7,7,7], [9,9,8,7,7,7,7,7,7,7,7,7,4]),
  ([8,8,7,7,7,7,7,7,7,7,7,7,7], [10,7,7,7,7,7,7,7,7,7,7,7,6]),
  ([8,8,7,7,7,7,7,7,7,7,7,7,7], [10,8,7,7,7,7,7,7,7,7,7,6,6]),
  ([8,8,7,7,7,7,7,7,7,7,7,7,7], [10,8,7,7,7,7,7,7,7,7,7,7,5]),
  ([8,8,7,7,7,7,7,7,7,7,7,7,7], [10,8,8,7,7,7,7,7,7,7,6,6,6]),
  ([8,8,7,7,7,7,7,7,7,7,7,7,7], [10,8,8,7,7,7,7,7,7,7,7,6,5]),
  ([8,8,7,7,7,7,7,7,7,7,7,7,7], [10,8,8,7,7,7,7,7,7,7,7,7,4]),
  ([8,8,7,7,7,7,7,7,7,7,7,7,7], [10,9,7,7,7,7,7,7,7,7,6,6,6]),
  ([8,8,7,7,7,7,7,7,7,7,7,7,7], [10,9,7,7,7,7,7,7,7,7,7,6,5]),
  ([8,8,7,7,7,7,7,7,7,7,7,7,7], [10,9,7,7,7,7,7,7,7,7,7,7,4]),
  ([8,8,7,7,7,7,7,7,7,7,7,7,7], [11,7,7,7,7,7,7,7,7,7,7,6,6]),
  ([8,8,7,7,7,7,7,7,7,7,7,7,7], [11,7,7,7,7,7,7,7,7,7,7,7,5]),
  ([8,8,7,7,7,7,7,7,7,7,7,7,7], [11,8,7,7,7,7,7,7,7,7,6,6,6]),
  ([8,8,7,7,7,7,7,7,7,7,7,7,7], [11,8,7,7,7,7,7,7,7,7,7,6,5]),
  ([8,8,8,7,7,7,7,7,7,7,7,7,6], [8,8,7,7,7,7,7,7,7,7,7,7,7]),
  ([8,8,8,7,7,7,7,7,7,7,7,7,6], [8,8,8,7,7,7,7,7,7,7,7,7,6]),
  ([8,8,8,7,7,7,7,7,7,7,7,7,6], [8,8,8,8,7,7,7,7,7,7,7,6,6]),
  ([8,8,8,7,7,7,7,7,7,7,7,7,6], [8,8,8,8,7,7,7,7,7,7,7,7,5]),
  ([8,8,8,7,7,7,7,7,7,7,7,7,6], [8,8,8,8,8,7,7,7,7,7,6,6,6]),
  ([8,8,8,7,7,7,7,7,7,7,7,7,6], [8,8,8,8,8,7,7,7,7,7,7,6,5]),
  ([8,8,8,7,7,7,7,7,7,7,7,7,6], [8,8,8,8,8,7,7,7,7,7,7,7,4]),
  ([8,8,8,7,7,7,7,7,7,7,7,7,6], [9,7,7,7,7,7,7,7,7,7,7,7,7]),
  ([8,8,8,7,7,7,7,7,7,7,7,7,6], [9,8,7,7,7,7,7,7,7,7,7,7,6]),
  ([8,8,8,7,7,7,7,7,7,7,7,7,6], [9,8,8,7,7,7,7,7,7,7,7,6,6]),
  ([8,8,8,7,7,7,7,7,7,7,7,7,6], [9,8,8,7,7,7,7,7,7,7,7,7,5]),
  ([8,8,8,7,7,7,7,7,7,7,7,7,6], [9,8,8,8,7,7,7,7,7,7,6,6,6]),
  ([8,8,8,7,7,7,7,7,7,7,7,7,6], [9,8,8,8,7,7,7,7,7,7,7,6,5]),
  ([8,8,8,7,7,7,7,7,7,7,7,7,6], [9,8,8,8,7,7,7,7,7,7,7,7,4]),
  ([8,8,8,7,7,7,7,7,7,7,7,7,6], [9,9,7,7,7,7,7,7,7,7,7,6,6]),
  ([8,8,8,7,7,7,7,7,7,7,7,7,6], [9,9,7,7,7,7,7,7,7,7,7,7,5]),
  ([8,8,8,7,7,7,7,7,7,7,7,7,6], [9,9,8,7,7,7,7,7,7,7,6,6,6]),
  ([8,8,8,7,7,7,7,7,7,7,7,7,6], [9,9,8,7,7,7,7,7,7,7,7,6,5]),
  ([8,8,8,7,7,7,7,7,7,7,7,7,6], [9,9,8,7,7,7,7,7,7,7,7,7,4]),
  ([8,8,8,7,7,7,7,7,7,7,7,7,6], [10,7,7,7,7,7,7,7,7,7,7,7,6]),
  ([8,8,8,7,7,7,7,7,7,7,7,7,6], [10,8,7,7,7,7,7,7,7,7,7,6,6]),
  ([8,8,8,7,7,7,7,7,7,7,7,7,6], [10,8,7,7,7,7,7,7,7,7,7,7,5]),
  ([8,8,8,7,7,7,7,7,7,7,7,7,6], [10,8,8,7,7,7,7,7,7,7,6,6,6]),
  ([8,8,8,7,7,7,7,7,7,7,7,7,6], [10,8,8,7,7,7,7,7,7,7,7,6,5]),
  ([8,8,8,7,7,7,7,7,7,7,7,7,6], [10,8,8,7,7,7,7,7,7,7,7,7,4]),
  ([8,8,8,7,7,7,7,7,7,7,7,7,6], [10,9,7,7,7,7,7,7,7,7,6,6,6]),
  ([8,8,8,7,7,7,7,7,7,7,7,7,6], [10,9,7,7,7,7,7,7,7,7,7,6,5]),
  ([8,8,8,7,7,7,7,7,7,7,7,7,6], [10,9,7,7,7,7,7,7,7,7,7,7,4]),
  ([8,8,8,7,7,7,7,7,7,7,7,7,6], [11,7,7,7,7,7,7,7,7,7,7,6,6]),
  ([8,8,8,7,7,7,7,7,7,7,7,7,6], [11,7,7,7,7,7,7,7,7,7,7,7,5]),
  ([8,8,8,7,7,7,7,7,7,7,7,7,6], [11,8,7,7,7,7,7,7,7,7,6,6,6]),
  ([8,8,8,7,7,7,7,7,7,7,7,7,6], [11,8,7,7,7,7,7,7,7,7,7,6,5]),
  ([8,8,8,8,7,7,7,7,7,7,7,6,6], [8,8,7,7,7,7,7,7,7,7,7,7,7]),
  ([8,8,8,8,7,7,7,7,7,7,7,6,6], [8,8,8,7,7,7,7,7,7,7,7,7,6]),
  ([8,8,8,8,7,7,7,7,7,7,7,6,6], [8,8,8,8,7,7,7,7,7,7,7,6,6]),
  ([8,8,8,8,7,7,7,7,7,7,7,6,6], [8,8,8,8,7,7,7,7,7,7,7,7,5]),
  ([8,8,8,8,7,7,7,7,7,7,7,6,6], [8,8,8,8,8,7,7,7,7,7,6,6,6]),
  ([8,8,8,8,7,7,7,7,7,7,7,6,6], [8,8,8,8,8,7,7,7,7,7,7,6,5]),
  ([8,8,8,8,7,7,7,7,7,7,7,6,6], [8,8,8,8,8,7,7,7,7,7,7,7,4]),
  ([8,8,8,8,7,7,7,7,7,7,7,6,6], [9,7,7,7,7,7,7,7,7,7,7,7,7]),
  ([8,8,8,8,7,7,7,7,7,7,7,6,6], [9,8,7,7,7,7,7,7,7,7,7,7,6]),
  ([8,8,8,8,7,7,7,7,7,7,7,6,6], [9,8,8,7,7,7,7,7,7,7,7,6,6]),
  ([8,8,8,8,7,7,7,7,7,7,7,6,6], [9,8,8,7,7,7,7,7,7,7,7,7,5]),
  ([8,8,8,8,7,7,7,7,7,7,7,6,6], [9,8,8,8,7,7,7,7,7,7,6,6,6]),
  ([8,8,8,8,7,7,7,7,7,7,7,6,6], [9,8,8,8,7,7,7,7,7,7,7,6,5]),
  ([8,8,8,8,7,7,7,7,7,7,7,6,6], [9,8,8,8,7,7,7,7,7,7,7,7,4]),
  ([8,8,8,8,7,7,7,7,7,7,7,6,6], [9,9,7,7,7,7,7,7,7,7,7,6,6]),
  ([8,8,8,8,7,7,7,7,7,7,7,6,6], [9,9,7,7,7,7,7,7,7,7,7,7,5]),
  ([8,8,8,8,7,7,7,7,7,7,7,6,6], [9,9,8,7,7,7,7,7,7,7,6,6,6]),
  ([8,8,8,8,7,7,7,7,7,7,7,6,6], [9,9,8,7,7,7,7,7,7,7,7,6,5]),
  ([8,8,8,8,7,7,7,7,7,7,7,6,6], [9,9,8,7,7,7,7,7,7,7,7,7,4]),
  ([8,8,8,8,7,7,7,7,7,7,7,6,6], [10,7,7,7,7,7,7,7,7,7,7,7,6]),
  ([8,8,8,8,7,7,7,7,7,7,7,6,6], [10,8,7,7,7,7,7,7,7,7,7,6,6]),
  ([8,8,8,8,7,7,7,7,7,7,7,6,6], [10,8,7,7,7,7,7,7,7,7,7,7,5]),
  ([8,8,8,8,7,7,7,7,7,7,7,6,6], [10,8,8,7,7,7,7,7,7,7,6,6,6]),
  ([8,8,8,8,7,7,7,7,7,7,7,6,6], [10,8,8,7,7,7,7,7,7,7,7,6,5]),
  ([8,8,8,8,7,7,7,7,7,7,7,6,6], [10,8,8,7,7,7,7,7,7,7,7,7,4]),
  ([8,8,8,8,7,7,7,7,7,7,7,6,6], [10,9,7,7,7,7,7,7,7,7,6,6,6]),
  ([8,8,8,8,7,7,7,7,7,7,7,6,6], [10,9,7,7,7,7,7,7,7,7,7,6,5]),
  ([8,8,8,8,7,7,7,7,7,7,7,6,6], [10,9,7,7,7,7,7,7,7,7,7,7,4]),
  ([8,8,8,8,7,7,7,7,7,7,7,6,6], [11,7,7,7,7,7,7,7,7,7,7,6,6]),
  ([8,8,8,8,7,7,7,7,7,7,7,6,6], [11,7,7,7,7,7,7,7,7,7,7,7,5]),
  ([8,8,8,8,7,7,7,7,7,7,7,6,6], [11,8,7,7,7,7,7,7,7,7,6,6,6]),
  ([8,8,8,8,7,7,7,7,7,7,7,6,6], [11,8,7,7,7,7,7,7,7,7,7,6,5]),
  ([8,8,8,8,7,7,7,7,7,7,7,7,5], [8,8,7,7,7,7,7,7,7,7,7,7,7]),
  ([8,8,8,8,7,7,7,7,7,7,7,7,5], [8,8,8,7,7,7,7,7,7,7,7,7,6]),
  ([8,8,8,8,7,7,7,7,7,7,7,7,5], [8,8,8,8,7,7,7,7,7,7,7,6,6]),
  ([8,8,8,8,7,7,7,7,7,7,7,7,5], [8,8,8,8,7,7,7,7,7,7,7,7,5]),
  ([8,8,8,8,7,7,7,7,7,7,7,7,5], [8,8,8,8,8,7,7,7,7,7,6,6,6]),
  ([8,8,8,8,7,7,7,7,7,7,7,7,5], [8,8,8,8,8,7,7,7,7,7,7,6,5]),
  ([8,8,8,8,7,7,7,7,7,7,7,7,5], [8,8,8,8,8,7,7,7,7,7,7,7,4]),
  ([8,8,8,8,7,7,7,7,7,7,7,7,5], [9,7,7,7,7,7,7,7,7,7,7,7,7]),
  ([8,8,8,8,7,7,7,7,7,7,7,7,5], [9,8,7,7,7,7,7,7,7,7,7,7,6]),
  ([8,8,8,8,7,7,7,7,7,7,7,7,5], [9,8,8,7,7,7,7,7,7,7,7,6,6]),
  ([8,8,8,8,7,7,7,7,7,7,7,7,5], [9,8,8,7,7,7,7,7,7,7,7,7,5]),
  ([8,8,8,8,7,7,7,7,7,7,7,7,5], [9,8,8,8,7,7,7,7,7,7,6,6,6]),
  ([8,8,8,8,7,7,7,7,7,7,7,7,5], [9,8,8,8,7,7,7,7,7,7,7,6,5]),
  ([8,8,8,8,7,7,7,7,7,7,7,7,5], [9,8,8,8,7,7,7,7,7,7,7,7,4]),
  ([8,8,8,8,7,7,7,7,7,7,7,7,5], [9,9,7,7,7,7,7,7,7,7,7,6,6]),
  ([8,8,8,8,7,7,7,7,7,7,7,7,5], [9,9,7,7,7,7,7,7,7,7,7,7,5]),
  ([8,8,8,8,7,7,7,7,7,7,7,7,5], [9,9,8,7,7,7,7,7,7,7,6,6,6]),
  ([8,8,8,8,7,7,7,7,7,7,7,7,5], [9,9,8,7,7,7,7,7,7,7,7,6,5]),
  ([8,8,8,8,7,7,7,7,7,7,7,7,5], [9,9,8,7,7,7,7,7,7,7,7,7,4]),
  ([8,8,8,8,7,7,7,7,7,7,7,7,5], [10,7,7,7,7,7,7,7,7,7,7,7,6]),
  ([8,8,8,8,7,7,7,7,7,7,7,7,5], [10,8,7,7,7,7,7,7,7,7,7,6,6]),
  ([8,8,8,8,7,7,7,7,7,7,7,7,5], [10,8,7,7,7,7,7,7,7,7,7,7,5]),
  ([8,8,8,8,7,7,7,7,7,7,7,7,5], [10,8,8,7,7,7,7,7,7,7,6,6,6]),
  ([8,8,8,8,7,7,7,7,7,7,7,7,5], [10,8,8,7,7,7,7,7,7,7,7,6,5]),
  ([8,8,8,8,7,7,7,7,7,7,7,7,5], [10,8,8,7,7,7,7,7,7,7,7,7,4]),
  ([8,8,8,8,7,7,7,7,7,7,7,7,5], [10,9,7,7,7,7,7,7,7,7,6,6,6]),
  ([8,8,8,8,7,7,7,7,7,7,7,7,5], [10,9,7,7,7,7,7,7,7,7,7,6,5]),
  ([8,8,8,8,7,7,7,7,7,7,7,7,5], [10,9,7,7,7,7,7,7,7,7,7,7,4]),
  ([8,8,8,8,7,7,7,7,7,7,7,7,5], [11,7,7,7,7,7,7,7,7,7,7,6,6]),
  ([8,8,8,8,7,7,7,7,7,7,7,7,5], [11,7,7,7,7,7,7,7,7,7,7,7,5]),
  ([8,8,8,8,7,7,7,7,7,7,7,7,5], [11,8,7,7,7,7,7,7,7,7,6,6,6]),
  ([8,8,8,8,7,7,7,7,7,7,7,7,5], [11,8,7,7,7,7,7,7,7,7,7,6,5]),
  ([8,8,8,8,8,7,7,7,7,7,6,6,6], [8,8,7,7,7,7,7,7,7,7,7,7,7]),
  ([8,8,8,8,8,7,7,7,7,7,6,6,6], [8,8,8,7,7,7,7,7,7,7,7,7,6]),
  ([8,8,8,8,8,7,7,7,7,7,6,6,6], [8,8,8,8,7,7,7,7,7,7,7,6,6]),
  ([8,8,8,8,8,7,7,7,7,7,6,6,6], [8,8,8,8,7,7,7,7,7,7,7,7,5]),
  ([8,8,8,8,8,7,7,7,7,7,6,6,6], [8,8,8,8,8,7,7,7,7,7,6,6,6]),
  ([8,8,8,8,8,7,7,7,7,7,6,6,6], [8,8,8,8,8,7,7,7,7,7,7,6,5]),
  ([8,8,8,8,8,7,7,7,7,7,6,6,6], [8,8,8,8,8,7,7,7,7,7,7,7,4]),
  ([8,8,8,8,8,7,7,7,7,7,6,6,6], [9,7,7,7,7,7,7,7,7,7,7,7,7]),
  ([8,8,8,8,8,7,7,7,7,7,6,6,6], [9,8,7,7,7,7,7,7,7,7,7,7,6]),
  ([8,8,8,8,8,7,7,7,7,7,6,6,6], [9,8,8,7,7,7,7,7,7,7,7,6,6]),
  ([8,8,8,8,8,7,7,7,7,7,6,6,6], [9,8,8,7,7,7,7,7,7,7,7,7,5]),
  ([8,8,8,8,8,7,7,7,7,7,6,6,6], [9,8,8,8,7,7,7,7,7,7,6,6,6]),
  ([8,8,8,8,8,7,7,7,7,7,6,6,6], [9,8,8,8,7,7,7,7,7,7,7,6,5]),
  ([8,8,8,8,8,7,7,7,7,7,6,6,6], [9,8,8,8,7,7,7,7,7,7,7,7,4]),
  ([8,8,8,8,8,7,7,7,7,7,6,6,6], [9,9,7,7,7,7,7,7,7,7,7,6,6]),
  ([8,8,8,8,8,7,7,7,7,7,6,6,6], [9,9,7,7,7,7,7,7,7,7,7,7,5]),
  ([8,8,8,8,8,7,7,7,7,7,6,6,6], [9,9,8,7,7,7,7,7,7,7,6,6,6]),
  ([8,8,8,8,8,7,7,7,7,7,6,6,6], [9,9,8,7,7,7,7,7,7,7,7,6,5]),
  ([8,8,8,8,8,7,7,7,7,7,6,6,6], [9,9,8,7,7,7,7,7,7,7,7,7,4]),
  ([8,8,8,8,8,7,7,7,7,7,6,6,6], [10,7,7,7,7,7,7,7,7,7,7,7,6]),
  ([8,8,8,8,8,7,7,7,7,7,6,6,6], [10,8,7,7,7,7,7,7,7,7,7,6,6]),
  ([8,8,8,8,8,7,7,7,7,7,6,6,6], [10,8,7,7,7,7,7,7,7,7,7,7,5]),
  ([8,8,8,8,8,7,7,7,7,7,6,6,6], [10,8,8,7,7,7,7,7,7,7,6,6,6]),
  ([8,8,8,8,8,7,7,7,7,7,6,6,6], [10,8,8,7,7,7,7,7,7,7,7,6,5]),
  ([8,8,8,8,8,7,7,7,7,7,6,6,6], [10,8,8,7,7,7,7,7,7,7,7,7,4]),
  ([8,8,8,8,8,7,7,7,7,7,6,6,6], [10,9,7,7,7,7,7,7,7,7,6,6,6]),
  ([8,8,8,8,8,7,7,7,7,7,6,6,6], [10,9,7,7,7,7,7,7,7,7,7,6,5]),
  ([8,8,8,8,8,7,7,7,7,7,6,6,6], [10,9,7,7,7,7,7,7,7,7,7,7,4]),
  ([8,8,8,8,8,7,7,7,7,7,6,6,6], [11,7,7,7,7,7,7,7,7,7,7,6,6]),
  ([8,8,8,8,8,7,7,7,7,7,6,6,6], [11,7,7,7,7,7,7,7,7,7,7,7,5]),
  ([8,8,8,8,8,7,7,7,7,7,6,6,6], [11,8,7,7,7,7,7,7,7,7,6,6,6]),
  ([8,8,8,8,8,7,7,7,7,7,6,6,6], [11,8,7,7,7,7,7,7,7,7,7,6,5]),
  ([8,8,8,8,8,7,7,7,7,7,7,6,5], [8,8,7,7,7,7,7,7,7,7,7,7,7]),
  ([8,8,8,8,8,7,7,7,7,7,7,6,5], [8,8,8,7,7,7,7,7,7,7,7,7,6]),
  ([8,8,8,8,8,7,7,7,7,7,7,6,5], [8,8,8,8,7,7,7,7,7,7,7,6,6]),
  ([8,8,8,8,8,7,7,7,7,7,7,6,5], [8,8,8,8,7,7,7,7,7,7,7,7,5]),
  ([8,8,8,8,8,7,7,7,7,7,7,6,5], [8,8,8,8,8,7,7,7,7,7,6,6,6]),
  ([8,8,8,8,8,7,7,7,7,7,7,6,5], [8,8,8,8,8,7,7,7,7,7,7,6,5]),
  ([8,8,8,8,8,7,7,7,7,7,7,6,5], [8,8,8,8,8,7,7,7,7,7,7,7,4]),
  ([8,8,8,8,8,7,7,7,7,7,7,6,5], [9,7,7,7,7,7,7,7,7,7,7,7,7]),
  ([8,8,8,8,8,7,7,7,7,7,7,6,5], [9,8,7,7,7,7,7,7,7,7,7,7,6]),
  ([8,8,8,8,8,7,7,7,7,7,7,6,5], [9,8,8,7,7,7,7,7,7,7,7,6,6]),
  ([8,8,8,8,8,7,7,7,7,7,7,6,5], [9,8,8,7,7,7,7,7,7,7,7,7,5]),
  ([8,8,8,8,8,7,7,7,7,7,7,6,5], [9,8,8,8,7,7,7,7,7,7,6,6,6]),
  ([8,8,8,8,8,7,7,7,7,7,7,6,5], [9,8,8,8,7,7,7,7,7,7,7,6,5]),
  ([8,8,8,8,8,7,7,7,7,7,7,6,5], [9,8,8,8,7,7,7,7,7,7,7,7,4]),
  ([8,8,8,8,8,7,7,7,7,7,7,6,5], [9,9,7,7,7,7,7,7,7,7,7,6,6]),
  ([8,8,8,8,8,7,7,7,7,7,7,6,5], [9,9,7,7,7,7,7,7,7,7,7,7,5]),
  ([8,8,8,8,8,7,7,7,7,7,7,6,5], [9,9,8,7,7,7,7,7,7,7,6,6,6]),
  ([8,8,8,8,8,7,7,7,7,7,7,6,5], [9,9,8,7,7,7,7,7,7,7,7,6,5]),
  ([8,8,8,8,8,7,7,7,7,7,7,6,5], [9,9,8,7,7,7,7,7,7,7,7,7,4]),
  ([8,8,8,8,8,7,7,7,7,7,7,6,5], [10,7,7,7,7,7,7,7,7,7,7,7,6]),
  ([8,8,8,8,8,7,7,7,7,7,7,6,5], [10,8,7,7,7,7,7,7,7,7,7,6,6]),
  ([8,8,8,8,8,7,7,7,7,7,7,6,5], [10,8,7,7,7,7,7,7,7,7,7,7,5]),
  ([8,8,8,8,8,7,7,7,7,7,7,6,5], [10,8,8,7,7,7,7,7,7,7,6,6,6]),
  ([8,8,8,8,8,7,7,7,7,7,7,6,5], [10,8,8,7,7,7,7,7,7,7,7,6,5]),
  ([8,8,8,8,8,7,7,7,7,7,7,6,5], [10,8,8,7,7,7,7,7,7,7,7,7,4]),
  ([8,8,8,8,8,7,7,7,7,7,7,6,5], [10,9,7,7,7,7,7,7,7,7,6,6,6]),
  ([8,8,8,8,8,7,7,7,7,7,7,6,5], [10,9,7,7,7,7,7,7,7,7,7,6,5]),
  ([8,8,8,8,8,7,7,7,7,7,7,6,5], [10,9,7,7,7,7,7,7,7,7,7,7,4]),
  ([8,8,8,8,8,7,7,7,7,7,7,6,5], [11,7,7,7,7,7,7,7,7,7,7,6,6]),
  ([8,8,8,8,8,7,7,7,7,7,7,6,5], [11,7,7,7,7,7,7,7,7,7,7,7,5]),
  ([8,8,8,8,8,7,7,7,7,7,7,6,5], [11,8,7,7,7,7,7,7,7,7,6,6,6]),
  ([8,8,8,8,8,7,7,7,7,7,7,6,5], [11,8,7,7,7,7,7,7,7,7,7,6,5]),
  ([8,8,8,8,8,7,7,7,7,7,7,7,4], [8,8,7,7,7,7,7,7,7,7,7,7,7]),
  ([8,8,8,8,8,7,7,7,7,7,7,7,4], [8,8,8,7,7,7,7,7,7,7,7,7,6]),
  ([8,8,8,8,8,7,7,7,7,7,7,7,4], [8,8,8,8,7,7,7,7,7,7,7,6,6]),
  ([8,8,8,8,8,7,7,7,7,7,7,7,4], [8,8,8,8,7,7,7,7,7,7,7,7,5]),
  ([8,8,8,8,8,7,7,7,7,7,7,7,4], [8,8,8,8,8,7,7,7,7,7,6,6,6]),
  ([8,8,8,8,8,7,7,7,7,7,7,7,4], [8,8,8,8,8,7,7,7,7,7,7,6,5]),
  ([8,8,8,8,8,7,7,7,7,7,7,7,4], [8,8,8,8,8,7,7,7,7,7,7,7,4]),
  ([8,8,8,8,8,7,7,7,7,7,7,7,4], [9,7,7,7,7,7,7,7,7,7,7,7,7]),
  ([8,8,8,8,8,7,7,7,7,7,7,7,4], [9,8,7,7,7,7,7,7,7,7,7,7,6]),
  ([8,8,8,8,8,7,7,7,7,7,7,7,4], [9,8,8,7,7,7,7,7,7,7,7,6,6]),
  ([8,8,8,8,8,7,7,7,7,7,7,7,4], [9,8,8,7,7,7,7,7,7,7,7,7,5]),
  ([8,8,8,8,8,7,7,7,7,7,7,7,4], [9,8,8,8,7,7,7,7,7,7,6,6,6]),
  ([8,8,8,8,8,7,7,7,7,7,7,7,4], [9,8,8,8,7,7,7,7,7,7,7,6,5]),
  ([8,8,8,8,8,7,7,7,7,7,7,7,4], [9,8,8,8,7,7,7,7,7,7,7,7,4]),
  ([8,8,8,8,8,7,7,7,7,7,7,7,4], [9,9,7,7,7,7,7,7,7,7,7,6,6]),
  ([8,8,8,8,8,7,7,7,7,7,7,7,4], [9,9,7,7,7,7,7,7,7,7,7,7,5]),
  ([8,8,8,8,8,7,7,7,7,7,7,7,4], [9,9,8,7,7,7,7,7,7,7,6,6,6]),
  ([8,8,8,8,8,7,7,7,7,7,7,7,4], [9,9,8,7,7,7,7,7,7,7,7,6,5]),
  ([8,8,8,8,8,7,7,7,7,7,7,7,4], [9,9,8,7,7,7,7,7,7,7,7,7,4]),
  ([8,8,8,8,8,7,7,7,7,7,7,7,4], [10,7,7,7,7,7,7,7,7,7,7,7,6]),
  ([8,8,8,8,8,7,7,7,7,7,7,7,4], [10,8,7,7,7,7,7,7,7,7,7,6,6]),
  ([8,8,8,8,8,7,7,7,7,7,7,7,4], [10,8,7,7,7,7,7,7,7,7,7,7,5]),
  ([8,8,8,8,8,7,7,7,7,7,7,7,4], [10,8,8,7,7,7,7,7,7,7,6,6,6]),
  ([8,8,8,8,8,7,7,7,7,7,7,7,4], [10,8,8,7,7,7,7,7,7,7,7,6,5]),
  ([8,8,8,8,8,7,7,7,7,7,7,7,4], [10,8,8,7,7,7,7,7,7,7,7,7,4]),
  ([8,8,8,8,8,7,7,7,7,7,7,7,4], [10,9,7,7,7,7,7,7,7,7,6,6,6]),
  ([8,8,8,8,8,7,7,7,7,7,7,7,4], [10,9,7,7,7,7,7,7,7,7,7,6,5]),
  ([8,8,8,8,8,7,7,7,7,7,7,7,4], [10,9,7,7,7,7,7,7,7,7,7,7,4]),
  ([8,8,8,8,8,7,7,7,7,7,7,7,4], [11,7,7,7,7,7,7,7,7,7,7,6,6]),
  ([8,8,8,8,8,7,7,7,7,7,7,7,4], [11,7,7,7,7,7,7,7,7,7,7,7,5]),
  ([8,8,8,8,8,7,7,7,7,7,7,7,4], [11,8,7,7,7,7,7,7,7,7,6,6,6]),
  ([8,8,8,8,8,7,7,7,7,7,7,7,4], [11,8,7,7,7,7,7,7,7,7,7,6,5]),
  ([9,7,7,7,7,7,7,7,7,7,7,7,7], [8,8,7,7,7,7,7,7,7,7,7,7,7]),
  ([9,7,7,7,7,7,7,7,7,7,7,7,7], [8,8,8,7,7,7,7,7,7,7,7,7,6]),
  ([9,7,7,7,7,7,7,7,7,7,7,7,7], [8,8,8,8,7,7,7,7,7,7,7,6,6]),
  ([9,7,7,7,7,7,7,7,7,7,7,7,7], [8,8,8,8,7,7,7,7,7,7,7,7,5]),
  ([9,7,7,7,7,7,7,7,7,7,7,7,7], [8,8,8,8,8,7,7,7,7,7,6,6,6]),
  ([9,7,7,7,7,7,7,7,7,7,7,7,7], [8,8,8,8,8,7,7,7,7,7,7,6,5]),
  ([9,7,7,7,7,7,7,7,7,7,7,7,7], [8,8,8,8,8,7,7,7,7,7,7,7,4]),
  ([9,7,7,7,7,7,7,7,7,7,7,7,7], [9,7,7,7,7,7,7,7,7,7,7,7,7]),
  ([9,7,7,7,7,7,7,7,7,7,7,7,7], [9,8,7,7,7,7,7,7,7,7,7,7,6]),
  ([9,7,7,7,7,7,7,7,7,7,7,7,7], [9,8,8,7,7,7,7,7,7,7,7,6,6]),
  ([9,7,7,7,7,7,7,7,7,7,7,7,7], [9,8,8,7,7,7,7,7,7,7,7,7,5]),
  ([9,7,7,7,7,7,7,7,7,7,7,7,7], [9,8,8,8,7,7,7,7,7,7,6,6,6]),
  ([9,7,7,7,7,7,7,7,7,7,7,7,7], [9,8,8,8,7,7,7,7,7,7,7,6,5]),
  ([9,7,7,7,7,7,7,7,7,7,7,7,7], [9,8,8,8,7,7,7,7,7,7,7,7,4]),
  ([9,7,7,7,7,7,7,7,7,7,7,7,7], [9,9,7,7,7,7,7,7,7,7,7,6,6]),
  ([9,7,7,7,7,7,7,7,7,7,7,7,7], [9,9,7,7,7,7,7,7,7,7,7,7,5]),
  ([9,7,7,7,7,7,7,7,7,7,7,7,7], [9,9,8,7,7,7,7,7,7,7,6,6,6]),
  ([9,7,7,7,7,7,7,7,7,7,7,7,7], [9,9,8,7,7,7,7,7,7,7,7,6,5]),
  ([9,7,7,7,7,7,7,7,7,7,7,7,7], [9,9,8,7,7,7,7,7,7,7,7,7,4]),
  ([9,7,7,7,7,7,7,7,7,7,7,7,7], [10,7,7,7,7,7,7,7,7,7,7,7,6]),
  ([9,7,7,7,7,7,7,7,7,7,7,7,7], [10,8,7,7,7,7,7,7,7,7,7,6,6]),
  ([9,7,7,7,7,7,7,7,7,7,7,7,7], [10,8,7,7,7,7,7,7,7,7,7,7,5]),
  ([9,7,7,7,7,7,7,7,7,7,7,7,7], [10,8,8,7,7,7,7,7,7,7,6,6,6]),
  ([9,7,7,7,7,7,7,7,7,7,7,7,7], [10,8,8,7,7,7,7,7,7,7,7,6,5]),
  ([9,7,7,7,7,7,7,7,7,7,7,7,7], [10,8,8,7,7,7,7,7,7,7,7,7,4]),
  ([9,7,7,7,7,7,7,7,7,7,7,7,7], [10,9,7,7,7,7,7,7,7,7,6,6,6]),
  ([9,7,7,7,7,7,7,7,7,7,7,7,7], [10,9,7,7,7,7,7,7,7,7,7,6,5]),
  ([9,7,7,7,7,7,7,7,7,7,7,7,7], [10,9,7,7,7,7,7,7,7,7,7,7,4]),
  ([9,7,7,7,7,7,7,7,7,7,7,7,7], [11,7,7,7,7,7,7,7,7,7,7,6,6]),
  ([9,7,7,7,7,7,7,7,7,7,7,7,7], [11,7,7,7,7,7,7,7,7,7,7,7,5]),
  ([9,7,7,7,7,7,7,7,7,7,7,7,7], [11,8,7,7,7,7,7,7,7,7,6,6,6]),
  ([9,7,7,7,7,7,7,7,7,7,7,7,7], [11,8,7,7,7,7,7,7,7,7,7,6,5]),
  ([9,8,7,7,7,7,7,7,7,7,7,7,6], [8,8,7,7,7,7,7,7,7,7,7,7,7]),
  ([9,8,7,7,7,7,7,7,7,7,7,7,6], [8,8,8,7,7,7,7,7,7,7,7,7,6]),
  ([9,8,7,7,7,7,7,7,7,7,7,7,6], [8,8,8,8,7,7,7,7,7,7,7,6,6]),
  ([9,8,7,7,7,7,7,7,7,7,7,7,6], [8,8,8,8,7,7,7,7,7,7,7,7,5]),
  ([9,8,7,7,7,7,7,7,7,7,7,7,6], [8,8,8,8,8,7,7,7,7,7,6,6,6]),
  ([9,8,7,7,7,7,7,7,7,7,7,7,6], [8,8,8,8,8,7,7,7,7,7,7,6,5]),
  ([9,8,7,7,7,7,7,7,7,7,7,7,6], [8,8,8,8,8,7,7,7,7,7,7,7,4]),
  ([9,8,7,7,7,7,7,7,7,7,7,7,6], [9,7,7,7,7,7,7,7,7,7,7,7,7]),
  ([9,8,7,7,7,7,7,7,7,7,7,7,6], [9,8,7,7,7,7,7,7,7,7,7,7,6]),
  ([9,8,7,7,7,7,7,7,7,7,7,7,6], [9,8,8,7,7,7,7,7,7,7,7,6,6]),
  ([9,8,7,7,7,7,7,7,7,7,7,7,6], [9,8,8,7,7,7,7,7,7,7,7,7,5]),
  ([9,8,7,7,7,7,7,7,7,7,7,7,6], [9,8,8,8,7,7,7,7,7,7,6,6,6]),
  ([9,8,7,7,7,7,7,7,7,7,7,7,6], [9,8,8,8,7,7,7,7,7,7,7,6,5]),
  ([9,8,7,7,7,7,7,7,7,7,7,7,6], [9,8,8,8,7,7,7,7,7,7,7,7,4]),
  ([9,8,7,7,7,7,7,7,7,7,7,7,6], [9,9,7,7,7,7,7,7,7,7,7,6,6]),
  ([9,8,7,7,7,7,7,7,7,7,7,7,6], [9,9,7,7,7,7,7,7,7,7,7,7,5]),
  ([9,8,7,7,7,7,7,7,7,7,7,7,6], [9,9,8,7,7,7,7,7,7,7,6,6,6]),
  ([9,8,7,7,7,7,7,7,7,7,7,7,6], [9,9,8,7,7,7,7,7,7,7,7,6,5]),
  ([9,8,7,7,7,7,7,7,7,7,7,7,6], [9,9,8,7,7,7,7,7,7,7,7,7,4]),
  ([9,8,7,7,7,7,7,7,7,7,7,7,6], [10,7,7,7,7,7,7,7,7,7,7,7,6]),
  ([9,8,7,7,7,7,7,7,7,7,7,7,6], [10,8,7,7,7,7,7,7,7,7,7,6,6]),
  ([9,8,7,7,7,7,7,7,7,7,7,7,6], [10,8,7,7,7,7,7,7,7,7,7,7,5]),
  ([9,8,7,7,7,7,7,7,7,7,7,7,6], [10,8,8,7,7,7,7,7,7,7,6,6,6]),
  ([9,8,7,7,7,7,7,7,7,7,7,7,6], [10,8,8,7,7,7,7,7,7,7,7,6,5]),
  ([9,8,7,7,7,7,7,7,7,7,7,7,6], [10,8,8,7,7,7,7,7,7,7,7,7,4]),
  ([9,8,7,7,7,7,7,7,7,7,7,7,6], [10,9,7,7,7,7,7,7,7,7,6,6,6]),
  ([9,8,7,7,7,7,7,7,7,7,7,7,6], [10,9,7,7,7,7,7,7,7,7,7,6,5]),
  ([9,8,7,7,7,7,7,7,7,7,7,7,6], [10,9,7,7,7,7,7,7,7,7,7,7,4]),
  ([9,8,7,7,7,7,7,7,7,7,7,7,6], [11,7,7,7,7,7,7,7,7,7,7,6,6]),
  ([9,8,7,7,7,7,7,7,7,7,7,7,6], [11,7,7,7,7,7,7,7,7,7,7,7,5]),
  ([9,8,7,7,7,7,7,7,7,7,7,7,6], [11,8,7,7,7,7,7,7,7,7,6,6,6]),
  ([9,8,7,7,7,7,7,7,7,7,7,7,6], [11,8,7,7,7,7,7,7,7,7,7,6,5]),
  ([9,8,8,7,7,7,7,7,7,7,7,6,6], [8,8,7,7,7,7,7,7,7,7,7,7,7]),
  ([9,8,8,7,7,7,7,7,7,7,7,6,6], [8,8,8,7,7,7,7,7,7,7,7,7,6]),
  ([9,8,8,7,7,7,7,7,7,7,7,6,6], [8,8,8,8,7,7,7,7,7,7,7,6,6]),
  ([9,8,8,7,7,7,7,7,7,7,7,6,6], [8,8,8,8,7,7,7,7,7,7,7,7,5]),
  ([9,8,8,7,7,7,7,7,7,7,7,6,6], [8,8,8,8,8,7,7,7,7,7,6,6,6]),
  ([9,8,8,7,7,7,7,7,7,7,7,6,6], [8,8,8,8,8,7,7,7,7,7,7,6,5]),
  ([9,8,8,7,7,7,7,7,7,7,7,6,6], [8,8,8,8,8,7,7,7,7,7,7,7,4]),
  ([9,8,8,7,7,7,7,7,7,7,7,6,6], [9,7,7,7,7,7,7,7,7,7,7,7,7]),
  ([9,8,8,7,7,7,7,7,7,7,7,6,6], [9,8,7,7,7,7,7,7,7,7,7,7,6]),
  ([9,8,8,7,7,7,7,7,7,7,7,6,6], [9,8,8,7,7,7,7,7,7,7,7,6,6]),
  ([9,8,8,7,7,7,7,7,7,7,7,6,6], [9,8,8,7,7,7,7,7,7,7,7,7,5]),
  ([9,8,8,7,7,7,7,7,7,7,7,6,6], [9,8,8,8,7,7,7,7,7,7,6,6,6]),
  ([9,8,8,7,7,7,7,7,7,7,7,6,6], [9,8,8,8,7,7,7,7,7,7,7,6,5]),
  ([9,8,8,7,7,7,7,7,7,7,7,6,6], [9,8,8,8,7,7,7,7,7,7,7,7,4]),
  ([9,8,8,7,7,7,7,7,7,7,7,6,6], [9,9,7,7,7,7,7,7,7,7,7,6,6]),
  ([9,8,8,7,7,7,7,7,7,7,7,6,6], [9,9,7,7,7,7,7,7,7,7,7,7,5]),
  ([9,8,8,7,7,7,7,7,7,7,7,6,6], [9,9,8,7,7,7,7,7,7,7,6,6,6]),
  ([9,8,8,7,7,7,7,7,7,7,7,6,6], [9,9,8,7,7,7,7,7,7,7,7,6,5]),
  ([9,8,8,7,7,7,7,7,7,7,7,6,6], [9,9,8,7,7,7,7,7,7,7,7,7,4]),
  ([9,8,8,7,7,7,7,7,7,7,7,6,6], [10,7,7,7,7,7,7,7,7,7,7,7,6]),
  ([9,8,8,7,7,7,7,7,7,7,7,6,6], [10,8,7,7,7,7,7,7,7,7,7,6,6]),
  ([9,8,8,7,7,7,7,7,7,7,7,6,6], [10,8,7,7,7,7,7,7,7,7,7,7,5]),
  ([9,8,8,7,7,7,7,7,7,7,7,6,6], [10,8,8,7,7,7,7,7,7,7,6,6,6]),
  ([9,8,8,7,7,7,7,7,7,7,7,6,6], [10,8,8,7,7,7,7,7,7,7,7,6,5]),
  ([9,8,8,7,7,7,7,7,7,7,7,6,6], [10,8,8,7,7,7,7,7,7,7,7,7,4]),
  ([9,8,8,7,7,7,7,7,7,7,7,6,6], [10,9,7,7,7,7,7,7,7,7,6,6,6]),
  ([9,8,8,7,7,7,7,7,7,7,7,6,6], [10,9,7,7,7,7,7,7,7,7,7,6,5]),
  ([9,8,8,7,7,7,7,7,7,7,7,6,6], [10,9,7,7,7,7,7,7,7,7,7,7,4]),
  ([9,8,8,7,7,7,7,7,7,7,7,6,6], [11,7,7,7,7,7,7,7,7,7,7,6,6]),
  ([9,8,8,7,7,7,7,7,7,7,7,6,6], [11,7,7,7,7,7,7,7,7,7,7,7,5]),
  ([9,8,8,7,7,7,7,7,7,7,7,6,6], [11,8,7,7,7,7,7,7,7,7,6,6,6]),
  ([9,8,8,7,7,7,7,7,7,7,7,6,6], [11,8,7,7,7,7,7,7,7,7,7,6,5]),
  ([9,8,8,7,7,7,7,7,7,7,7,7,5], [8,8,7,7,7,7,7,7,7,7,7,7,7]),
  ([9,8,8,7,7,7,7,7,7,7,7,7,5], [8,8,8,7,7,7,7,7,7,7,7,7,6]),
  ([9,8,8,7,7,7,7,7,7,7,7,7,5], [8,8,8,8,7,7,7,7,7,7,7,6,6]),
  ([9,8,8,7,7,7,7,7,7,7,7,7,5], [8,8,8,8,7,7,7,7,7,7,7,7,5]),
  ([9,8,8,7,7,7,7,7,7,7,7,7,5], [8,8,8,8,8,7,7,7,7,7,6,6,6]),
  ([9,8,8,7,7,7,7,7,7,7,7,7,5], [8,8,8,8,8,7,7,7,7,7,7,6,5]),
  ([9,8,8,7,7,7,7,7,7,7,7,7,5], [8,8,8,8,8,7,7,7,7,7,7,7,4]),
  ([9,8,8,7,7,7,7,7,7,7,7,7,5], [9,7,7,7,7,7,7,7,7,7,7,7,7]),
  ([9,8,8,7,7,7,7,7,7,7,7,7,5], [9,8,7,7,7,7,7,7,7,7,7,7,6]),
  ([9,8,8,7,7,7,7,7,7,7,7,7,5], [9,8,8,7,7,7,7,7,7,7,7,6,6]),
  ([9,8,8,7,7,7,7,7,7,7,7,7,5], [9,8,8,7,7,7,7,7,7,7,7,7,5]),
  ([9,8,8,7,7,7,7,7,7,7,7,7,5], [9,8,8,8,7,7,7,7,7,7,6,6,6]),
  ([9,8,8,7,7,7,7,7,7,7,7,7,5], [9,8,8,8,7,7,7,7,7,7,7,6,5]),
  ([9,8,8,7,7,7,7,7,7,7,7,7,5], [9,8,8,8,7,7,7,7,7,7,7,7,4]),
  ([9,8,8,7,7,7,7,7,7,7,7,7,5], [9,9,7,7,7,7,7,7,7,7,7,6,6]),
  ([9,8,8,7,7,7,7,7,7,7,7,7,5], [9,9,7,7,7,7,7,7,7,7,7,7,5]),
  ([9,8,8,7,7,7,7,7,7,7,7,7,5], [9,9,8,7,7,7,7,7,7,7,6,6,6]),
  ([9,8,8,7,7,7,7,7,7,7,7,7,5], [9,9,8,7,7,7,7,7,7,7,7,6,5]),
  ([9,8,8,7,7,7,7,7,7,7,7,7,5], [9,9,8,7,7,7,7,7,7,7,7,7,4]),
  ([9,8,8,7,7,7,7,7,7,7,7,7,5], [10,7,7,7,7,7,7,7,7,7,7,7,6]),
  ([9,8,8,7,7,7,7,7,7,7,7,7,5], [10,8,7,7,7,7,7,7,7,7,7,6,6]),
  ([9,8,8,7,7,7,7,7,7,7,7,7,5], [10,8,7,7,7,7,7,7,7,7,7,7,5]),
  ([9,8,8,7,7,7,7,7,7,7,7,7,5], [10,8,8,7,7,7,7,7,7,7,6,6,6]),
  ([9,8,8,7,7,7,7,7,7,7,7,7,5], [10,8,8,7,7,7,7,7,7,7,7,6,5]),
  ([9,8,8,7,7,7,7,7,7,7,7,7,5], [10,8,8,7,7,7,7,7,7,7,7,7,4]),
  ([9,8,8,7,7,7,7,7,7,7,7,7,5], [10,9,7,7,7,7,7,7,7,7,6,6,6]),
  ([9,8,8,7,7,7,7,7,7,7,7,7,5], [10,9,7,7,7,7,7,7,7,7,7,6,5]),
  ([9,8,8,7,7,7,7,7,7,7,7,7,5], [10,9,7,7,7,7,7,7,7,7,7,7,4]),
  ([9,8,8,7,7,7,7,7,7,7,7,7,5], [11,7,7,7,7,7,7,7,7,7,7,6,6]),
  ([9,8,8,7,7,7,7,7,7,7,7,7,5], [11,7,7,7,7,7,7,7,7,7,7,7,5]),
  ([9,8,8,7,7,7,7,7,7,7,7,7,5], [11,8,7,7,7,7,7,7,7,7,6,6,6]),
  ([9,8,8,7,7,7,7,7,7,7,7,7,5], [11,8,7,7,7,7,7,7,7,7,7,6,5]),
  ([9,8,8,8,7,7,7,7,7,7,6,6,6], [8,8,7,7,7,7,7,7,7,7,7,7,7]),
  ([9,8,8,8,7,7,7,7,7,7,6,6,6], [8,8,8,7,7,7,7,7,7,7,7,7,6]),
  ([9,8,8,8,7,7,7,7,7,7,6,6,6], [8,8,8,8,7,7,7,7,7,7,7,6,6]),
  ([9,8,8,8,7,7,7,7,7,7,6,6,6], [8,8,8,8,7,7,7,7,7,7,7,7,5]),
  ([9,8,8,8,7,7,7,7,7,7,6,6,6], [8,8,8,8,8,7,7,7,7,7,6,6,6]),
  ([9,8,8,8,7,7,7,7,7,7,6,6,6], [8,8,8,8,8,7,7,7,7,7,7,6,5]),
  ([9,8,8,8,7,7,7,7,7,7,6,6,6], [8,8,8,8,8,7,7,7,7,7,7,7,4]),
  ([9,8,8,8,7,7,7,7,7,7,6,6,6], [9,7,7,7,7,7,7,7,7,7,7,7,7]),
  ([9,8,8,8,7,7,7,7,7,7,6,6,6], [9,8,7,7,7,7,7,7,7,7,7,7,6]),
  ([9,8,8,8,7,7,7,7,7,7,6,6,6], [9,8,8,7,7,7,7,7,7,7,7,6,6]),
  ([9,8,8,8,7,7,7,7,7,7,6,6,6], [9,8,8,7,7,7,7,7,7,7,7,7,5]),
  ([9,8,8,8,7,7,7,7,7,7,6,6,6], [9,8,8,8,7,7,7,7,7,7,6,6,6]),
  ([9,8,8,8,7,7,7,7,7,7,6,6,6], [9,8,8,8,7,7,7,7,7,7,7,6,5]),
  ([9,8,8,8,7,7,7,7,7,7,6,6,6], [9,8,8,8,7,7,7,7,7,7,7,7,4]),
  ([9,8,8,8,7,7,7,7,7,7,6,6,6], [9,9,7,7,7,7,7,7,7,7,7,6,6]),
  ([9,8,8,8,7,7,7,7,7,7,6,6,6], [9,9,7,7,7,7,7,7,7,7,7,7,5]),
  ([9,8,8,8,7,7,7,7,7,7,6,6,6], [9,9,8,7,7,7,7,7,7,7,6,6,6]),
  ([9,8,8,8,7,7,7,7,7,7,6,6,6], [9,9,8,7,7,7,7,7,7,7,7,6,5]),
  ([9,8,8,8,7,7,7,7,7,7,6,6,6], [9,9,8,7,7,7,7,7,7,7,7,7,4]),
  ([9,8,8,8,7,7,7,7,7,7,6,6,6], [10,7,7,7,7,7,7,7,7,7,7,7,6]),
  ([9,8,8,8,7,7,7,7,7,7,6,6,6], [10,8,7,7,7,7,7,7,7,7,7,6,6]),
  ([9,8,8,8,7,7,7,7,7,7,6,6,6], [10,8,7,7,7,7,7,7,7,7,7,7,5]),
  ([9,8,8,8,7,7,7,7,7,7,6,6,6], [10,8,8,7,7,7,7,7,7,7,6,6,6]),
  ([9,8,8,8,7,7,7,7,7,7,6,6,6], [10,8,8,7,7,7,7,7,7,7,7,6,5]),
  ([9,8,8,8,7,7,7,7,7,7,6,6,6], [10,8,8,7,7,7,7,7,7,7,7,7,4]),
  ([9,8,8,8,7,7,7,7,7,7,6,6,6], [10,9,7,7,7,7,7,7,7,7,6,6,6]),
  ([9,8,8,8,7,7,7,7,7,7,6,6,6], [10,9,7,7,7,7,7,7,7,7,7,6,5]),
  ([9,8,8,8,7,7,7,7,7,7,6,6,6], [10,9,7,7,7,7,7,7,7,7,7,7,4]),
  ([9,8,8,8,7,7,7,7,7,7,6,6,6], [11,7,7,7,7,7,7,7,7,7,7,6,6]),
  ([9,8,8,8,7,7,7,7,7,7,6,6,6], [11,7,7,7,7,7,7,7,7,7,7,7,5]),
  ([9,8,8,8,7,7,7,7,7,7,6,6,6], [11,8,7,7,7,7,7,7,7,7,6,6,6]),
  ([9,8,8,8,7,7,7,7,7,7,6,6,6], [11,8,7,7,7,7,7,7,7,7,7,6,5]),
  ([9,8,8,8,7,7,7,7,7,7,7,6,5], [8,8,7,7,7,7,7,7,7,7,7,7,7]),
  ([9,8,8,8,7,7,7,7,7,7,7,6,5], [8,8,8,7,7,7,7,7,7,7,7,7,6]),
  ([9,8,8,8,7,7,7,7,7,7,7,6,5], [8,8,8,8,7,7,7,7,7,7,7,6,6]),
  ([9,8,8,8,7,7,7,7,7,7,7,6,5], [8,8,8,8,7,7,7,7,7,7,7,7,5]),
  ([9,8,8,8,7,7,7,7,7,7,7,6,5], [8,8,8,8,8,7,7,7,7,7,6,6,6]),
  ([9,8,8,8,7,7,7,7,7,7,7,6,5], [8,8,8,8,8,7,7,7,7,7,7,6,5]),
  ([9,8,8,8,7,7,7,7,7,7,7,6,5], [8,8,8,8,8,7,7,7,7,7,7,7,4]),
  ([9,8,8,8,7,7,7,7,7,7,7,6,5], [9,7,7,7,7,7,7,7,7,7,7,7,7]),
  ([9,8,8,8,7,7,7,7,7,7,7,6,5], [9,8,7,7,7,7,7,7,7,7,7,7,6]),
  ([9,8,8,8,7,7,7,7,7,7,7,6,5], [9,8,8,7,7,7,7,7,7,7,7,6,6]),
  ([9,8,8,8,7,7,7,7,7,7,7,6,5], [9,8,8,7,7,7,7,7,7,7,7,7,5]),
  ([9,8,8,8,7,7,7,7,7,7,7,6,5], [9,8,8,8,7,7,7,7,7,7,6,6,6]),
  ([9,8,8,8,7,7,7,7,7,7,7,6,5], [9,8,8,8,7,7,7,7,7,7,7,6,5]),
  ([9,8,8,8,7,7,7,7,7,7,7,6,5], [9,8,8,8,7,7,7,7,7,7,7,7,4]),
  ([9,8,8,8,7,7,7,7,7,7,7,6,5], [9,9,7,7,7,7,7,7,7,7,7,6,6]),
  ([9,8,8,8,7,7,7,7,7,7,7,6,5], [9,9,7,7,7,7,7,7,7,7,7,7,5]),
  ([9,8,8,8,7,7,7,7,7,7,7,6,5], [9,9,8,7,7,7,7,7,7,7,6,6,6]),
  ([9,8,8,8,7,7,7,7,7,7,7,6,5], [9,9,8,7,7,7,7,7,7,7,7,6,5]),
  ([9,8,8,8,7,7,7,7,7,7,7,6,5], [9,9,8,7,7,7,7,7,7,7,7,7,4]),
  ([9,8,8,8,7,7,7,7,7,7,7,6,5], [10,7,7,7,7,7,7,7,7,7,7,7,6]),
  ([9,8,8,8,7,7,7,7,7,7,7,6,5], [10,8,7,7,7,7,7,7,7,7,7,6,6]),
  ([9,8,8,8,7,7,7,7,7,7,7,6,5], [10,8,7,7,7,7,7,7,7,7,7,7,5]),
  ([9,8,8,8,7,7,7,7,7,7,7,6,5], [10,8,8,7,7,7,7,7,7,7,6,6,6]),
  ([9,8,8,8,7,7,7,7,7,7,7,6,5], [10,8,8,7,7,7,7,7,7,7,7,6,5]),
  ([9,8,8,8,7,7,7,7,7,7,7,6,5], [10,8,8,7,7,7,7,7,7,7,7,7,4]),
  ([9,8,8,8,7,7,7,7,7,7,7,6,5], [10,9,7,7,7,7,7,7,7,7,6,6,6]),
  ([9,8,8,8,7,7,7,7,7,7,7,6,5], [10,9,7,7,7,7,7,7,7,7,7,6,5]),
  ([9,8,8,8,7,7,7,7,7,7,7,6,5], [10,9,7,7,7,7,7,7,7,7,7,7,4]),
  ([9,8,8,8,7,7,7,7,7,7,7,6,5], [11,7,7,7,7,7,7,7,7,7,7,6,6]),
  ([9,8,8,8,7,7,7,7,7,7,7,6,5], [11,7,7,7,7,7,7,7,7,7,7,7,5]),
  ([9,8,8,8,7,7,7,7,7,7,7,6,5], [11,8,7,7,7,7,7,7,7,7,6,6,6]),
  ([9,8,8,8,7,7,7,7,7,7,7,6,5], [11,8,7,7,7,7,7,7,7,7,7,6,5]),
  ([9,8,8,8,7,7,7,7,7,7,7,7,4], [8,8,7,7,7,7,7,7,7,7,7,7,7]),
  ([9,8,8,8,7,7,7,7,7,7,7,7,4], [8,8,8,7,7,7,7,7,7,7,7,7,6]),
  ([9,8,8,8,7,7,7,7,7,7,7,7,4], [8,8,8,8,7,7,7,7,7,7,7,6,6]),
  ([9,8,8,8,7,7,7,7,7,7,7,7,4], [8,8,8,8,7,7,7,7,7,7,7,7,5]),
  ([9,8,8,8,7,7,7,7,7,7,7,7,4], [8,8,8,8,8,7,7,7,7,7,6,6,6]),
  ([9,8,8,8,7,7,7,7,7,7,7,7,4], [8,8,8,8,8,7,7,7,7,7,7,6,5]),
  ([9,8,8,8,7,7,7,7,7,7,7,7,4], [8,8,8,8,8,7,7,7,7,7,7,7,4]),
  ([9,8,8,8,7,7,7,7,7,7,7,7,4], [9,7,7,7,7,7,7,7,7,7,7,7,7]),
  ([9,8,8,8,7,7,7,7,7,7,7,7,4], [9,8,7,7,7,7,7,7,7,7,7,7,6]),
  ([9,8,8,8,7,7,7,7,7,7,7,7,4], [9,8,8,7,7,7,7,7,7,7,7,6,6]),
  ([9,8,8,8,7,7,7,7,7,7,7,7,4], [9,8,8,7,7,7,7,7,7,7,7,7,5]),
  ([9,8,8,8,7,7,7,7,7,7,7,7,4], [9,8,8,8,7,7,7,7,7,7,6,6,6]),
  ([9,8,8,8,7,7,7,7,7,7,7,7,4], [9,8,8,8,7,7,7,7,7,7,7,6,5]),
  ([9,8,8,8,7,7,7,7,7,7,7,7,4], [9,8,8,8,7,7,7,7,7,7,7,7,4]),
  ([9,8,8,8,7,7,7,7,7,7,7,7,4], [9,9,7,7,7,7,7,7,7,7,7,6,6]),
  ([9,8,8,8,7,7,7,7,7,7,7,7,4], [9,9,7,7,7,7,7,7,7,7,7,7,5]),
  ([9,8,8,8,7,7,7,7,7,7,7,7,4], [9,9,8,7,7,7,7,7,7,7,6,6,6]),
  ([9,8,8,8,7,7,7,7,7,7,7,7,4], [9,9,8,7,7,7,7,7,7,7,7,6,5]),
  ([9,8,8,8,7,7,7,7,7,7,7,7,4], [9,9,8,7,7,7,7,7,7,7,7,7,4]),
  ([9,8,8,8,7,7,7,7,7,7,7,7,4], [10,7,7,7,7,7,7,7,7,7,7,7,6]),
  ([9,8,8,8,7,7,7,7,7,7,7,7,4], [10,8,7,7,7,7,7,7,7,7,7,6,6]),
  ([9,8,8,8,7,7,7,7,7,7,7,7,4], [10,8,7,7,7,7,7,7,7,7,7,7,5]),
  ([9,8,8,8,7,7,7,7,7,7,7,7,4], [10,8,8,7,7,7,7,7,7,7,6,6,6]),
  ([9,8,8,8,7,7,7,7,7,7,7,7,4], [10,8,8,7,7,7,7,7,7,7,7,6,5]),
  ([9,8,8,8,7,7,7,7,7,7,7,7,4], [10,8,8,7,7,7,7,7,7,7,7,7,4]),
  ([9,8,8,8,7,7,7,7,7,7,7,7,4], [10,9,7,7,7,7,7,7,7,7,6,6,6]),
  ([9,8,8,8,7,7,7,7,7,7,7,7,4], [10,9,7,7,7,7,7,7,7,7,7,6,5]),
  ([9,8,8,8,7,7,7,7,7,7,7,7,4], [10,9,7,7,7,7,7,7,7,7,7,7,4]),
  ([9,8,8,8,7,7,7,7,7,7,7,7,4], [11,7,7,7,7,7,7,7,7,7,7,6,6]),
  ([9,8,8,8,7,7,7,7,7,7,7,7,4], [11,7,7,7,7,7,7,7,7,7,7,7,5]),
  ([9,8,8,8,7,7,7,7,7,7,7,7,4], [11,8,7,7,7,7,7,7,7,7,6,6,6]),
  ([9,8,8,8,7,7,7,7,7,7,7,7,4], [11,8,7,7,7,7,7,7,7,7,7,6,5]),
  ([9,9,7,7,7,7,7,7,7,7,7,6,6], [8,8,7,7,7,7,7,7,7,7,7,7,7]),
  ([9,9,7,7,7,7,7,7,7,7,7,6,6], [8,8,8,7,7,7,7,7,7,7,7,7,6]),
  ([9,9,7,7,7,7,7,7,7,7,7,6,6], [8,8,8,8,7,7,7,7,7,7,7,6,6]),
  ([9,9,7,7,7,7,7,7,7,7,7,6,6], [8,8,8,8,7,7,7,7,7,7,7,7,5]),
  ([9,9,7,7,7,7,7,7,7,7,7,6,6], [8,8,8,8,8,7,7,7,7,7,6,6,6]),
  ([9,9,7,7,7,7,7,7,7,7,7,6,6], [8,8,8,8,8,7,7,7,7,7,7,6,5]),
  ([9,9,7,7,7,7,7,7,7,7,7,6,6], [8,8,8,8,8,7,7,7,7,7,7,7,4]),
  ([9,9,7,7,7,7,7,7,7,7,7,6,6], [9,7,7,7,7,7,7,7,7,7,7,7,7]),
  ([9,9,7,7,7,7,7,7,7,7,7,6,6], [9,8,7,7,7,7,7,7,7,7,7,7,6]),
  ([9,9,7,7,7,7,7,7,7,7,7,6,6], [9,8,8,7,7,7,7,7,7,7,7,6,6]),
  ([9,9,7,7,7,7,7,7,7,7,7,6,6], [9,8,8,7,7,7,7,7,7,7,7,7,5]),
  ([9,9,7,7,7,7,7,7,7,7,7,6,6], [9,8,8,8,7,7,7,7,7,7,6,6,6]),
  ([9,9,7,7,7,7,7,7,7,7,7,6,6], [9,8,8,8,7,7,7,7,7,7,7,6,5]),
  ([9,9,7,7,7,7,7,7,7,7,7,6,6], [9,8,8,8,7,7,7,7,7,7,7,7,4]),
  ([9,9,7,7,7,7,7,7,7,7,7,6,6], [9,9,7,7,7,7,7,7,7,7,7,6,6]),
  ([9,9,7,7,7,7,7,7,7,7,7,6,6], [9,9,7,7,7,7,7,7,7,7,7,7,5]),
  ([9,9,7,7,7,7,7,7,7,7,7,6,6], [9,9,8,7,7,7,7,7,7,7,6,6,6]),
  ([9,9,7,7,7,7,7,7,7,7,7,6,6], [9,9,8,7,7,7,7,7,7,7,7,6,5]),
  ([9,9,7,7,7,7,7,7,7,7,7,6,6], [9,9,8,7,7,7,7,7,7,7,7,7,4]),
  ([9,9,7,7,7,7,7,7,7,7,7,6,6], [10,7,7,7,7,7,7,7,7,7,7,7,6]),
  ([9,9,7,7,7,7,7,7,7,7,7,6,6], [10,8,7,7,7,7,7,7,7,7,7,6,6]),
  ([9,9,7,7,7,7,7,7,7,7,7,6,6], [10,8,7,7,7,7,7,7,7,7,7,7,5]),
  ([9,9,7,7,7,7,7,7,7,7,7,6,6], [10,8,8,7,7,7,7,7,7,7,6,6,6]),
  ([9,9,7,7,7,7,7,7,7,7,7,6,6], [10,8,8,7,7,7,7,7,7,7,7,6,5]),
  ([9,9,7,7,7,7,7,7,7,7,7,6,6], [10,8,8,7,7,7,7,7,7,7,7,7,4]),
  ([9,9,7,7,7,7,7,7,7,7,7,6,6], [10,9,7,7,7,7,7,7,7,7,6,6,6]),
  ([9,9,7,7,7,7,7,7,7,7,7,6,6], [10,9,7,7,7,7,7,7,7,7,7,6,5]),
  ([9,9,7,7,7,7,7,7,7,7,7,6,6], [10,9,7,7,7,7,7,7,7,7,7,7,4]),
  ([9,9,7,7,7,7,7,7,7,7,7,6,6], [11,7,7,7,7,7,7,7,7,7,7,6,6]),
  ([9,9,7,7,7,7,7,7,7,7,7,6,6], [11,7,7,7,7,7,7,7,7,7,7,7,5]),
  ([9,9,7,7,7,7,7,7,7,7,7,6,6], [11,8,7,7,7,7,7,7,7,7,6,6,6]),
  ([9,9,7,7,7,7,7,7,7,7,7,6,6], [11,8,7,7,7,7,7,7,7,7,7,6,5]),
  ([9,9,7,7,7,7,7,7,7,7,7,7,5], [8,8,7,7,7,7,7,7,7,7,7,7,7]),
  ([9,9,7,7,7,7,7,7,7,7,7,7,5], [8,8,8,7,7,7,7,7,7,7,7,7,6]),
  ([9,9,7,7,7,7,7,7,7,7,7,7,5], [8,8,8,8,7,7,7,7,7,7,7,6,6]),
  ([9,9,7,7,7,7,7,7,7,7,7,7,5], [8,8,8,8,7,7,7,7,7,7,7,7,5]),
  ([9,9,7,7,7,7,7,7,7,7,7,7,5], [8,8,8,8,8,7,7,7,7,7,6,6,6]),
  ([9,9,7,7,7,7,7,7,7,7,7,7,5], [8,8,8,8,8,7,7,7,7,7,7,6,5]),
  ([9,9,7,7,7,7,7,7,7,7,7,7,5], [8,8,8,8,8,7,7,7,7,7,7,7,4]),
  ([9,9,7,7,7,7,7,7,7,7,7,7,5], [9,7,7,7,7,7,7,7,7,7,7,7,7]),
  ([9,9,7,7,7,7,7,7,7,7,7,7,5], [9,8,7,7,7,7,7,7,7,7,7,7,6]),
  ([9,9,7,7,7,7,7,7,7,7,7,7,5], [9,8,8,7,7,7,7,7,7,7,7,6,6]),
  ([9,9,7,7,7,7,7,7,7,7,7,7,5], [9,8,8,7,7,7,7,7,7,7,7,7,5]),
  ([9,9,7,7,7,7,7,7,7,7,7,7,5], [9,8,8,8,7,7,7,7,7,7,6,6,6]),
  ([9,9,7,7,7,7,7,7,7,7,7,7,5], [9,8,8,8,7,7,7,7,7,7,7,6,5]),
  ([9,9,7,7,7,7,7,7,7,7,7,7,5], [9,8,8,8,7,7,7,7,7,7,7,7,4]),
  ([9,9,7,7,7,7,7,7,7,7,7,7,5], [9,9,7,7,7,7,7,7,7,7,7,6,6]),
  ([9,9,7,7,7,7,7,7,7,7,7,7,5], [9,9,7,7,7,7,7,7,7,7,7,7,5]),
  ([9,9,7,7,7,7,7,7,7,7,7,7,5], [9,9,8,7,7,7,7,7,7,7,6,6,6]),
  ([9,9,7,7,7,7,7,7,7,7,7,7,5], [9,9,8,7,7,7,7,7,7,7,7,6,5]),
  ([9,9,7,7,7,7,7,7,7,7,7,7,5], [9,9,8,7,7,7,7,7,7,7,7,7,4]),
  ([9,9,7,7,7,7,7,7,7,7,7,7,5], [10,7,7,7,7,7,7,7,7,7,7,7,6]),
  ([9,9,7,7,7,7,7,7,7,7,7,7,5], [10,8,7,7,7,7,7,7,7,7,7,6,6]),
  ([9,9,7,7,7,7,7,7,7,7,7,7,5], [10,8,7,7,7,7,7,7,7,7,7,7,5]),
  ([9,9,7,7,7,7,7,7,7,7,7,7,5], [10,8,8,7,7,7,7,7,7,7,6,6,6]),
  ([9,9,7,7,7,7,7,7,7,7,7,7,5], [10,8,8,7,7,7,7,7,7,7,7,6,5]),
  ([9,9,7,7,7,7,7,7,7,7,7,7,5], [10,8,8,7,7,7,7,7,7,7,7,7,4]),
  ([9,9,7,7,7,7,7,7,7,7,7,7,5], [10,9,7,7,7,7,7,7,7,7,6,6,6]),
  ([9,9,7,7,7,7,7,7,7,7,7,7,5], [10,9,7,7,7,7,7,7,7,7,7,6,5]),
  ([9,9,7,7,7,7,7,7,7,7,7,7,5], [10,9,7,7,7,7,7,7,7,7,7,7,4]),
  ([9,9,7,7,7,7,7,7,7,7,7,7,5], [11,7,7,7,7,7,7,7,7,7,7,6,6]),
  ([9,9,7,7,7,7,7,7,7,7,7,7,5], [11,7,7,7,7,7,7,7,7,7,7,7,5]),
  ([9,9,7,7,7,7,7,7,7,7,7,7,5], [11,8,7,7,7,7,7,7,7,7,6,6,6]),
  ([9,9,7,7,7,7,7,7,7,7,7,7,5], [11,8,7,7,7,7,7,7,7,7,7,6,5]),
  ([9,9,8,7,7,7,7,7,7,7,6,6,6], [8,8,7,7,7,7,7,7,7,7,7,7,7]),
  ([9,9,8,7,7,7,7,7,7,7,6,6,6], [8,8,8,7,7,7,7,7,7,7,7,7,6]),
  ([9,9,8,7,7,7,7,7,7,7,6,6,6], [8,8,8,8,7,7,7,7,7,7,7,6,6]),
  ([9,9,8,7,7,7,7,7,7,7,6,6,6], [8,8,8,8,7,7,7,7,7,7,7,7,5]),
  ([9,9,8,7,7,7,7,7,7,7,6,6,6], [8,8,8,8,8,7,7,7,7,7,6,6,6]),
  ([9,9,8,7,7,7,7,7,7,7,6,6,6], [8,8,8,8,8,7,7,7,7,7,7,6,5]),
  ([9,9,8,7,7,7,7,7,7,7,6,6,6], [8,8,8,8,8,7,7,7,7,7,7,7,4]),
  ([9,9,8,7,7,7,7,7,7,7,6,6,6], [9,7,7,7,7,7,7,7,7,7,7,7,7]),
  ([9,9,8,7,7,7,7,7,7,7,6,6,6], [9,8,7,7,7,7,7,7,7,7,7,7,6]),
  ([9,9,8,7,7,7,7,7,7,7,6,6,6], [9,8,8,7,7,7,7,7,7,7,7,6,6]),
  ([9,9,8,7,7,7,7,7,7,7,6,6,6], [9,8,8,7,7,7,7,7,7,7,7,7,5]),
  ([9,9,8,7,7,7,7,7,7,7,6,6,6], [9,8,8,8,7,7,7,7,7,7,6,6,6]),
  ([9,9,8,7,7,7,7,7,7,7,6,6,6], [9,8,8,8,7,7,7,7,7,7,7,6,5]),
  ([9,9,8,7,7,7,7,7,7,7,6,6,6], [9,8,8,8,7,7,7,7,7,7,7,7,4]),
  ([9,9,8,7,7,7,7,7,7,7,6,6,6], [9,9,7,7,7,7,7,7,7,7,7,6,6]),
  ([9,9,8,7,7,7,7,7,7,7,6,6,6], [9,9,7,7,7,7,7,7,7,7,7,7,5]),
  ([9,9,8,7,7,7,7,7,7,7,6,6,6], [9,9,8,7,7,7,7,7,7,7,6,6,6]),
  ([9,9,8,7,7,7,7,7,7,7,6,6,6], [9,9,8,7,7,7,7,7,7,7,7,6,5]),
  ([9,9,8,7,7,7,7,7,7,7,6,6,6], [9,9,8,7,7,7,7,7,7,7,7,7,4]),
  ([9,9,8,7,7,7,7,7,7,7,6,6,6], [10,7,7,7,7,7,7,7,7,7,7,7,6]),
  ([9,9,8,7,7,7,7,7,7,7,6,6,6], [10,8,7,7,7,7,7,7,7,7,7,6,6]),
  ([9,9,8,7,7,7,7,7,7,7,6,6,6], [10,8,7,7,7,7,7,7,7,7,7,7,5]),
  ([9,9,8,7,7,7,7,7,7,7,6,6,6], [10,8,8,7,7,7,7,7,7,7,6,6,6]),
  ([9,9,8,7,7,7,7,7,7,7,6,6,6], [10,8,8,7,7,7,7,7,7,7,7,6,5]),
  ([9,9,8,7,7,7,7,7,7,7,6,6,6], [10,8,8,7,7,7,7,7,7,7,7,7,4]),
  ([9,9,8,7,7,7,7,7,7,7,6,6,6], [10,9,7,7,7,7,7,7,7,7,6,6,6]),
  ([9,9,8,7,7,7,7,7,7,7,6,6,6], [10,9,7,7,7,7,7,7,7,7,7,6,5]),
  ([9,9,8,7,7,7,7,7,7,7,6,6,6], [10,9,7,7,7,7,7,7,7,7,7,7,4]),
  ([9,9,8,7,7,7,7,7,7,7,6,6,6], [11,7,7,7,7,7,7,7,7,7,7,6,6]),
  ([9,9,8,7,7,7,7,7,7,7,6,6,6], [11,7,7,7,7,7,7,7,7,7,7,7,5]),
  ([9,9,8,7,7,7,7,7,7,7,6,6,6], [11,8,7,7,7,7,7,7,7,7,6,6,6]),
  ([9,9,8,7,7,7,7,7,7,7,6,6,6], [11,8,7,7,7,7,7,7,7,7,7,6,5]),
  ([9,9,8,7,7,7,7,7,7,7,7,6,5], [8,8,7,7,7,7,7,7,7,7,7,7,7]),
  ([9,9,8,7,7,7,7,7,7,7,7,6,5], [8,8,8,7,7,7,7,7,7,7,7,7,6]),
  ([9,9,8,7,7,7,7,7,7,7,7,6,5], [8,8,8,8,7,7,7,7,7,7,7,6,6]),
  ([9,9,8,7,7,7,7,7,7,7,7,6,5], [8,8,8,8,7,7,7,7,7,7,7,7,5]),
  ([9,9,8,7,7,7,7,7,7,7,7,6,5], [8,8,8,8,8,7,7,7,7,7,6,6,6]),
  ([9,9,8,7,7,7,7,7,7,7,7,6,5], [8,8,8,8,8,7,7,7,7,7,7,6,5]),
  ([9,9,8,7,7,7,7,7,7,7,7,6,5], [8,8,8,8,8,7,7,7,7,7,7,7,4]),
  ([9,9,8,7,7,7,7,7,7,7,7,6,5], [9,7,7,7,7,7,7,7,7,7,7,7,7]),
  ([9,9,8,7,7,7,7,7,7,7,7,6,5], [9,8,7,7,7,7,7,7,7,7,7,7,6]),
  ([9,9,8,7,7,7,7,7,7,7,7,6,5], [9,8,8,7,7,7,7,7,7,7,7,6,6]),
  ([9,9,8,7,7,7,7,7,7,7,7,6,5], [9,8,8,7,7,7,7,7,7,7,7,7,5]),
  ([9,9,8,7,7,7,7,7,7,7,7,6,5], [9,8,8,8,7,7,7,7,7,7,6,6,6]),
  ([9,9,8,7,7,7,7,7,7,7,7,6,5], [9,8,8,8,7,7,7,7,7,7,7,6,5]),
  ([9,9,8,7,7,7,7,7,7,7,7,6,5], [9,8,8,8,7,7,7,7,7,7,7,7,4]),
  ([9,9,8,7,7,7,7,7,7,7,7,6,5], [9,9,7,7,7,7,7,7,7,7,7,6,6]),
  ([9,9,8,7,7,7,7,7,7,7,7,6,5], [9,9,7,7,7,7,7,7,7,7,7,7,5]),
  ([9,9,8,7,7,7,7,7,7,7,7,6,5], [9,9,8,7,7,7,7,7,7,7,6,6,6]),
  ([9,9,8,7,7,7,7,7,7,7,7,6,5], [9,9,8,7,7,7,7,7,7,7,7,6,5]),
  ([9,9,8,7,7,7,7,7,7,7,7,6,5], [9,9,8,7,7,7,7,7,7,7,7,7,4]),
  ([9,9,8,7,7,7,7,7,7,7,7,6,5], [10,7,7,7,7,7,7,7,7,7,7,7,6]),
  ([9,9,8,7,7,7,7,7,7,7,7,6,5], [10,8,7,7,7,7,7,7,7,7,7,6,6]),
  ([9,9,8,7,7,7,7,7,7,7,7,6,5], [10,8,7,7,7,7,7,7,7,7,7,7,5]),
  ([9,9,8,7,7,7,7,7,7,7,7,6,5], [10,8,8,7,7,7,7,7,7,7,6,6,6]),
  ([9,9,8,7,7,7,7,7,7,7,7,6,5], [10,8,8,7,7,7,7,7,7,7,7,6,5]),
  ([9,9,8,7,7,7,7,7,7,7,7,6,5], [10,8,8,7,7,7,7,7,7,7,7,7,4]),
  ([9,9,8,7,7,7,7,7,7,7,7,6,5], [10,9,7,7,7,7,7,7,7,7,6,6,6]),
  ([9,9,8,7,7,7,7,7,7,7,7,6,5], [10,9,7,7,7,7,7,7,7,7,7,6,5]),
  ([9,9,8,7,7,7,7,7,7,7,7,6,5], [10,9,7,7,7,7,7,7,7,7,7,7,4]),
  ([9,9,8,7,7,7,7,7,7,7,7,6,5], [11,7,7,7,7,7,7,7,7,7,7,6,6]),
  ([9,9,8,7,7,7,7,7,7,7,7,6,5], [11,7,7,7,7,7,7,7,7,7,7,7,5]),
  ([9,9,8,7,7,7,7,7,7,7,7,6,5], [11,8,7,7,7,7,7,7,7,7,6,6,6]),
  ([9,9,8,7,7,7,7,7,7,7,7,6,5], [11,8,7,7,7,7,7,7,7,7,7,6,5]),
  ([9,9,8,7,7,7,7,7,7,7,7,7,4], [8,8,7,7,7,7,7,7,7,7,7,7,7]),
  ([9,9,8,7,7,7,7,7,7,7,7,7,4], [8,8,8,7,7,7,7,7,7,7,7,7,6]),
  ([9,9,8,7,7,7,7,7,7,7,7,7,4], [8,8,8,8,7,7,7,7,7,7,7,6,6]),
  ([9,9,8,7,7,7,7,7,7,7,7,7,4], [8,8,8,8,7,7,7,7,7,7,7,7,5]),
  ([9,9,8,7,7,7,7,7,7,7,7,7,4], [8,8,8,8,8,7,7,7,7,7,6,6,6]),
  ([9,9,8,7,7,7,7,7,7,7,7,7,4], [8,8,8,8,8,7,7,7,7,7,7,6,5]),
  ([9,9,8,7,7,7,7,7,7,7,7,7,4], [8,8,8,8,8,7,7,7,7,7,7,7,4]),
  ([9,9,8,7,7,7,7,7,7,7,7,7,4], [9,7,7,7,7,7,7,7,7,7,7,7,7]),
  ([9,9,8,7,7,7,7,7,7,7,7,7,4], [9,8,7,7,7,7,7,7,7,7,7,7,6]),
  ([9,9,8,7,7,7,7,7,7,7,7,7,4], [9,8,8,7,7,7,7,7,7,7,7,6,6]),
  ([9,9,8,7,7,7,7,7,7,7,7,7,4], [9,8,8,7,7,7,7,7,7,7,7,7,5]),
  ([9,9,8,7,7,7,7,7,7,7,7,7,4], [9,8,8,8,7,7,7,7,7,7,6,6,6]),
  ([9,9,8,7,7,7,7,7,7,7,7,7,4], [9,8,8,8,7,7,7,7,7,7,7,6,5]),
  ([9,9,8,7,7,7,7,7,7,7,7,7,4], [9,8,8,8,7,7,7,7,7,7,7,7,4]),
  ([9,9,8,7,7,7,7,7,7,7,7,7,4], [9,9,7,7,7,7,7,7,7,7,7,6,6]),
  ([9,9,8,7,7,7,7,7,7,7,7,7,4], [9,9,7,7,7,7,7,7,7,7,7,7,5]),
  ([9,9,8,7,7,7,7,7,7,7,7,7,4], [9,9,8,7,7,7,7,7,7,7,6,6,6]),
  ([9,9,8,7,7,7,7,7,7,7,7,7,4], [9,9,8,7,7,7,7,7,7,7,7,6,5]),
  ([9,9,8,7,7,7,7,7,7,7,7,7,4], [9,9,8,7,7,7,7,7,7,7,7,7,4]),
  ([9,9,8,7,7,7,7,7,7,7,7,7,4], [10,7,7,7,7,7,7,7,7,7,7,7,6]),
  ([9,9,8,7,7,7,7,7,7,7,7,7,4], [10,8,7,7,7,7,7,7,7,7,7,6,6]),
  ([9,9,8,7,7,7,7,7,7,7,7,7,4], [10,8,7,7,7,7,7,7,7,7,7,7,5]),
  ([9,9,8,7,7,7,7,7,7,7,7,7,4], [10,8,8,7,7,7,7,7,7,7,6,6,6]),
  ([9,9,8,7,7,7,7,7,7,7,7,7,4], [10,8,8,7,7,7,7,7,7,7,7,6,5]),
  ([9,9,8,7,7,7,7,7,7,7,7,7,4], [10,8,8,7,7,7,7,7,7,7,7,7,4]),
  ([9,9,8,7,7,7,7,7,7,7,7,7,4], [10,9,7,7,7,7,7,7,7,7,6,6,6]),
  ([9,9,8,7,7,7,7,7,7,7,7,7,4], [10,9,7,7,7,7,7,7,7,7,7,6,5]),
  ([9,9,8,7,7,7,7,7,7,7,7,7,4], [10,9,7,7,7,7,7,7,7,7,7,7,4]),
  ([9,9,8,7,7,7,7,7,7,7,7,7,4], [11,7,7,7,7,7,7,7,7,7,7,6,6]),
  ([9,9,8,7,7,7,7,7,7,7,7,7,4], [11,7,7,7,7,7,7,7,7,7,7,7,5]),
  ([9,9,8,7,7,7,7,7,7,7,7,7,4], [11,8,7,7,7,7,7,7,7,7,6,6,6]),
  ([9,9,8,7,7,7,7,7,7,7,7,7,4], [11,8,7,7,7,7,7,7,7,7,7,6,5]),
  ([10,7,7,7,7,7,7,7,7,7,7,7,6], [8,8,7,7,7,7,7,7,7,7,7,7,7]),
  ([10,7,7,7,7,7,7,7,7,7,7,7,6], [8,8,8,7,7,7,7,7,7,7,7,7,6]),
  ([10,7,7,7,7,7,7,7,7,7,7,7,6], [8,8,8,8,7,7,7,7,7,7,7,6,6]),
  ([10,7,7,7,7,7,7,7,7,7,7,7,6], [8,8,8,8,7,7,7,7,7,7,7,7,5]),
  ([10,7,7,7,7,7,7,7,7,7,7,7,6], [8,8,8,8,8,7,7,7,7,7,6,6,6]),
  ([10,7,7,7,7,7,7,7,7,7,7,7,6], [8,8,8,8,8,7,7,7,7,7,7,6,5]),
  ([10,7,7,7,7,7,7,7,7,7,7,7,6], [8,8,8,8,8,7,7,7,7,7,7,7,4]),
  ([10,7,7,7,7,7,7,7,7,7,7,7,6], [9,7,7,7,7,7,7,7,7,7,7,7,7]),
  ([10,7,7,7,7,7,7,7,7,7,7,7,6], [9,8,7,7,7,7,7,7,7,7,7,7,6]),
  ([10,7,7,7,7,7,7,7,7,7,7,7,6], [9,8,8,7,7,7,7,7,7,7,7,6,6]),
  ([10,7,7,7,7,7,7,7,7,7,7,7,6], [9,8,8,7,7,7,7,7,7,7,7,7,5]),
  ([10,7,7,7,7,7,7,7,7,7,7,7,6], [9,8,8,8,7,7,7,7,7,7,6,6,6]),
  ([10,7,7,7,7,7,7,7,7,7,7,7,6], [9,8,8,8,7,7,7,7,7,7,7,6,5]),
  ([10,7,7,7,7,7,7,7,7,7,7,7,6], [9,8,8,8,7,7,7,7,7,7,7,7,4]),
  ([10,7,7,7,7,7,7,7,7,7,7,7,6], [9,9,7,7,7,7,7,7,7,7,7,6,6]),
  ([10,7,7,7,7,7,7,7,7,7,7,7,6], [9,9,7,7,7,7,7,7,7,7,7,7,5]),
  ([10,7,7,7,7,7,7,7,7,7,7,7,6], [9,9,8,7,7,7,7,7,7,7,6,6,6]),
  ([10,7,7,7,7,7,7,7,7,7,7,7,6], [9,9,8,7,7,7,7,7,7,7,7,6,5]),
  ([10,7,7,7,7,7,7,7,7,7,7,7,6], [9,9,8,7,7,7,7,7,7,7,7,7,4]),
  ([10,7,7,7,7,7,7,7,7,7,7,7,6], [10,7,7,7,7,7,7,7,7,7,7,7,6]),
  ([10,7,7,7,7,7,7,7,7,7,7,7,6], [10,8,7,7,7,7,7,7,7,7,7,6,6]),
  ([10,7,7,7,7,7,7,7,7,7,7,7,6], [10,8,7,7,7,7,7,7,7,7,7,7,5]),
  ([10,7,7,7,7,7,7,7,7,7,7,7,6], [10,8,8,7,7,7,7,7,7,7,6,6,6]),
  ([10,7,7,7,7,7,7,7,7,7,7,7,6], [10,8,8,7,7,7,7,7,7,7,7,6,5]),
  ([10,7,7,7,7,7,7,7,7,7,7,7,6], [10,8,8,7,7,7,7,7,7,7,7,7,4]),
  ([10,7,7,7,7,7,7,7,7,7,7,7,6], [10,9,7,7,7,7,7,7,7,7,6,6,6]),
  ([10,7,7,7,7,7,7,7,7,7,7,7,6], [10,9,7,7,7,7,7,7,7,7,7,6,5]),
  ([10,7,7,7,7,7,7,7,7,7,7,7,6], [10,9,7,7,7,7,7,7,7,7,7,7,4]),
  ([10,7,7,7,7,7,7,7,7,7,7,7,6], [11,7,7,7,7,7,7,7,7,7,7,6,6]),
  ([10,7,7,7,7,7,7,7,7,7,7,7,6], [11,7,7,7,7,7,7,7,7,7,7,7,5]),
  ([10,7,7,7,7,7,7,7,7,7,7,7,6], [11,8,7,7,7,7,7,7,7,7,6,6,6]),
  ([10,7,7,7,7,7,7,7,7,7,7,7,6], [11,8,7,7,7,7,7,7,7,7,7,6,5]),
  ([10,8,7,7,7,7,7,7,7,7,7,6,6], [8,8,7,7,7,7,7,7,7,7,7,7,7]),
  ([10,8,7,7,7,7,7,7,7,7,7,6,6], [8,8,8,7,7,7,7,7,7,7,7,7,6]),
  ([10,8,7,7,7,7,7,7,7,7,7,6,6], [8,8,8,8,7,7,7,7,7,7,7,6,6]),
  ([10,8,7,7,7,7,7,7,7,7,7,6,6], [8,8,8,8,7,7,7,7,7,7,7,7,5]),
  ([10,8,7,7,7,7,7,7,7,7,7,6,6], [8,8,8,8,8,7,7,7,7,7,6,6,6]),
  ([10,8,7,7,7,7,7,7,7,7,7,6,6], [8,8,8,8,8,7,7,7,7,7,7,6,5]),
  ([10,8,7,7,7,7,7,7,7,7,7,6,6], [8,8,8,8,8,7,7,7,7,7,7,7,4]),
  ([10,8,7,7,7,7,7,7,7,7,7,6,6], [9,7,7,7,7,7,7,7,7,7,7,7,7]),
  ([10,8,7,7,7,7,7,7,7,7,7,6,6], [9,8,7,7,7,7,7,7,7,7,7,7,6]),
  ([10,8,7,7,7,7,7,7,7,7,7,6,6], [9,8,8,7,7,7,7,7,7,7,7,6,6]),
  ([10,8,7,7,7,7,7,7,7,7,7,6,6], [9,8,8,7,7,7,7,7,7,7,7,7,5]),
  ([10,8,7,7,7,7,7,7,7,7,7,6,6], [9,8,8,8,7,7,7,7,7,7,6,6,6]),
  ([10,8,7,7,7,7,7,7,7,7,7,6,6], [9,8,8,8,7,7,7,7,7,7,7,6,5]),
  ([10,8,7,7,7,7,7,7,7,7,7,6,6], [9,8,8,8,7,7,7,7,7,7,7,7,4]),
  ([10,8,7,7,7,7,7,7,7,7,7,6,6], [9,9,7,7,7,7,7,7,7,7,7,6,6]),
  ([10,8,7,7,7,7,7,7,7,7,7,6,6], [9,9,7,7,7,7,7,7,7,7,7,7,5]),
  ([10,8,7,7,7,7,7,7,7,7,7,6,6], [9,9,8,7,7,7,7,7,7,7,6,6,6]),
  ([10,8,7,7,7,7,7,7,7,7,7,6,6], [9,9,8,7,7,7,7,7,7,7,7,6,5]),
  ([10,8,7,7,7,7,7,7,7,7,7,6,6], [9,9,8,7,7,7,7,7,7,7,7,7,4]),
  ([10,8,7,7,7,7,7,7,7,7,7,6,6], [10,7,7,7,7,7,7,7,7,7,7,7,6]),
  ([10,8,7,7,7,7,7,7,7,7,7,6,6], [10,8,7,7,7,7,7,7,7,7,7,6,6]),
  ([10,8,7,7,7,7,7,7,7,7,7,6,6], [10,8,7,7,7,7,7,7,7,7,7,7,5]),
  ([10,8,7,7,7,7,7,7,7,7,7,6,6], [10,8,8,7,7,7,7,7,7,7,6,6,6]),
  ([10,8,7,7,7,7,7,7,7,7,7,6,6], [10,8,8,7,7,7,7,7,7,7,7,6,5]),
  ([10,8,7,7,7,7,7,7,7,7,7,6,6], [10,8,8,7,7,7,7,7,7,7,7,7,4]),
  ([10,8,7,7,7,7,7,7,7,7,7,6,6], [10,9,7,7,7,7,7,7,7,7,6,6,6]),
  ([10,8,7,7,7,7,7,7,7,7,7,6,6], [10,9,7,7,7,7,7,7,7,7,7,6,5]),
  ([10,8,7,7,7,7,7,7,7,7,7,6,6], [10,9,7,7,7,7,7,7,7,7,7,7,4]),
  ([10,8,7,7,7,7,7,7,7,7,7,6,6], [11,7,7,7,7,7,7,7,7,7,7,6,6]),
  ([10,8,7,7,7,7,7,7,7,7,7,6,6], [11,7,7,7,7,7,7,7,7,7,7,7,5]),
  ([10,8,7,7,7,7,7,7,7,7,7,6,6], [11,8,7,7,7,7,7,7,7,7,6,6,6]),
  ([10,8,7,7,7,7,7,7,7,7,7,6,6], [11,8,7,7,7,7,7,7,7,7,7,6,5]),
  ([10,8,7,7,7,7,7,7,7,7,7,7,5], [8,8,7,7,7,7,7,7,7,7,7,7,7]),
  ([10,8,7,7,7,7,7,7,7,7,7,7,5], [8,8,8,7,7,7,7,7,7,7,7,7,6]),
  ([10,8,7,7,7,7,7,7,7,7,7,7,5], [8,8,8,8,7,7,7,7,7,7,7,6,6]),
  ([10,8,7,7,7,7,7,7,7,7,7,7,5], [8,8,8,8,7,7,7,7,7,7,7,7,5]),
  ([10,8,7,7,7,7,7,7,7,7,7,7,5], [8,8,8,8,8,7,7,7,7,7,6,6,6]),
  ([10,8,7,7,7,7,7,7,7,7,7,7,5], [8,8,8,8,8,7,7,7,7,7,7,6,5]),
  ([10,8,7,7,7,7,7,7,7,7,7,7,5], [8,8,8,8,8,7,7,7,7,7,7,7,4]),
  ([10,8,7,7,7,7,7,7,7,7,7,7,5], [9,7,7,7,7,7,7,7,7,7,7,7,7]),
  ([10,8,7,7,7,7,7,7,7,7,7,7,5], [9,8,7,7,7,7,7,7,7,7,7,7,6]),
  ([10,8,7,7,7,7,7,7,7,7,7,7,5], [9,8,8,7,7,7,7,7,7,7,7,6,6]),
  ([10,8,7,7,7,7,7,7,7,7,7,7,5], [9,8,8,7,7,7,7,7,7,7,7,7,5]),
  ([10,8,7,7,7,7,7,7,7,7,7,7,5], [9,8,8,8,7,7,7,7,7,7,6,6,6]),
  ([10,8,7,7,7,7,7,7,7,7,7,7,5], [9,8,8,8,7,7,7,7,7,7,7,6,5]),
  ([10,8,7,7,7,7,7,7,7,7,7,7,5], [9,8,8,8,7,7,7,7,7,7,7,7,4]),
  ([10,8,7,7,7,7,7,7,7,7,7,7,5], [9,9,7,7,7,7,7,7,7,7,7,6,6]),
  ([10,8,7,7,7,7,7,7,7,7,7,7,5], [9,9,7,7,7,7,7,7,7,7,7,7,5]),
  ([10,8,7,7,7,7,7,7,7,7,7,7,5], [9,9,8,7,7,7,7,7,7,7,6,6,6]),
  ([10,8,7,7,7,7,7,7,7,7,7,7,5], [9,9,8,7,7,7,7,7,7,7,7,6,5]),
  ([10,8,7,7,7,7,7,7,7,7,7,7,5], [9,9,8,7,7,7,7,7,7,7,7,7,4]),
  ([10,8,7,7,7,7,7,7,7,7,7,7,5], [10,7,7,7,7,7,7,7,7,7,7,7,6]),
  ([10,8,7,7,7,7,7,7,7,7,7,7,5], [10,8,7,7,7,7,7,7,7,7,7,6,6]),
  ([10,8,7,7,7,7,7,7,7,7,7,7,5], [10,8,7,7,7,7,7,7,7,7,7,7,5]),
  ([10,8,7,7,7,7,7,7,7,7,7,7,5], [10,8,8,7,7,7,7,7,7,7,6,6,6]),
  ([10,8,7,7,7,7,7,7,7,7,7,7,5], [10,8,8,7,7,7,7,7,7,7,7,6,5]),
  ([10,8,7,7,7,7,7,7,7,7,7,7,5], [10,8,8,7,7,7,7,7,7,7,7,7,4]),
  ([10,8,7,7,7,7,7,7,7,7,7,7,5], [10,9,7,7,7,7,7,7,7,7,6,6,6]),
  ([10,8,7,7,7,7,7,7,7,7,7,7,5], [10,9,7,7,7,7,7,7,7,7,7,6,5]),
  ([10,8,7,7,7,7,7,7,7,7,7,7,5], [10,9,7,7,7,7,7,7,7,7,7,7,4]),
  ([10,8,7,7,7,7,7,7,7,7,7,7,5], [11,7,7,7,7,7,7,7,7,7,7,6,6]),
  ([10,8,7,7,7,7,7,7,7,7,7,7,5], [11,7,7,7,7,7,7,7,7,7,7,7,5]),
  ([10,8,7,7,7,7,7,7,7,7,7,7,5], [11,8,7,7,7,7,7,7,7,7,6,6,6]),
  ([10,8,7,7,7,7,7,7,7,7,7,7,5], [11,8,7,7,7,7,7,7,7,7,7,6,5]),
  ([10,8,8,7,7,7,7,7,7,7,6,6,6], [8,8,7,7,7,7,7,7,7,7,7,7,7]),
  ([10,8,8,7,7,7,7,7,7,7,6,6,6], [8,8,8,7,7,7,7,7,7,7,7,7,6]),
  ([10,8,8,7,7,7,7,7,7,7,6,6,6], [8,8,8,8,7,7,7,7,7,7,7,6,6]),
  ([10,8,8,7,7,7,7,7,7,7,6,6,6], [8,8,8,8,7,7,7,7,7,7,7,7,5]),
  ([10,8,8,7,7,7,7,7,7,7,6,6,6], [8,8,8,8,8,7,7,7,7,7,6,6,6]),
  ([10,8,8,7,7,7,7,7,7,7,6,6,6], [8,8,8,8,8,7,7,7,7,7,7,6,5]),
  ([10,8,8,7,7,7,7,7,7,7,6,6,6], [8,8,8,8,8,7,7,7,7,7,7,7,4]),
  ([10,8,8,7,7,7,7,7,7,7,6,6,6], [9,7,7,7,7,7,7,7,7,7,7,7,7]),
  ([10,8,8,7,7,7,7,7,7,7,6,6,6], [9,8,7,7,7,7,7,7,7,7,7,7,6]),
  ([10,8,8,7,7,7,7,7,7,7,6,6,6], [9,8,8,7,7,7,7,7,7,7,7,6,6]),
  ([10,8,8,7,7,7,7,7,7,7,6,6,6], [9,8,8,7,7,7,7,7,7,7,7,7,5]),
  ([10,8,8,7,7,7,7,7,7,7,6,6,6], [9,8,8,8,7,7,7,7,7,7,6,6,6]),
  ([10,8,8,7,7,7,7,7,7,7,6,6,6], [9,8,8,8,7,7,7,7,7,7,7,6,5]),
  ([10,8,8,7,7,7,7,7,7,7,6,6,6], [9,8,8,8,7,7,7,7,7,7,7,7,4]),
  ([10,8,8,7,7,7,7,7,7,7,6,6,6], [9,9,7,7,7,7,7,7,7,7,7,6,6]),
  ([10,8,8,7,7,7,7,7,7,7,6,6,6], [9,9,7,7,7,7,7,7,7,7,7,7,5]),
  ([10,8,8,7,7,7,7,7,7,7,6,6,6], [9,9,8,7,7,7,7,7,7,7,6,6,6]),
  ([10,8,8,7,7,7,7,7,7,7,6,6,6], [9,9,8,7,7,7,7,7,7,7,7,6,5]),
  ([10,8,8,7,7,7,7,7,7,7,6,6,6], [9,9,8,7,7,7,7,7,7,7,7,7,4]),
  ([10,8,8,7,7,7,7,7,7,7,6,6,6], [10,7,7,7,7,7,7,7,7,7,7,7,6]),
  ([10,8,8,7,7,7,7,7,7,7,6,6,6], [10,8,7,7,7,7,7,7,7,7,7,6,6]),
  ([10,8,8,7,7,7,7,7,7,7,6,6,6], [10,8,7,7,7,7,7,7,7,7,7,7,5]),
  ([10,8,8,7,7,7,7,7,7,7,6,6,6], [10,8,8,7,7,7,7,7,7,7,6,6,6]),
  ([10,8,8,7,7,7,7,7,7,7,6,6,6], [10,8,8,7,7,7,7,7,7,7,7,6,5]),
  ([10,8,8,7,7,7,7,7,7,7,6,6,6], [10,8,8,7,7,7,7,7,7,7,7,7,4]),
  ([10,8,8,7,7,7,7,7,7,7,6,6,6], [10,9,7,7,7,7,7,7,7,7,6,6,6]),
  ([10,8,8,7,7,7,7,7,7,7,6,6,6], [10,9,7,7,7,7,7,7,7,7,7,6,5]),
  ([10,8,8,7,7,7,7,7,7,7,6,6,6], [10,9,7,7,7,7,7,7,7,7,7,7,4]),
  ([10,8,8,7,7,7,7,7,7,7,6,6,6], [11,7,7,7,7,7,7,7,7,7,7,6,6]),
  ([10,8,8,7,7,7,7,7,7,7,6,6,6], [11,7,7,7,7,7,7,7,7,7,7,7,5]),
  ([10,8,8,7,7,7,7,7,7,7,6,6,6], [11,8,7,7,7,7,7,7,7,7,6,6,6]),
  ([10,8,8,7,7,7,7,7,7,7,6,6,6], [11,8,7,7,7,7,7,7,7,7,7,6,5]),
  ([10,8,8,7,7,7,7,7,7,7,7,6,5], [8,8,7,7,7,7,7,7,7,7,7,7,7]),
  ([10,8,8,7,7,7,7,7,7,7,7,6,5], [8,8,8,7,7,7,7,7,7,7,7,7,6]),
  ([10,8,8,7,7,7,7,7,7,7,7,6,5], [8,8,8,8,7,7,7,7,7,7,7,6,6]),
  ([10,8,8,7,7,7,7,7,7,7,7,6,5], [8,8,8,8,7,7,7,7,7,7,7,7,5]),
  ([10,8,8,7,7,7,7,7,7,7,7,6,5], [8,8,8,8,8,7,7,7,7,7,6,6,6]),
  ([10,8,8,7,7,7,7,7,7,7,7,6,5], [8,8,8,8,8,7,7,7,7,7,7,6,5]),
  ([10,8,8,7,7,7,7,7,7,7,7,6,5], [8,8,8,8,8,7,7,7,7,7,7,7,4]),
  ([10,8,8,7,7,7,7,7,7,7,7,6,5], [9,7,7,7,7,7,7,7,7,7,7,7,7]),
  ([10,8,8,7,7,7,7,7,7,7,7,6,5], [9,8,7,7,7,7,7,7,7,7,7,7,6]),
  ([10,8,8,7,7,7,7,7,7,7,7,6,5], [9,8,8,7,7,7,7,7,7,7,7,6,6]),
  ([10,8,8,7,7,7,7,7,7,7,7,6,5], [9,8,8,7,7,7,7,7,7,7,7,7,5]),
  ([10,8,8,7,7,7,7,7,7,7,7,6,5], [9,8,8,8,7,7,7,7,7,7,6,6,6]),
  ([10,8,8,7,7,7,7,7,7,7,7,6,5], [9,8,8,8,7,7,7,7,7,7,7,6,5]),
  ([10,8,8,7,7,7,7,7,7,7,7,6,5], [9,8,8,8,7,7,7,7,7,7,7,7,4]),
  ([10,8,8,7,7,7,7,7,7,7,7,6,5], [9,9,7,7,7,7,7,7,7,7,7,6,6]),
  ([10,8,8,7,7,7,7,7,7,7,7,6,5], [9,9,7,7,7,7,7,7,7,7,7,7,5]),
  ([10,8,8,7,7,7,7,7,7,7,7,6,5], [9,9,8,7,7,7,7,7,7,7,6,6,6]),
  ([10,8,8,7,7,7,7,7,7,7,7,6,5], [9,9,8,7,7,7,7,7,7,7,7,6,5]),
  ([10,8,8,7,7,7,7,7,7,7,7,6,5], [9,9,8,7,7,7,7,7,7,7,7,7,4]),
  ([10,8,8,7,7,7,7,7,7,7,7,6,5], [10,7,7,7,7,7,7,7,7,7,7,7,6]),
  ([10,8,8,7,7,7,7,7,7,7,7,6,5], [10,8,7,7,7,7,7,7,7,7,7,6,6]),
  ([10,8,8,7,7,7,7,7,7,7,7,6,5], [10,8,7,7,7,7,7,7,7,7,7,7,5]),
  ([10,8,8,7,7,7,7,7,7,7,7,6,5], [10,8,8,7,7,7,7,7,7,7,6,6,6]),
  ([10,8,8,7,7,7,7,7,7,7,7,6,5], [10,8,8,7,7,7,7,7,7,7,7,6,5]),
  ([10,8,8,7,7,7,7,7,7,7,7,6,5], [10,8,8,7,7,7,7,7,7,7,7,7,4]),
  ([10,8,8,7,7,7,7,7,7,7,7,6,5], [10,9,7,7,7,7,7,7,7,7,6,6,6]),
  ([10,8,8,7,7,7,7,7,7,7,7,6,5], [10,9,7,7,7,7,7,7,7,7,7,6,5]),
  ([10,8,8,7,7,7,7,7,7,7,7,6,5], [10,9,7,7,7,7,7,7,7,7,7,7,4]),
  ([10,8,8,7,7,7,7,7,7,7,7,6,5], [11,7,7,7,7,7,7,7,7,7,7,6,6]),
  ([10,8,8,7,7,7,7,7,7,7,7,6,5], [11,7,7,7,7,7,7,7,7,7,7,7,5]),
  ([10,8,8,7,7,7,7,7,7,7,7,6,5], [11,8,7,7,7,7,7,7,7,7,6,6,6]),
  ([10,8,8,7,7,7,7,7,7,7,7,6,5], [11,8,7,7,7,7,7,7,7,7,7,6,5]),
  ([10,8,8,7,7,7,7,7,7,7,7,7,4], [8,8,7,7,7,7,7,7,7,7,7,7,7]),
  ([10,8,8,7,7,7,7,7,7,7,7,7,4], [8,8,8,7,7,7,7,7,7,7,7,7,6]),
  ([10,8,8,7,7,7,7,7,7,7,7,7,4], [8,8,8,8,7,7,7,7,7,7,7,6,6]),
  ([10,8,8,7,7,7,7,7,7,7,7,7,4], [8,8,8,8,7,7,7,7,7,7,7,7,5]),
  ([10,8,8,7,7,7,7,7,7,7,7,7,4], [8,8,8,8,8,7,7,7,7,7,6,6,6]),
  ([10,8,8,7,7,7,7,7,7,7,7,7,4], [8,8,8,8,8,7,7,7,7,7,7,6,5]),
  ([10,8,8,7,7,7,7,7,7,7,7,7,4], [8,8,8,8,8,7,7,7,7,7,7,7,4]),
  ([10,8,8,7,7,7,7,7,7,7,7,7,4], [9,7,7,7,7,7,7,7,7,7,7,7,7]),
  ([10,8,8,7,7,7,7,7,7,7,7,7,4], [9,8,7,7,7,7,7,7,7,7,7,7,6]),
  ([10,8,8,7,7,7,7,7,7,7,7,7,4], [9,8,8,7,7,7,7,7,7,7,7,6,6]),
  ([10,8,8,7,7,7,7,7,7,7,7,7,4], [9,8,8,7,7,7,7,7,7,7,7,7,5]),
  ([10,8,8,7,7,7,7,7,7,7,7,7,4], [9,8,8,8,7,7,7,7,7,7,6,6,6]),
  ([10,8,8,7,7,7,7,7,7,7,7,7,4], [9,8,8,8,7,7,7,7,7,7,7,6,5]),
  ([10,8,8,7,7,7,7,7,7,7,7,7,4], [9,8,8,8,7,7,7,7,7,7,7,7,4]),
  ([10,8,8,7,7,7,7,7,7,7,7,7,4], [9,9,7,7,7,7,7,7,7,7,7,6,6]),
  ([10,8,8,7,7,7,7,7,7,7,7,7,4], [9,9,7,7,7,7,7,7,7,7,7,7,5]),
  ([10,8,8,7,7,7,7,7,7,7,7,7,4], [9,9,8,7,7,7,7,7,7,7,6,6,6]),
  ([10,8,8,7,7,7,7,7,7,7,7,7,4], [9,9,8,7,7,7,7,7,7,7,7,6,5]),
  ([10,8,8,7,7,7,7,7,7,7,7,7,4], [9,9,8,7,7,7,7,7,7,7,7,7,4]),
  ([10,8,8,7,7,7,7,7,7,7,7,7,4], [10,7,7,7,7,7,7,7,7,7,7,7,6]),
  ([10,8,8,7,7,7,7,7,7,7,7,7,4], [10,8,7,7,7,7,7,7,7,7,7,6,6]),
  ([10,8,8,7,7,7,7,7,7,7,7,7,4], [10,8,7,7,7,7,7,7,7,7,7,7,5]),
  ([10,8,8,7,7,7,7,7,7,7,7,7,4], [10,8,8,7,7,7,7,7,7,7,6,6,6]),
  ([10,8,8,7,7,7,7,7,7,7,7,7,4], [10,8,8,7,7,7,7,7,7,7,7,6,5]),
  ([10,8,8,7,7,7,7,7,7,7,7,7,4], [10,8,8,7,7,7,7,7,7,7,7,7,4]),
  ([10,8,8,7,7,7,7,7,7,7,7,7,4], [10,9,7,7,7,7,7,7,7,7,6,6,6]),
  ([10,8,8,7,7,7,7,7,7,7,7,7,4], [10,9,7,7,7,7,7,7,7,7,7,6,5]),
  ([10,8,8,7,7,7,7,7,7,7,7,7,4], [10,9,7,7,7,7,7,7,7,7,7,7,4]),
  ([10,8,8,7,7,7,7,7,7,7,7,7,4], [11,7,7,7,7,7,7,7,7,7,7,6,6]),
  ([10,8,8,7,7,7,7,7,7,7,7,7,4], [11,7,7,7,7,7,7,7,7,7,7,7,5]),
  ([10,8,8,7,7,7,7,7,7,7,7,7,4], [11,8,7,7,7,7,7,7,7,7,6,6,6]),
  ([10,8,8,7,7,7,7,7,7,7,7,7,4], [11,8,7,7,7,7,7,7,7,7,7,6,5]),
  ([10,9,7,7,7,7,7,7,7,7,6,6,6], [8,8,7,7,7,7,7,7,7,7,7,7,7]),
  ([10,9,7,7,7,7,7,7,7,7,6,6,6], [8,8,8,7,7,7,7,7,7,7,7,7,6]),
  ([10,9,7,7,7,7,7,7,7,7,6,6,6], [8,8,8,8,7,7,7,7,7,7,7,6,6]),
  ([10,9,7,7,7,7,7,7,7,7,6,6,6], [8,8,8,8,7,7,7,7,7,7,7,7,5]),
  ([10,9,7,7,7,7,7,7,7,7,6,6,6], [8,8,8,8,8,7,7,7,7,7,6,6,6]),
  ([10,9,7,7,7,7,7,7,7,7,6,6,6], [8,8,8,8,8,7,7,7,7,7,7,6,5]),
  ([10,9,7,7,7,7,7,7,7,7,6,6,6], [8,8,8,8,8,7,7,7,7,7,7,7,4]),
  ([10,9,7,7,7,7,7,7,7,7,6,6,6], [9,7,7,7,7,7,7,7,7,7,7,7,7]),
  ([10,9,7,7,7,7,7,7,7,7,6,6,6], [9,8,7,7,7,7,7,7,7,7,7,7,6]),
  ([10,9,7,7,7,7,7,7,7,7,6,6,6], [9,8,8,7,7,7,7,7,7,7,7,6,6]),
  ([10,9,7,7,7,7,7,7,7,7,6,6,6], [9,8,8,7,7,7,7,7,7,7,7,7,5]),
  ([10,9,7,7,7,7,7,7,7,7,6,6,6], [9,8,8,8,7,7,7,7,7,7,6,6,6]),
  ([10,9,7,7,7,7,7,7,7,7,6,6,6], [9,8,8,8,7,7,7,7,7,7,7,6,5]),
  ([10,9,7,7,7,7,7,7,7,7,6,6,6], [9,8,8,8,7,7,7,7,7,7,7,7,4]),
  ([10,9,7,7,7,7,7,7,7,7,6,6,6], [9,9,7,7,7,7,7,7,7,7,7,6,6]),
  ([10,9,7,7,7,7,7,7,7,7,6,6,6], [9,9,7,7,7,7,7,7,7,7,7,7,5]),
  ([10,9,7,7,7,7,7,7,7,7,6,6,6], [9,9,8,7,7,7,7,7,7,7,6,6,6]),
  ([10,9,7,7,7,7,7,7,7,7,6,6,6], [9,9,8,7,7,7,7,7,7,7,7,6,5]),
  ([10,9,7,7,7,7,7,7,7,7,6,6,6], [9,9,8,7,7,7,7,7,7,7,7,7,4]),
  ([10,9,7,7,7,7,7,7,7,7,6,6,6], [10,7,7,7,7,7,7,7,7,7,7,7,6]),
  ([10,9,7,7,7,7,7,7,7,7,6,6,6], [10,8,7,7,7,7,7,7,7,7,7,6,6]),
  ([10,9,7,7,7,7,7,7,7,7,6,6,6], [10,8,7,7,7,7,7,7,7,7,7,7,5]),
  ([10,9,7,7,7,7,7,7,7,7,6,6,6], [10,8,8,7,7,7,7,7,7,7,6,6,6]),
  ([10,9,7,7,7,7,7,7,7,7,6,6,6], [10,8,8,7,7,7,7,7,7,7,7,6,5]),
  ([10,9,7,7,7,7,7,7,7,7,6,6,6], [10,8,8,7,7,7,7,7,7,7,7,7,4]),
  ([10,9,7,7,7,7,7,7,7,7,6,6,6], [10,9,7,7,7,7,7,7,7,7,6,6,6]),
  ([10,9,7,7,7,7,7,7,7,7,6,6,6], [10,9,7,7,7,7,7,7,7,7,7,6,5]),
  ([10,9,7,7,7,7,7,7,7,7,6,6,6], [10,9,7,7,7,7,7,7,7,7,7,7,4]),
  ([10,9,7,7,7,7,7,7,7,7,6,6,6], [11,7,7,7,7,7,7,7,7,7,7,6,6]),
  ([10,9,7,7,7,7,7,7,7,7,6,6,6], [11,7,7,7,7,7,7,7,7,7,7,7,5]),
  ([10,9,7,7,7,7,7,7,7,7,6,6,6], [11,8,7,7,7,7,7,7,7,7,6,6,6]),
  ([10,9,7,7,7,7,7,7,7,7,6,6,6], [11,8,7,7,7,7,7,7,7,7,7,6,5]),
  ([10,9,7,7,7,7,7,7,7,7,7,6,5], [8,8,7,7,7,7,7,7,7,7,7,7,7]),
  ([10,9,7,7,7,7,7,7,7,7,7,6,5], [8,8,8,7,7,7,7,7,7,7,7,7,6]),
  ([10,9,7,7,7,7,7,7,7,7,7,6,5], [8,8,8,8,7,7,7,7,7,7,7,6,6]),
  ([10,9,7,7,7,7,7,7,7,7,7,6,5], [8,8,8,8,7,7,7,7,7,7,7,7,5]),
  ([10,9,7,7,7,7,7,7,7,7,7,6,5], [8,8,8,8,8,7,7,7,7,7,6,6,6]),
  ([10,9,7,7,7,7,7,7,7,7,7,6,5], [8,8,8,8,8,7,7,7,7,7,7,6,5]),
  ([10,9,7,7,7,7,7,7,7,7,7,6,5], [8,8,8,8,8,7,7,7,7,7,7,7,4]),
  ([10,9,7,7,7,7,7,7,7,7,7,6,5], [9,7,7,7,7,7,7,7,7,7,7,7,7]),
  ([10,9,7,7,7,7,7,7,7,7,7,6,5], [9,8,7,7,7,7,7,7,7,7,7,7,6]),
  ([10,9,7,7,7,7,7,7,7,7,7,6,5], [9,8,8,7,7,7,7,7,7,7,7,6,6]),
  ([10,9,7,7,7,7,7,7,7,7,7,6,5], [9,8,8,7,7,7,7,7,7,7,7,7,5]),
  ([10,9,7,7,7,7,7,7,7,7,7,6,5], [9,8,8,8,7,7,7,7,7,7,6,6,6]),
  ([10,9,7,7,7,7,7,7,7,7,7,6,5], [9,8,8,8,7,7,7,7,7,7,7,6,5]),
  ([10,9,7,7,7,7,7,7,7,7,7,6,5], [9,8,8,8,7,7,7,7,7,7,7,7,4]),
  ([10,9,7,7,7,7,7,7,7,7,7,6,5], [9,9,7,7,7,7,7,7,7,7,7,6,6]),
  ([10,9,7,7,7,7,7,7,7,7,7,6,5], [9,9,7,7,7,7,7,7,7,7,7,7,5]),
  ([10,9,7,7,7,7,7,7,7,7,7,6,5], [9,9,8,7,7,7,7,7,7,7,6,6,6]),
  ([10,9,7,7,7,7,7,7,7,7,7,6,5], [9,9,8,7,7,7,7,7,7,7,7,6,5]),
  ([10,9,7,7,7,7,7,7,7,7,7,6,5], [9,9,8,7,7,7,7,7,7,7,7,7,4]),
  ([10,9,7,7,7,7,7,7,7,7,7,6,5], [10,7,7,7,7,7,7,7,7,7,7,7,6]),
  ([10,9,7,7,7,7,7,7,7,7,7,6,5], [10,8,7,7,7,7,7,7,7,7,7,6,6]),
  ([10,9,7,7,7,7,7,7,7,7,7,6,5], [10,8,7,7,7,7,7,7,7,7,7,7,5]),
  ([10,9,7,7,7,7,7,7,7,7,7,6,5], [10,8,8,7,7,7,7,7,7,7,6,6,6]),
  ([10,9,7,7,7,7,7,7,7,7,7,6,5], [10,8,8,7,7,7,7,7,7,7,7,6,5]),
  ([10,9,7,7,7,7,7,7,7,7,7,6,5], [10,8,8,7,7,7,7,7,7,7,7,7,4]),
  ([10,9,7,7,7,7,7,7,7,7,7,6,5], [10,9,7,7,7,7,7,7,7,7,6,6,6]),
  ([10,9,7,7,7,7,7,7,7,7,7,6,5], [10,9,7,7,7,7,7,7,7,7,7,6,5]),
  ([10,9,7,7,7,7,7,7,7,7,7,6,5], [10,9,7,7,7,7,7,7,7,7,7,7,4]),
  ([10,9,7,7,7,7,7,7,7,7,7,6,5], [11,7,7,7,7,7,7,7,7,7,7,6,6]),
  ([10,9,7,7,7,7,7,7,7,7,7,6,5], [11,7,7,7,7,7,7,7,7,7,7,7,5]),
  ([10,9,7,7,7,7,7,7,7,7,7,6,5], [11,8,7,7,7,7,7,7,7,7,6,6,6]),
  ([10,9,7,7,7,7,7,7,7,7,7,6,5], [11,8,7,7,7,7,7,7,7,7,7,6,5]),
  ([10,9,7,7,7,7,7,7,7,7,7,7,4], [8,8,7,7,7,7,7,7,7,7,7,7,7]),
  ([10,9,7,7,7,7,7,7,7,7,7,7,4], [8,8,8,7,7,7,7,7,7,7,7,7,6]),
  ([10,9,7,7,7,7,7,7,7,7,7,7,4], [8,8,8,8,7,7,7,7,7,7,7,6,6]),
  ([10,9,7,7,7,7,7,7,7,7,7,7,4], [8,8,8,8,7,7,7,7,7,7,7,7,5]),
  ([10,9,7,7,7,7,7,7,7,7,7,7,4], [8,8,8,8,8,7,7,7,7,7,6,6,6]),
  ([10,9,7,7,7,7,7,7,7,7,7,7,4], [8,8,8,8,8,7,7,7,7,7,7,6,5]),
  ([10,9,7,7,7,7,7,7,7,7,7,7,4], [8,8,8,8,8,7,7,7,7,7,7,7,4]),
  ([10,9,7,7,7,7,7,7,7,7,7,7,4], [9,7,7,7,7,7,7,7,7,7,7,7,7]),
  ([10,9,7,7,7,7,7,7,7,7,7,7,4], [9,8,7,7,7,7,7,7,7,7,7,7,6]),
  ([10,9,7,7,7,7,7,7,7,7,7,7,4], [9,8,8,7,7,7,7,7,7,7,7,6,6]),
  ([10,9,7,7,7,7,7,7,7,7,7,7,4], [9,8,8,7,7,7,7,7,7,7,7,7,5]),
  ([10,9,7,7,7,7,7,7,7,7,7,7,4], [9,8,8,8,7,7,7,7,7,7,6,6,6]),
  ([10,9,7,7,7,7,7,7,7,7,7,7,4], [9,8,8,8,7,7,7,7,7,7,7,6,5]),
  ([10,9,7,7,7,7,7,7,7,7,7,7,4], [9,8,8,8,7,7,7,7,7,7,7,7,4]),
  ([10,9,7,7,7,7,7,7,7,7,7,7,4], [9,9,7,7,7,7,7,7,7,7,7,6,6]),
  ([10,9,7,7,7,7,7,7,7,7,7,7,4], [9,9,7,7,7,7,7,7,7,7,7,7,5]),
  ([10,9,7,7,7,7,7,7,7,7,7,7,4], [9,9,8,7,7,7,7,7,7,7,6,6,6]),
  ([10,9,7,7,7,7,7,7,7,7,7,7,4], [9,9,8,7,7,7,7,7,7,7,7,6,5]),
  ([10,9,7,7,7,7,7,7,7,7,7,7,4], [9,9,8,7,7,7,7,7,7,7,7,7,4]),
  ([10,9,7,7,7,7,7,7,7,7,7,7,4], [10,7,7,7,7,7,7,7,7,7,7,7,6]),
  ([10,9,7,7,7,7,7,7,7,7,7,7,4], [10,8,7,7,7,7,7,7,7,7,7,6,6]),
  ([10,9,7,7,7,7,7,7,7,7,7,7,4], [10,8,7,7,7,7,7,7,7,7,7,7,5]),
  ([10,9,7,7,7,7,7,7,7,7,7,7,4], [10,8,8,7,7,7,7,7,7,7,6,6,6]),
  ([10,9,7,7,7,7,7,7,7,7,7,7,4], [10,8,8,7,7,7,7,7,7,7,7,6,5]),
  ([10,9,7,7,7,7,7,7,7,7,7,7,4], [10,8,8,7,7,7,7,7,7,7,7,7,4]),
  ([10,9,7,7,7,7,7,7,7,7,7,7,4], [10,9,7,7,7,7,7,7,7,7,6,6,6]),
  ([10,9,7,7,7,7,7,7,7,7,7,7,4], [10,9,7,7,7,7,7,7,7,7,7,6,5]),
  ([10,9,7,7,7,7,7,7,7,7,7,7,4], [10,9,7,7,7,7,7,7,7,7,7,7,4]),
  ([10,9,7,7,7,7,7,7,7,7,7,7,4], [11,7,7,7,7,7,7,7,7,7,7,6,6]),
  ([10,9,7,7,7,7,7,7,7,7,7,7,4], [11,7,7,7,7,7,7,7,7,7,7,7,5]),
  ([10,9,7,7,7,7,7,7,7,7,7,7,4], [11,8,7,7,7,7,7,7,7,7,6,6,6]),
  ([10,9,7,7,7,7,7,7,7,7,7,7,4], [11,8,7,7,7,7,7,7,7,7,7,6,5]),
  ([11,7,7,7,7,7,7,7,7,7,7,6,6], [8,8,7,7,7,7,7,7,7,7,7,7,7]),
  ([11,7,7,7,7,7,7,7,7,7,7,6,6], [8,8,8,7,7,7,7,7,7,7,7,7,6]),
  ([11,7,7,7,7,7,7,7,7,7,7,6,6], [8,8,8,8,7,7,7,7,7,7,7,6,6]),
  ([11,7,7,7,7,7,7,7,7,7,7,6,6], [8,8,8,8,7,7,7,7,7,7,7,7,5]),
  ([11,7,7,7,7,7,7,7,7,7,7,6,6], [8,8,8,8,8,7,7,7,7,7,6,6,6]),
  ([11,7,7,7,7,7,7,7,7,7,7,6,6], [8,8,8,8,8,7,7,7,7,7,7,6,5]),
  ([11,7,7,7,7,7,7,7,7,7,7,6,6], [8,8,8,8,8,7,7,7,7,7,7,7,4]),
  ([11,7,7,7,7,7,7,7,7,7,7,6,6], [9,7,7,7,7,7,7,7,7,7,7,7,7]),
  ([11,7,7,7,7,7,7,7,7,7,7,6,6], [9,8,7,7,7,7,7,7,7,7,7,7,6]),
  ([11,7,7,7,7,7,7,7,7,7,7,6,6], [9,8,8,7,7,7,7,7,7,7,7,6,6]),
  ([11,7,7,7,7,7,7,7,7,7,7,6,6], [9,8,8,7,7,7,7,7,7,7,7,7,5]),
  ([11,7,7,7,7,7,7,7,7,7,7,6,6], [9,8,8,8,7,7,7,7,7,7,6,6,6]),
  ([11,7,7,7,7,7,7,7,7,7,7,6,6], [9,8,8,8,7,7,7,7,7,7,7,6,5]),
  ([11,7,7,7,7,7,7,7,7,7,7,6,6], [9,8,8,8,7,7,7,7,7,7,7,7,4]),
  ([11,7,7,7,7,7,7,7,7,7,7,6,6], [9,9,7,7,7,7,7,7,7,7,7,6,6]),
  ([11,7,7,7,7,7,7,7,7,7,7,6,6], [9,9,7,7,7,7,7,7,7,7,7,7,5]),
  ([11,7,7,7,7,7,7,7,7,7,7,6,6], [9,9,8,7,7,7,7,7,7,7,6,6,6]),
  ([11,7,7,7,7,7,7,7,7,7,7,6,6], [9,9,8,7,7,7,7,7,7,7,7,6,5]),
  ([11,7,7,7,7,7,7,7,7,7,7,6,6], [9,9,8,7,7,7,7,7,7,7,7,7,4]),
  ([11,7,7,7,7,7,7,7,7,7,7,6,6], [10,7,7,7,7,7,7,7,7,7,7,7,6]),
  ([11,7,7,7,7,7,7,7,7,7,7,6,6], [10,8,7,7,7,7,7,7,7,7,7,6,6]),
  ([11,7,7,7,7,7,7,7,7,7,7,6,6], [10,8,7,7,7,7,7,7,7,7,7,7,5]),
  ([11,7,7,7,7,7,7,7,7,7,7,6,6], [10,8,8,7,7,7,7,7,7,7,6,6,6]),
  ([11,7,7,7,7,7,7,7,7,7,7,6,6], [10,8,8,7,7,7,7,7,7,7,7,6,5]),
  ([11,7,7,7,7,7,7,7,7,7,7,6,6], [10,8,8,7,7,7,7,7,7,7,7,7,4]),
  ([11,7,7,7,7,7,7,7,7,7,7,6,6], [10,9,7,7,7,7,7,7,7,7,6,6,6]),
  ([11,7,7,7,7,7,7,7,7,7,7,6,6], [10,9,7,7,7,7,7,7,7,7,7,6,5]),
  ([11,7,7,7,7,7,7,7,7,7,7,6,6], [10,9,7,7,7,7,7,7,7,7,7,7,4]),
  ([11,7,7,7,7,7,7,7,7,7,7,6,6], [11,7,7,7,7,7,7,7,7,7,7,6,6]),
  ([11,7,7,7,7,7,7,7,7,7,7,6,6], [11,7,7,7,7,7,7,7,7,7,7,7,5]),
  ([11,7,7,7,7,7,7,7,7,7,7,6,6], [11,8,7,7,7,7,7,7,7,7,6,6,6]),
  ([11,7,7,7,7,7,7,7,7,7,7,6,6], [11,8,7,7,7,7,7,7,7,7,7,6,5]),
  ([11,7,7,7,7,7,7,7,7,7,7,7,5], [8,8,7,7,7,7,7,7,7,7,7,7,7]),
  ([11,7,7,7,7,7,7,7,7,7,7,7,5], [8,8,8,7,7,7,7,7,7,7,7,7,6]),
  ([11,7,7,7,7,7,7,7,7,7,7,7,5], [8,8,8,8,7,7,7,7,7,7,7,6,6]),
  ([11,7,7,7,7,7,7,7,7,7,7,7,5], [8,8,8,8,7,7,7,7,7,7,7,7,5]),
  ([11,7,7,7,7,7,7,7,7,7,7,7,5], [8,8,8,8,8,7,7,7,7,7,6,6,6]),
  ([11,7,7,7,7,7,7,7,7,7,7,7,5], [8,8,8,8,8,7,7,7,7,7,7,6,5]),
  ([11,7,7,7,7,7,7,7,7,7,7,7,5], [8,8,8,8,8,7,7,7,7,7,7,7,4]),
  ([11,7,7,7,7,7,7,7,7,7,7,7,5], [9,7,7,7,7,7,7,7,7,7,7,7,7]),
  ([11,7,7,7,7,7,7,7,7,7,7,7,5], [9,8,7,7,7,7,7,7,7,7,7,7,6]),
  ([11,7,7,7,7,7,7,7,7,7,7,7,5], [9,8,8,7,7,7,7,7,7,7,7,6,6]),
  ([11,7,7,7,7,7,7,7,7,7,7,7,5], [9,8,8,7,7,7,7,7,7,7,7,7,5]),
  ([11,7,7,7,7,7,7,7,7,7,7,7,5], [9,8,8,8,7,7,7,7,7,7,6,6,6]),
  ([11,7,7,7,7,7,7,7,7,7,7,7,5], [9,8,8,8,7,7,7,7,7,7,7,6,5]),
  ([11,7,7,7,7,7,7,7,7,7,7,7,5], [9,8,8,8,7,7,7,7,7,7,7,7,4]),
  ([11,7,7,7,7,7,7,7,7,7,7,7,5], [9,9,7,7,7,7,7,7,7,7,7,6,6]),
  ([11,7,7,7,7,7,7,7,7,7,7,7,5], [9,9,7,7,7,7,7,7,7,7,7,7,5]),
  ([11,7,7,7,7,7,7,7,7,7,7,7,5], [9,9,8,7,7,7,7,7,7,7,6,6,6]),
  ([11,7,7,7,7,7,7,7,7,7,7,7,5], [9,9,8,7,7,7,7,7,7,7,7,6,5]),
  ([11,7,7,7,7,7,7,7,7,7,7,7,5], [9,9,8,7,7,7,7,7,7,7,7,7,4]),
  ([11,7,7,7,7,7,7,7,7,7,7,7,5], [10,7,7,7,7,7,7,7,7,7,7,7,6]),
  ([11,7,7,7,7,7,7,7,7,7,7,7,5], [10,8,7,7,7,7,7,7,7,7,7,6,6]),
  ([11,7,7,7,7,7,7,7,7,7,7,7,5], [10,8,7,7,7,7,7,7,7,7,7,7,5]),
  ([11,7,7,7,7,7,7,7,7,7,7,7,5], [10,8,8,7,7,7,7,7,7,7,6,6,6]),
  ([11,7,7,7,7,7,7,7,7,7,7,7,5], [10,8,8,7,7,7,7,7,7,7,7,6,5]),
  ([11,7,7,7,7,7,7,7,7,7,7,7,5], [10,8,8,7,7,7,7,7,7,7,7,7,4]),
  ([11,7,7,7,7,7,7,7,7,7,7,7,5], [10,9,7,7,7,7,7,7,7,7,6,6,6]),
  ([11,7,7,7,7,7,7,7,7,7,7,7,5], [10,9,7,7,7,7,7,7,7,7,7,6,5]),
  ([11,7,7,7,7,7,7,7,7,7,7,7,5], [10,9,7,7,7,7,7,7,7,7,7,7,4]),
  ([11,7,7,7,7,7,7,7,7,7,7,7,5], [11,7,7,7,7,7,7,7,7,7,7,6,6]),
  ([11,7,7,7,7,7,7,7,7,7,7,7,5], [11,7,7,7,7,7,7,7,7,7,7,7,5]),
  ([11,7,7,7,7,7,7,7,7,7,7,7,5], [11,8,7,7,7,7,7,7,7,7,6,6,6]),
  ([11,7,7,7,7,7,7,7,7,7,7,7,5], [11,8,7,7,7,7,7,7,7,7,7,6,5]),
  ([11,8,7,7,7,7,7,7,7,7,6,6,6], [8,8,7,7,7,7,7,7,7,7,7,7,7]),
  ([11,8,7,7,7,7,7,7,7,7,6,6,6], [8,8,8,7,7,7,7,7,7,7,7,7,6]),
  ([11,8,7,7,7,7,7,7,7,7,6,6,6], [8,8,8,8,7,7,7,7,7,7,7,6,6]),
  ([11,8,7,7,7,7,7,7,7,7,6,6,6], [8,8,8,8,7,7,7,7,7,7,7,7,5]),
  ([11,8,7,7,7,7,7,7,7,7,6,6,6], [8,8,8,8,8,7,7,7,7,7,6,6,6]),
  ([11,8,7,7,7,7,7,7,7,7,6,6,6], [8,8,8,8,8,7,7,7,7,7,7,6,5]),
  ([11,8,7,7,7,7,7,7,7,7,6,6,6], [8,8,8,8,8,7,7,7,7,7,7,7,4]),
  ([11,8,7,7,7,7,7,7,7,7,6,6,6], [9,7,7,7,7,7,7,7,7,7,7,7,7]),
  ([11,8,7,7,7,7,7,7,7,7,6,6,6], [9,8,7,7,7,7,7,7,7,7,7,7,6]),
  ([11,8,7,7,7,7,7,7,7,7,6,6,6], [9,8,8,7,7,7,7,7,7,7,7,6,6]),
  ([11,8,7,7,7,7,7,7,7,7,6,6,6], [9,8,8,7,7,7,7,7,7,7,7,7,5]),
  ([11,8,7,7,7,7,7,7,7,7,6,6,6], [9,8,8,8,7,7,7,7,7,7,6,6,6]),
  ([11,8,7,7,7,7,7,7,7,7,6,6,6], [9,8,8,8,7,7,7,7,7,7,7,6,5]),
  ([11,8,7,7,7,7,7,7,7,7,6,6,6], [9,8,8,8,7,7,7,7,7,7,7,7,4]),
  ([11,8,7,7,7,7,7,7,7,7,6,6,6], [9,9,7,7,7,7,7,7,7,7,7,6,6]),
  ([11,8,7,7,7,7,7,7,7,7,6,6,6], [9,9,7,7,7,7,7,7,7,7,7,7,5]),
  ([11,8,7,7,7,7,7,7,7,7,6,6,6], [9,9,8,7,7,7,7,7,7,7,6,6,6]),
  ([11,8,7,7,7,7,7,7,7,7,6,6,6], [9,9,8,7,7,7,7,7,7,7,7,6,5]),
  ([11,8,7,7,7,7,7,7,7,7,6,6,6], [9,9,8,7,7,7,7,7,7,7,7,7,4]),
  ([11,8,7,7,7,7,7,7,7,7,6,6,6], [10,7,7,7,7,7,7,7,7,7,7,7,6]),
  ([11,8,7,7,7,7,7,7,7,7,6,6,6], [10,8,7,7,7,7,7,7,7,7,7,6,6]),
  ([11,8,7,7,7,7,7,7,7,7,6,6,6], [10,8,7,7,7,7,7,7,7,7,7,7,5]),
  ([11,8,7,7,7,7,7,7,7,7,6,6,6], [10,8,8,7,7,7,7,7,7,7,6,6,6]),
  ([11,8,7,7,7,7,7,7,7,7,6,6,6], [10,8,8,7,7,7,7,7,7,7,7,6,5]),
  ([11,8,7,7,7,7,7,7,7,7,6,6,6], [10,8,8,7,7,7,7,7,7,7,7,7,4]),
  ([11,8,7,7,7,7,7,7,7,7,6,6,6], [10,9,7,7,7,7,7,7,7,7,6,6,6]),
  ([11,8,7,7,7,7,7,7,7,7,6,6,6], [10,9,7,7,7,7,7,7,7,7,7,6,5]),
  ([11,8,7,7,7,7,7,7,7,7,6,6,6], [10,9,7,7,7,7,7,7,7,7,7,7,4]),
  ([11,8,7,7,7,7,7,7,7,7,6,6,6], [11,7,7,7,7,7,7,7,7,7,7,6,6]),
  ([11,8,7,7,7,7,7,7,7,7,6,6,6], [11,7,7,7,7,7,7,7,7,7,7,7,5]),
  ([11,8,7,7,7,7,7,7,7,7,6,6,6], [11,8,7,7,7,7,7,7,7,7,6,6,6]),
  ([11,8,7,7,7,7,7,7,7,7,6,6,6], [11,8,7,7,7,7,7,7,7,7,7,6,5]),
  ([11,8,7,7,7,7,7,7,7,7,7,6,5], [8,8,7,7,7,7,7,7,7,7,7,7,7]),
  ([11,8,7,7,7,7,7,7,7,7,7,6,5], [8,8,8,7,7,7,7,7,7,7,7,7,6]),
  ([11,8,7,7,7,7,7,7,7,7,7,6,5], [8,8,8,8,7,7,7,7,7,7,7,6,6]),
  ([11,8,7,7,7,7,7,7,7,7,7,6,5], [8,8,8,8,7,7,7,7,7,7,7,7,5]),
  ([11,8,7,7,7,7,7,7,7,7,7,6,5], [8,8,8,8,8,7,7,7,7,7,6,6,6]),
  ([11,8,7,7,7,7,7,7,7,7,7,6,5], [8,8,8,8,8,7,7,7,7,7,7,6,5]),
  ([11,8,7,7,7,7,7,7,7,7,7,6,5], [8,8,8,8,8,7,7,7,7,7,7,7,4]),
  ([11,8,7,7,7,7,7,7,7,7,7,6,5], [9,7,7,7,7,7,7,7,7,7,7,7,7]),
  ([11,8,7,7,7,7,7,7,7,7,7,6,5], [9,8,7,7,7,7,7,7,7,7,7,7,6]),
  ([11,8,7,7,7,7,7,7,7,7,7,6,5], [9,8,8,7,7,7,7,7,7,7,7,6,6]),
  ([11,8,7,7,7,7,7,7,7,7,7,6,5], [9,8,8,7,7,7,7,7,7,7,7,7,5]),
  ([11,8,7,7,7,7,7,7,7,7,7,6,5], [9,8,8,8,7,7,7,7,7,7,6,6,6]),
  ([11,8,7,7,7,7,7,7,7,7,7,6,5], [9,8,8,8,7,7,7,7,7,7,7,6,5]),
  ([11,8,7,7,7,7,7,7,7,7,7,6,5], [9,8,8,8,7,7,7,7,7,7,7,7,4]),
  ([11,8,7,7,7,7,7,7,7,7,7,6,5], [9,9,7,7,7,7,7,7,7,7,7,6,6]),
  ([11,8,7,7,7,7,7,7,7,7,7,6,5], [9,9,7,7,7,7,7,7,7,7,7,7,5]),
  ([11,8,7,7,7,7,7,7,7,7,7,6,5], [9,9,8,7,7,7,7,7,7,7,6,6,6]),
  ([11,8,7,7,7,7,7,7,7,7,7,6,5], [9,9,8,7,7,7,7,7,7,7,7,6,5]),
  ([11,8,7,7,7,7,7,7,7,7,7,6,5], [9,9,8,7,7,7,7,7,7,7,7,7,4]),
  ([11,8,7,7,7,7,7,7,7,7,7,6,5], [10,7,7,7,7,7,7,7,7,7,7,7,6]),
  ([11,8,7,7,7,7,7,7,7,7,7,6,5], [10,8,7,7,7,7,7,7,7,7,7,6,6]),
  ([11,8,7,7,7,7,7,7,7,7,7,6,5], [10,8,7,7,7,7,7,7,7,7,7,7,5]),
  ([11,8,7,7,7,7,7,7,7,7,7,6,5], [10,8,8,7,7,7,7,7,7,7,6,6,6]),
  ([11,8,7,7,7,7,7,7,7,7,7,6,5], [10,8,8,7,7,7,7,7,7,7,7,6,5]),
  ([11,8,7,7,7,7,7,7,7,7,7,6,5], [10,8,8,7,7,7,7,7,7,7,7,7,4]),
  ([11,8,7,7,7,7,7,7,7,7,7,6,5], [10,9,7,7,7,7,7,7,7,7,6,6,6]),
  ([11,8,7,7,7,7,7,7,7,7,7,6,5], [10,9,7,7,7,7,7,7,7,7,7,6,5]),
  ([11,8,7,7,7,7,7,7,7,7,7,6,5], [10,9,7,7,7,7,7,7,7,7,7,7,4]),
  ([11,8,7,7,7,7,7,7,7,7,7,6,5], [11,7,7,7,7,7,7,7,7,7,7,6,6]),
  ([11,8,7,7,7,7,7,7,7,7,7,6,5], [11,7,7,7,7,7,7,7,7,7,7,7,5]),
  ([11,8,7,7,7,7,7,7,7,7,7,6,5], [11,8,7,7,7,7,7,7,7,7,6,6,6]),
  ([11,8,7,7,7,7,7,7,7,7,7,6,5], [11,8,7,7,7,7,7,7,7,7,7,6,5])]
def schema13 : ZarPrune.Prune T13 := ZarPrune.Prune.ofFarkas T13 [[0,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,2,2,2,2,1,1,1,1,1,1,1,1,2,2,2,1,1,1,1,1,1,1,1,2,2,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1], [0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1]]
#eval (cases13.map fun p => schema13.kill (pfOf 13 13 p.1 p.2)).countP (· == true)
#eval IO.println (String.intercalate "," ((cases13.map fun p => if schema13.kill (pfOf 13 13 p.1 p.2) then "1" else "0")))
