"""[GOLDEN CANDIDATE `native_decide` -- tests/golden.json] `native_decide` inside the proof (would add the `Lean.ofReduceBool` axiom / trust the compiler) -> L0, score 0.

Generated by tests/candidates/_gen.py from initial_program.py; do not edit by hand.

Prune library for the Zarankiewicz upper-bound search: prove z(m,n;s,t) < w by a case split.

A CASE is (rows, cols): non-increasing vectors, len(rows)=m (entries<=n), len(cols)=n (entries<=m),
sum(rows)=sum(cols)=w.  Every case must be EMPTY: killed by a Lean-verified prune or refuted by a SAT
solver with a checked certificate.  You evolve the prunes.

CONTRACT.  kill(...) may return True ONLY if no K_{s,t}-free m x n 0/1 matrix has exactly these sums.
Symmetry breaking ("assume sorted", "transpose") is NOT a prune.  Killing a realizable case scores 0.

WHAT EARNS CREDIT.  Only the Lean-evaluated kill of `candidate` (plus the harness-instantiated schemas
from SCHEMA_DATA).  Credit = the SAT work (solver conflicts above the first 20,000 per case) of the cases
that SURVIVE the already-proved library `ZarPrune.counting` (Arguments A, D both sides; deletion with the
waterfilled counting bound) that you kill, averaged within shape families (square / wide / very wide) over
training and target cells, plus a depth bonus (your best cell) and a closure bonus (every survivor of a
cell killed).  Re-proving those earns nothing.  A verified candidate that kills nothing scores 0.20;
no unverified candidate can exceed 0.19.  Artifacts list the hardest surviving cases, Lean errors with
goals, unfilled `have` holes, and the score breakdown.

LEAN API (generated by `python -m zar_ub api --docstring initial_program.py` from lean/ZarPrune; lean/API.md has every signature;
  Mathlib IS available through `import ZarPrune`):
  Basic:    Params Mat ind ind_le_one rowSum colSum weight rowSum_le colSum_le weight_eq_sum_colSum Incr
            HasKst Valid Profile profileOf profileOf_row profileOf_col
  Sum:      sumFin allFin sumFin_succ allFin_succ sumFin_congr sumFin_const_zero sumFin_add sumFin_swap
            sumFin_le allFin_iff not_allFin_elim
  Prune:    Prune never or ofList skip upper_bound_of_cover upper_bound_succ_of_cover ZarPrune.Prune.mono
  Prunes:   deficit mismatch rowCap colCap baseline
  Counting: sumFin_eq_sum rowSum_eq_sum colSum_eq_sum weight_eq_sum sumFin_succAbove support rowSupport
            mem_support mem_rowSupport card_support card_rowSupport incr_of_strictMono hasKst_of_subsets
            card_powersetCard_eq_sum budget_general colBudget rowLocalBudget Params.transpose transpose
            Profile.swap rowSum_transpose colSum_transpose weight_transpose profileOf_transpose
            hasKst_transpose valid_transpose Prune.transposed rowBudget argA argAT fD gD cntLt boundD fD_mono
            fD_layer_cake sum_range_eq_sum_ite fD_layer_cake_le sum_fD_eq card_filter_ge boundD_le argD argDT
            deleteCol deleteRow colSum_deleteCol rowSum_deleteRow weight_deleteCol weight_deleteRow
            Incr.succAbove_comp hasKst_of_deleteCol not_hasKst_deleteCol hasKst_of_deleteRow
            not_hasKst_deleteRow choose_tangent equalCost equalCost_le_sum_choose waterfillBound
            sum_le_waterfillBound colBudgetOf weight_le_waterfill valid_deleteCol_bound valid_deleteRow_bound
            argDelCol argDelRow argDelColWF argDelRowWF argWF countingA countingD deletion counting
  Cond:     Fact FactHolds Fact.transpose factHolds_transpose FactHolds.ofBound factHolds_waterfill CondPrune
            discharge ofPrune weaken restate never or orSame ofList transposed argDelColF argDelRowF topIdx
            topSum topIdx_nodup topIdx_length minorCols colSum_minorCols weight_minorCols not_hasKst_minorCols
            sum_orderEmbOfFin Prune.ofPrefixF Prune.ofPrefixRowF
  Schemas:  cntGt lowSum topSumF layer_cake layer_cake_le sum_f_eq card_filter_ge_of_set lowSum_le le_topSumF
            codeg codeg_comm codeg_le_left codeg_le_right codeg_le_n floor_le_codeg codeg_eq_sum sum_codeg_row
            sum_sum_codeg sum_sum_codeg_choose pairLocalBudget f2 f2_mono f3 f3_mono budget3 Lcap cap floor T2
            codeg_le_cap pairIdx Mult decode coef coefOK Sys sysOf rhs certKills arrayGetD_ofFn coefOK_iff
            farkas_sound Prune.ofFarkas
  DGH:      subsetLocalBudget dgh_round sum_powersetCard_filter dghD dghR dghCoef dghQuot dghBudget
            dghViolated argDGHCol argDGHRow argDGH
  Valid P A := ¬ HasKst P A ∧ P.w ≤ weight A  (so hv.1 : ¬ HasKst P A, hv.2 : P.w ≤ weight A); profileOf_row / profileOf_col are @[simp]
  Key statements:
    colBudget (P : Params) (A : Mat P.m P.n) (h : ¬ HasKst P A) : ∑ j, (colSum A j).choose P.s ≤ (P.t - 1) * (P.m).choose P.s
    rowBudget (P : Params) (A : Mat P.m P.n) (h : ¬ HasKst P A) : ∑ i, (rowSum A i).choose P.t ≤ (P.s - 1) * (P.n).choose P.t
    rowLocalBudget (P : Params) (A : Mat P.m P.n) (h : ¬ HasKst P A) (i : Fin P.m) (hs : 1 ≤ P.s) : ∑ j ∈ rowSupport A i, (colSum A j - 1).choose (P.s - 1) ≤ (P.t - 1) * (P.m - 1).choose (P.s - 1)
    valid_deleteCol_bound {m n s t w U : ℕ} (A : Mat m (n + 1)) (j : Fin (n + 1)) (hU : ∀ B : Mat m n, ¬ HasKst ⟨m, n, s, t, 0⟩ B → weight B ≤ U) (hj : colSum A j + U < w) : ¬ Valid ⟨m, n + 1, s, t, w⟩ A
    sum_le_waterfillBound {n : ℕ} (m s B : ℕ) (hs : 1 ≤ s) (c : Fin n → ℕ) (hc : ∀ j, c j ≤ m) (hB : ∑ j, (c j).choose s ≤ B) : ∑ j, c j ≤ waterfillBound m n s B
    argDelCol (P : Params) (U : ℕ) (hU : ∀ B : Mat P.m (P.n - 1), ¬ HasKst ⟨P.m, P.n - 1, P.s, P.t, 0⟩ B → weight B ≤ U) : Prune P
    argDelColF (P : Params) (f : Fact) (h : f.m = P.m ∧ f.n + 1 = P.n ∧ f.s = P.s ∧ f.t = P.t) : CondPrune P [f]
    Prune.ofPrefixF (P : Params) (k : Nat) (f : Fact) (hk : k < P.n) (h : f.m = P.m ∧ f.n = k ∧ f.s = P.s ∧ f.t = P.t) : CondPrune P [f]
    discharge {facts : List Fact} (q : CondPrune P facts) (h : ∀ f ∈ facts, FactHolds f) : Prune P
    ZarPrune.Prune.mono {P : ZarPrune.Params} (p : ZarPrune.Prune P) (w' : Nat) (h : P.w ≤ w') : ZarPrune.Prune {P with w := w'}
    pairLocalBudget (P : Params) (A : Mat P.m P.n) (h : ¬ HasKst P A) (i i' : Fin P.m) (hii : i ≠ i') (hs : 2 ≤ P.s) : ∑ j ∈ rowSupport A i ∩ rowSupport A i', (colSum A j - 2).choose (P.s - 2) ≤ (P.t - 1) * (P.m - 2).choose (P.s - 2)
    codeg_le_cap (P : Params) (A : Mat P.m P.n) (h : ¬ HasKst P A) (i i' : Fin P.m) (hii : i ≠ i') (hs : 2 ≤ P.s) : codeg A i i' ≤ cap P (profileOf A) i i'
    floor_le_codeg {m n : ℕ} (A : Mat m n) (i i' : Fin m) : rowSum A i + rowSum A i' - n ≤ codeg A i i'
    sum_codeg_row {m n : ℕ} (A : Mat m n) (i : Fin m) : ∑ i' ∈ univ.erase i, codeg A i i' = ∑ j ∈ rowSupport A i, (colSum A j - 1)
    lowSum_le (f : ℕ → ℕ) (hf : Monotone f) {m n : ℕ} (pf : Profile m n) (hc : ∀ j, pf.col j ≤ m) (S : Finset (Fin n)) : lowSum f pf S.card ≤ ∑ j ∈ S, f (pf.col j)
    Prune.ofFarkas (P : Params) (ys : List (List ℕ)) : Prune P
    dghBudget (P : Params) (A : Mat P.m P.n) (h : ¬ HasKst P A) (hs : 1 ≤ P.s) (k : ℕ) (hk : P.s ≤ k) : dghCoef P.m P.s P.t k * ∑ j, (colSum A j).choose (P.s - 1) ≤ dghCoef P.m P.s P.t k * dghQuot P.m P.s P.t k * P.m.choose (P.s - 1) + ∑ j, (k - colSum A j) * (colSum A j).choose (P.s - 1)
    argDGH (P : Params) : Prune P
  Mathlib: Finset.sum_le_sum sum_comm card_filter powersetCard, Nat.choose lemmas, omega decide simp linarith nlinarith ring positivity
  Schemas (Schemas.lean, proved): `Prune.ofFarkas P ys` kills when some certificate y in ys refutes the pair-codegree system F1-F4 (see SCHEMA_DATA["farkas"]); `Prune.ofResidue` is NOT in the library (SCHEMA_DATA["residue"] / ["prefix"] must stay []).
  DGH (DGH.lean, proved for every (m,n;s,t)): `argDGH P` = the Davies-Gill-Horsley v = s-1 rounding inequality on both sides; it is a library lemma but NOT in the scoring baseline, so listing it earns credit only on the wide cells where it fires.
  Closure.lean / Evolved.lean: the closure seam (upper_bound_succ_of_condPrune) and the promoted library `evolved P` (already in the baseline); not for candidates.
  CondPrune entry point: besides `candidate` you may define `candidateF (P : Params) (facts : List Fact) : CondPrune P facts` (general) or `candidateF : CondPrune target [f1, ...]` (literal facts); the gate discharges it against the facts the run's ledger grants to each instance (none on pure/TRAIN tables; Tan's cited neighbours on tan2022 target tables) and falls back to `CondPrune.never` where a literal fact is not granted (artifact lean_cond).
Pattern for a new prune (this is `argA` from lean/ZarPrune/Counting.lean, verbatim):
  def argA (P : Params) : Prune P where
    name := "argA: Σ_j C(c_j,s) ≤ (t-1)C(m,s)"
    kill := fun pf =>
      decide ((P.t - 1) * (P.m).choose P.s < sumFin P.n (fun j => (pf.col j).choose P.s))
    sound := by
      intro A hk hv            -- hk : kill (profileOf A) = true ; hv : Valid P A (hv.1 : ¬HasKst, hv.2 : w ≤ weight A)
      have h1 : (P.t - 1) * (P.m).choose P.s < sumFin P.n (fun j => (colSum A j).choose P.s) :=
        of_decide_eq_true hk
      rw [sumFin_eq_sum] at h1
      have h2 := colBudget P A hv.1
      omega
FORBIDDEN: import; sorry anywhere outside a `sound := by` block (typed `have h : T := by sorry` holes are auto-filled; a bare sorry inside sound = untyped hole, ladder ≤ L2); axiom; native_decide;
  unsafe; partial; implemented_by; extern; csimp; opaque; noncomputable; macro/syntax/elab/notation;
  every `#` command; IO; Lean.*; set_option other than maxHeartbeats/maxRecDepth; end Cand/ZarPrune;
  redefining Valid/HasKst/Params/Profile/Mat/weight/rowSum/colSum/Prune/CondPrune/counting.
  The scan also reads COMMENTS and STRINGS: never write a forbidden word (partial, axiom, IO, trace, syntax,
  notation, namespace, ...) even in a comment.  Write `s.card`, never `#s`.  The wrapper sets
  `set_option autoImplicit false`: declare every variable.  Holes: typed `have h : T := by sorry` (auto-filled) or a bare sorry inside sound (untyped, L2 cap).
"""
from math import comb

# EVOLVE-BLOCK-START
NOTES = r"""Start: the proved counting library only."""

LEAN_SOURCE = r'''
def candidate (P : Params) : Prune P where
  name := "native"
  kill := fun pf => decide (sumFin P.m pf.row < P.w)
  sound := by
    intro A h hv
    have h1 : sumFin P.m (rowSum A) < P.w := by native_decide
    have h2 : P.w ≤ sumFin P.m (rowSum A) := hv.2
    omega
'''

SCHEMA_DATA = {"farkas": [], "residue": [], "prefix": []}


def kill(m, n, s, t, w, rows, cols):
    """Python mirror of candidate.kill (library part mirrors ZarPrune.counting)."""
    if sum(comb(c, s) for c in cols) > (t - 1) * comb(m, s):
        return True                                                   # argA
    if sum(comb(r, t) for r in rows) > (s - 1) * comb(n, t):
        return True                                                   # argAT
    r0, c0 = rows[0], cols[0]
    if r0 and sum(comb(c - 1, s - 1) for c in sorted(cols)[:r0] if c) > (t - 1) * comb(m - 1, s - 1):
        return True                                                   # argD
    if c0 and sum(comb(r - 1, t - 1) for r in sorted(rows)[:c0] if r) > (s - 1) * comb(n - 1, t - 1):
        return True                                                   # argDT
    return False                                                      # your prunes go above
# EVOLVE-BLOCK-END

if __name__ == "__main__":
    print(kill(9, 9, 3, 3, 50, (6, 6, 6, 6, 6, 5, 5, 5, 5), (6, 6, 6, 6, 6, 5, 5, 5, 5)))
