import ZarPrune
import ZarPrune.Closure

set_option autoImplicit false
set_option maxRecDepth 8192

/-! Generated by `zar_ub/closure.py` on 2026-09-22 00:09: z(10,21;3,3) <= 106, tier 1.  Do not edit. -/

namespace ZarPrune.Closures.Z_10_21_107
open ZarPrune

abbrev P : Params := ⟨10, 21, 3, 3, 107⟩

/-! Counting facts (waterfilled Argument A), proved here. -/
abbrev G1 : Fact := ⟨3, 21, 3, 3, 44, "lean-here"⟩
theorem G1_holds : FactHolds G1 := factHolds_of_waterfill_le 3 21 3 3 44 "lean-here" (by decide) (by decide +kernel)
abbrev G2 : Fact := ⟨4, 21, 3, 3, 50, "lean-here"⟩
theorem G2_holds : FactHolds G2 := factHolds_of_waterfill_le 4 21 3 3 50 "lean-here" (by decide) (by decide +kernel)
abbrev G3 : Fact := ⟨5, 21, 3, 3, 62, "lean-here"⟩
theorem G3_holds : FactHolds G3 := factHolds_of_waterfill_le 5 21 3 3 62 "lean-here" (by decide) (by decide +kernel)
abbrev G4 : Fact := ⟨6, 21, 3, 3, 69, "lean-here"⟩
theorem G4_holds : FactHolds G4 := factHolds_of_waterfill_le 6 21 3 3 69 "lean-here" (by decide) (by decide +kernel)
abbrev G5 : Fact := ⟨7, 21, 3, 3, 79, "lean-here"⟩
theorem G5_holds : FactHolds G5 := factHolds_of_waterfill_le 7 21 3 3 79 "lean-here" (by decide) (by decide +kernel)
abbrev G6 : Fact := ⟨8, 21, 3, 3, 88, "lean-here"⟩
theorem G6_holds : FactHolds G6 := factHolds_of_waterfill_le 8 21 3 3 88 "lean-here" (by decide) (by decide +kernel)
abbrev G7 : Fact := ⟨9, 21, 3, 3, 98, "lean-here"⟩
theorem G7_holds : FactHolds G7 := factHolds_of_waterfill_le 9 21 3 3 98 "lean-here" (by decide) (by decide +kernel)
abbrev G8 : Fact := ⟨10, 3, 3, 3, 22, "lean-here"⟩
theorem G8_holds : FactHolds G8 := factHolds_of_waterfillT_le 10 3 3 3 22 "lean-here" (by decide) (by decide +kernel)
abbrev G9 : Fact := ⟨10, 4, 3, 3, 28, "lean-here"⟩
theorem G9_holds : FactHolds G9 := factHolds_of_waterfillT_le 10 4 3 3 28 "lean-here" (by decide) (by decide +kernel)
abbrev G10 : Fact := ⟨10, 5, 3, 3, 33, "lean-here"⟩
theorem G10_holds : FactHolds G10 := factHolds_of_waterfillT_le 10 5 3 3 33 "lean-here" (by decide) (by decide +kernel)
abbrev G11 : Fact := ⟨10, 6, 3, 3, 40, "lean-here"⟩
theorem G11_holds : FactHolds G11 := factHolds_of_waterfillT_le 10 6 3 3 40 "lean-here" (by decide) (by decide +kernel)
abbrev G12 : Fact := ⟨10, 7, 3, 3, 45, "lean-here"⟩
theorem G12_holds : FactHolds G12 := factHolds_of_waterfillT_le 10 7 3 3 45 "lean-here" (by decide) (by decide +kernel)
abbrev G13 : Fact := ⟨10, 8, 3, 3, 51, "lean-here"⟩
theorem G13_holds : FactHolds G13 := factHolds_of_waterfillT_le 10 8 3 3 51 "lean-here" (by decide) (by decide +kernel)
abbrev G14 : Fact := ⟨10, 9, 3, 3, 56, "lean-here"⟩
theorem G14_holds : FactHolds G14 := factHolds_of_waterfillT_le 10 9 3 3 56 "lean-here" (by decide) (by decide +kernel)
abbrev G15 : Fact := ⟨10, 10, 3, 3, 62, "lean-here"⟩
theorem G15_holds : FactHolds G15 := factHolds_of_waterfill_le 10 10 3 3 62 "lean-here" (by decide) (by decide +kernel)
abbrev G16 : Fact := ⟨10, 11, 3, 3, 67, "lean-here"⟩
theorem G16_holds : FactHolds G16 := factHolds_of_waterfill_le 10 11 3 3 67 "lean-here" (by decide) (by decide +kernel)
abbrev G17 : Fact := ⟨10, 12, 3, 3, 72, "lean-here"⟩
theorem G17_holds : FactHolds G17 := factHolds_of_waterfill_le 10 12 3 3 72 "lean-here" (by decide) (by decide +kernel)
abbrev G18 : Fact := ⟨10, 13, 3, 3, 76, "lean-here"⟩
theorem G18_holds : FactHolds G18 := factHolds_of_waterfill_le 10 13 3 3 76 "lean-here" (by decide) (by decide +kernel)
abbrev G19 : Fact := ⟨10, 14, 3, 3, 80, "lean-here"⟩
theorem G19_holds : FactHolds G19 := factHolds_of_waterfill_le 10 14 3 3 80 "lean-here" (by decide) (by decide +kernel)
abbrev G20 : Fact := ⟨10, 15, 3, 3, 84, "lean-here"⟩
theorem G20_holds : FactHolds G20 := factHolds_of_waterfill_le 10 15 3 3 84 "lean-here" (by decide) (by decide +kernel)
abbrev G21 : Fact := ⟨10, 16, 3, 3, 88, "lean-here"⟩
theorem G21_holds : FactHolds G21 := factHolds_of_waterfill_le 10 16 3 3 88 "lean-here" (by decide) (by decide +kernel)
abbrev G22 : Fact := ⟨10, 17, 3, 3, 92, "lean-here"⟩
theorem G22_holds : FactHolds G22 := factHolds_of_waterfill_le 10 17 3 3 92 "lean-here" (by decide) (by decide +kernel)
abbrev G23 : Fact := ⟨10, 18, 3, 3, 96, "lean-here"⟩
theorem G23_holds : FactHolds G23 := factHolds_of_waterfill_le 10 18 3 3 96 "lean-here" (by decide) (by decide +kernel)
abbrev G24 : Fact := ⟨10, 19, 3, 3, 100, "lean-here"⟩
theorem G24_holds : FactHolds G24 := factHolds_of_waterfill_le 10 19 3 3 100 "lean-here" (by decide) (by decide +kernel)
abbrev G25 : Fact := ⟨10, 20, 3, 3, 104, "lean-here"⟩
theorem G25_holds : FactHolds G25 := factHolds_of_waterfill_le 10 20 3 3 104 "lean-here" (by decide) (by decide +kernel)

/-! External facts (hypotheses of the closure theorem), one per Fact. -/
abbrev F1 : Fact := ⟨7, 21, 3, 3, 78, "tan2022"⟩
abbrev F2 : Fact := ⟨8, 21, 3, 3, 87, "tan2022"⟩
abbrev F3 : Fact := ⟨9, 21, 3, 3, 96, "tan2022"⟩
abbrev F4 : Fact := ⟨10, 6, 3, 3, 39, "tan2022"⟩
abbrev F5 : Fact := ⟨10, 7, 3, 3, 44, "tan2022"⟩
abbrev F6 : Fact := ⟨10, 8, 3, 3, 50, "tan2022"⟩
abbrev F7 : Fact := ⟨10, 9, 3, 3, 54, "tan2022"⟩
abbrev F8 : Fact := ⟨10, 10, 3, 3, 60, "tan2022"⟩
abbrev F9 : Fact := ⟨10, 11, 3, 3, 64, "tan2022"⟩
abbrev F10 : Fact := ⟨10, 12, 3, 3, 68, "tan2022"⟩
abbrev F11 : Fact := ⟨10, 13, 3, 3, 73, "tan2022"⟩
abbrev F12 : Fact := ⟨10, 14, 3, 3, 77, "tan2022"⟩
abbrev F13 : Fact := ⟨10, 15, 3, 3, 81, "tan2022"⟩
abbrev F14 : Fact := ⟨10, 16, 3, 3, 85, "tan2022"⟩
abbrev F15 : Fact := ⟨10, 17, 3, 3, 90, "tan2022"⟩
abbrev F16 : Fact := ⟨10, 18, 3, 3, 94, "tan2022"⟩
abbrev F17 : Fact := ⟨10, 19, 3, 3, 98, "tan2022"⟩
abbrev F18 : Fact := ⟨10, 20, 3, 3, 102, "lean-here"⟩

abbrev facts : List Fact := [G1, G2, G3, G4, G5, G6, G7, G8, G9, G10, G11, G12, G13, G14, G15, G16, G17, G18, G19, G20, G21, G22, G23, G24, G25, F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, F11, F12, F13, F14, F15, F16, F17, F18]

/-- The prune: the proved library, as a `CondPrune` (closed `kill`). -/
def condPrune : CondPrune P facts :=
  CondPrune.ofList P facts [
    (CondPrune.ofPrune (Prune.or (Prune.or (baseline P) (counting P)) (evolved P))).weaken (fun _ hf => nomatch hf)
  ]

/-- The list the SAT solver refuted (0 cases). -/
def survList : List (List Nat × List Nat) := []

/-- The only per-instance kernel computation (Tier-1: `decide +kernel`). -/
theorem survivors_eq : survivorsK P facts condPrune.kill = survList := by decide +kernel

theorem factsHold
    (h1 : FactHolds F1)
    (h2 : FactHolds F2)
    (h3 : FactHolds F3)
    (h4 : FactHolds F4)
    (h5 : FactHolds F5)
    (h6 : FactHolds F6)
    (h7 : FactHolds F7)
    (h8 : FactHolds F8)
    (h9 : FactHolds F9)
    (h10 : FactHolds F10)
    (h11 : FactHolds F11)
    (h12 : FactHolds F12)
    (h13 : FactHolds F13)
    (h14 : FactHolds F14)
    (h15 : FactHolds F15)
    (h16 : FactHolds F16)
    (h17 : FactHolds F17)
    (h18 : FactHolds F18) :
    ∀ f ∈ facts, FactHolds f :=
  List.forall_mem_cons.mpr ⟨G1_holds,
    List.forall_mem_cons.mpr ⟨G2_holds,
      List.forall_mem_cons.mpr ⟨G3_holds,
        List.forall_mem_cons.mpr ⟨G4_holds,
          List.forall_mem_cons.mpr ⟨G5_holds,
            List.forall_mem_cons.mpr ⟨G6_holds,
              List.forall_mem_cons.mpr ⟨G7_holds,
                List.forall_mem_cons.mpr ⟨G8_holds,
                  List.forall_mem_cons.mpr ⟨G9_holds,
                    List.forall_mem_cons.mpr ⟨G10_holds,
                      List.forall_mem_cons.mpr ⟨G11_holds,
                        List.forall_mem_cons.mpr ⟨G12_holds,
                          List.forall_mem_cons.mpr ⟨G13_holds,
                            List.forall_mem_cons.mpr ⟨G14_holds,
                              List.forall_mem_cons.mpr ⟨G15_holds,
                                List.forall_mem_cons.mpr ⟨G16_holds,
                                  List.forall_mem_cons.mpr ⟨G17_holds,
                                    List.forall_mem_cons.mpr ⟨G18_holds,
                                      List.forall_mem_cons.mpr ⟨G19_holds,
                                        List.forall_mem_cons.mpr ⟨G20_holds,
                                          List.forall_mem_cons.mpr ⟨G21_holds,
                                            List.forall_mem_cons.mpr ⟨G22_holds,
                                              List.forall_mem_cons.mpr ⟨G23_holds,
                                                List.forall_mem_cons.mpr ⟨G24_holds,
                                                  List.forall_mem_cons.mpr ⟨G25_holds,
                                                    List.forall_mem_cons.mpr ⟨h1,
                                                      List.forall_mem_cons.mpr ⟨h2,
                                                        List.forall_mem_cons.mpr ⟨h3,
                                                          List.forall_mem_cons.mpr ⟨h4,
                                                            List.forall_mem_cons.mpr ⟨h5,
                                                              List.forall_mem_cons.mpr ⟨h6,
                                                                List.forall_mem_cons.mpr ⟨h7,
                                                                  List.forall_mem_cons.mpr ⟨h8,
                                                                    List.forall_mem_cons.mpr ⟨h9,
                                                                      List.forall_mem_cons.mpr ⟨h10,
                                                                        List.forall_mem_cons.mpr ⟨h11,
                                                                          List.forall_mem_cons.mpr ⟨h12,
                                                                            List.forall_mem_cons.mpr ⟨h13,
                                                                              List.forall_mem_cons.mpr ⟨h14,
                                                                                List.forall_mem_cons.mpr ⟨h15,
                                                                                  List.forall_mem_cons.mpr ⟨h16,
                                                                                    List.forall_mem_cons.mpr ⟨h17,
                                                                                      List.forall_mem_cons.mpr ⟨h18,
                                                                                        List.forall_mem_nil _⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩

/-- **z(10,21;3,3) ≤ 106**, conditional on the 18 external fact(s) `F1`…`F18`; no SAT case remains. -/
theorem z_10_21_le_106
    (h1 : FactHolds F1)
    (h2 : FactHolds F2)
    (h3 : FactHolds F3)
    (h4 : FactHolds F4)
    (h5 : FactHolds F5)
    (h6 : FactHolds F6)
    (h7 : FactHolds F7)
    (h8 : FactHolds F8)
    (h9 : FactHolds F9)
    (h10 : FactHolds F10)
    (h11 : FactHolds F11)
    (h12 : FactHolds F12)
    (h13 : FactHolds F13)
    (h14 : FactHolds F14)
    (h15 : FactHolds F15)
    (h16 : FactHolds F16)
    (h17 : FactHolds F17)
    (h18 : FactHolds F18) :
    ∀ A : Mat 10 21, ¬ HasKst P A → weight A ≤ 106 :=
  upper_bound_succ_of_condPrune P 106 rfl facts (factsHold h1 h2 h3 h4 h5 h6 h7 h8 h9 h10 h11 h12 h13 h14 h15 h16 h17 h18) condPrune survList survivors_eq (fun _ hq => nomatch hq)

#print axioms z_10_21_le_106

end ZarPrune.Closures.Z_10_21_107
