import ZarPrune
import ZarPrune.Closure

set_option autoImplicit false
set_option maxRecDepth 8192

/-! Generated by `zar_ub/closure.py` on 2026-09-21 23:42: z(11,20;3,3) <= 111, tier 1.  Do not edit. -/

namespace ZarPrune.Closures.Z_11_20_112
open ZarPrune

abbrev P : Params := ⟨11, 20, 3, 3, 112⟩

/-! Counting facts (waterfilled Argument A), proved here. -/
abbrev G1 : Fact := ⟨3, 20, 3, 3, 42, "lean-here"⟩
theorem G1_holds : FactHolds G1 := factHolds_of_waterfill_le 3 20 3 3 42 "lean-here" (by decide) (by decide +kernel)
abbrev G2 : Fact := ⟨4, 20, 3, 3, 48, "lean-here"⟩
theorem G2_holds : FactHolds G2 := factHolds_of_waterfill_le 4 20 3 3 48 "lean-here" (by decide) (by decide +kernel)
abbrev G3 : Fact := ⟨5, 20, 3, 3, 60, "lean-here"⟩
theorem G3_holds : FactHolds G3 := factHolds_of_waterfill_le 5 20 3 3 60 "lean-here" (by decide) (by decide +kernel)
abbrev G4 : Fact := ⟨6, 20, 3, 3, 66, "lean-here"⟩
theorem G4_holds : FactHolds G4 := factHolds_of_waterfill_le 6 20 3 3 66 "lean-here" (by decide) (by decide +kernel)
abbrev G5 : Fact := ⟨7, 20, 3, 3, 76, "lean-here"⟩
theorem G5_holds : FactHolds G5 := factHolds_of_waterfill_le 7 20 3 3 76 "lean-here" (by decide) (by decide +kernel)
abbrev G6 : Fact := ⟨8, 20, 3, 3, 85, "lean-here"⟩
theorem G6_holds : FactHolds G6 := factHolds_of_waterfill_le 8 20 3 3 85 "lean-here" (by decide) (by decide +kernel)
abbrev G7 : Fact := ⟨9, 20, 3, 3, 94, "lean-here"⟩
theorem G7_holds : FactHolds G7 := factHolds_of_waterfill_le 9 20 3 3 94 "lean-here" (by decide) (by decide +kernel)
abbrev G8 : Fact := ⟨10, 20, 3, 3, 104, "lean-here"⟩
theorem G8_holds : FactHolds G8 := factHolds_of_waterfill_le 10 20 3 3 104 "lean-here" (by decide) (by decide +kernel)
abbrev G9 : Fact := ⟨11, 3, 3, 3, 24, "lean-here"⟩
theorem G9_holds : FactHolds G9 := factHolds_of_waterfillT_le 11 3 3 3 24 "lean-here" (by decide) (by decide +kernel)
abbrev G10 : Fact := ⟨11, 4, 3, 3, 30, "lean-here"⟩
theorem G10_holds : FactHolds G10 := factHolds_of_waterfillT_le 11 4 3 3 30 "lean-here" (by decide) (by decide +kernel)
abbrev G11 : Fact := ⟨11, 5, 3, 3, 36, "lean-here"⟩
theorem G11_holds : FactHolds G11 := factHolds_of_waterfillT_le 11 5 3 3 36 "lean-here" (by decide) (by decide +kernel)
abbrev G12 : Fact := ⟨11, 6, 3, 3, 42, "lean-here"⟩
theorem G12_holds : FactHolds G12 := factHolds_of_waterfillT_le 11 6 3 3 42 "lean-here" (by decide) (by decide +kernel)
abbrev G13 : Fact := ⟨11, 7, 3, 3, 48, "lean-here"⟩
theorem G13_holds : FactHolds G13 := factHolds_of_waterfillT_le 11 7 3 3 48 "lean-here" (by decide) (by decide +kernel)
abbrev G14 : Fact := ⟨11, 8, 3, 3, 55, "lean-here"⟩
theorem G14_holds : FactHolds G14 := factHolds_of_waterfillT_le 11 8 3 3 55 "lean-here" (by decide) (by decide +kernel)
abbrev G15 : Fact := ⟨11, 9, 3, 3, 60, "lean-here"⟩
theorem G15_holds : FactHolds G15 := factHolds_of_waterfillT_le 11 9 3 3 60 "lean-here" (by decide) (by decide +kernel)
abbrev G16 : Fact := ⟨11, 10, 3, 3, 67, "lean-here"⟩
theorem G16_holds : FactHolds G16 := factHolds_of_waterfillT_le 11 10 3 3 67 "lean-here" (by decide) (by decide +kernel)
abbrev G17 : Fact := ⟨11, 11, 3, 3, 73, "lean-here"⟩
theorem G17_holds : FactHolds G17 := factHolds_of_waterfill_le 11 11 3 3 73 "lean-here" (by decide) (by decide +kernel)
abbrev G18 : Fact := ⟨11, 12, 3, 3, 78, "lean-here"⟩
theorem G18_holds : FactHolds G18 := factHolds_of_waterfill_le 11 12 3 3 78 "lean-here" (by decide) (by decide +kernel)
abbrev G19 : Fact := ⟨11, 13, 3, 3, 82, "lean-here"⟩
theorem G19_holds : FactHolds G19 := factHolds_of_waterfill_le 11 13 3 3 82 "lean-here" (by decide) (by decide +kernel)
abbrev G20 : Fact := ⟨11, 14, 3, 3, 87, "lean-here"⟩
theorem G20_holds : FactHolds G20 := factHolds_of_waterfill_le 11 14 3 3 87 "lean-here" (by decide) (by decide +kernel)
abbrev G21 : Fact := ⟨11, 15, 3, 3, 92, "lean-here"⟩
theorem G21_holds : FactHolds G21 := factHolds_of_waterfill_le 11 15 3 3 92 "lean-here" (by decide) (by decide +kernel)
abbrev G22 : Fact := ⟨11, 16, 3, 3, 96, "lean-here"⟩
theorem G22_holds : FactHolds G22 := factHolds_of_waterfill_le 11 16 3 3 96 "lean-here" (by decide) (by decide +kernel)
abbrev G23 : Fact := ⟨11, 17, 3, 3, 101, "lean-here"⟩
theorem G23_holds : FactHolds G23 := factHolds_of_waterfill_le 11 17 3 3 101 "lean-here" (by decide) (by decide +kernel)
abbrev G24 : Fact := ⟨11, 18, 3, 3, 105, "lean-here"⟩
theorem G24_holds : FactHolds G24 := factHolds_of_waterfill_le 11 18 3 3 105 "lean-here" (by decide) (by decide +kernel)
abbrev G25 : Fact := ⟨11, 19, 3, 3, 109, "lean-here"⟩
theorem G25_holds : FactHolds G25 := factHolds_of_waterfill_le 11 19 3 3 109 "lean-here" (by decide) (by decide +kernel)

/-! External facts (hypotheses of the closure theorem), one per Fact. -/
abbrev F1 : Fact := ⟨7, 20, 3, 3, 75, "tan2022"⟩
abbrev F2 : Fact := ⟨8, 20, 3, 3, 84, "tan2022"⟩
abbrev F3 : Fact := ⟨9, 20, 3, 3, 93, "tan2022"⟩
abbrev F4 : Fact := ⟨10, 20, 3, 3, 102, "lean-here"⟩
abbrev F5 : Fact := ⟨11, 7, 3, 3, 47, "tan2022"⟩
abbrev F6 : Fact := ⟨11, 8, 3, 3, 53, "tan2022"⟩
abbrev F7 : Fact := ⟨11, 9, 3, 3, 59, "tan2022"⟩
abbrev F8 : Fact := ⟨11, 10, 3, 3, 64, "tan2022"⟩
abbrev F9 : Fact := ⟨11, 11, 3, 3, 69, "tan2022"⟩
abbrev F10 : Fact := ⟨11, 12, 3, 3, 74, "tan2022"⟩
abbrev F11 : Fact := ⟨11, 13, 3, 3, 80, "tan2022"⟩
abbrev F12 : Fact := ⟨11, 14, 3, 3, 84, "tan2022"⟩
abbrev F13 : Fact := ⟨11, 15, 3, 3, 88, "tan2022"⟩
abbrev F14 : Fact := ⟨11, 16, 3, 3, 92, "tan2022"⟩
abbrev F15 : Fact := ⟨11, 17, 3, 3, 96, "tan2022"⟩
abbrev F16 : Fact := ⟨11, 18, 3, 3, 101, "tan2022"⟩

abbrev facts : List Fact := [G1, G2, G3, G4, G5, G6, G7, G8, G9, G10, G11, G12, G13, G14, G15, G16, G17, G18, G19, G20, G21, G22, G23, G24, G25, F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, F11, F12, F13, F14, F15, F16]

/-- The prune: the proved library, as a `CondPrune` (closed `kill`). -/
def condPrune : CondPrune P facts :=
  CondPrune.ofList P facts [
    (CondPrune.ofPrune (Prune.or (baseline P) (counting P))).weaken (fun _ hf => nomatch hf)
  ]

/-- The list the SAT solver refuted (0 cases). -/
def survList : List (List Nat × List Nat) := []

/-- The only per-instance kernel computation (Tier-1: `decide +kernel`). -/
theorem survivors_eq : survivorsK P facts condPrune.kill = survList := by decide +kernel

theorem factsHold
    (h1 : FactHolds F1)
    (h2 : FactHolds F2)
    (h3 : FactHolds F3)
    (h4 : FactHolds F4)
    (h5 : FactHolds F5)
    (h6 : FactHolds F6)
    (h7 : FactHolds F7)
    (h8 : FactHolds F8)
    (h9 : FactHolds F9)
    (h10 : FactHolds F10)
    (h11 : FactHolds F11)
    (h12 : FactHolds F12)
    (h13 : FactHolds F13)
    (h14 : FactHolds F14)
    (h15 : FactHolds F15)
    (h16 : FactHolds F16) :
    ∀ f ∈ facts, FactHolds f :=
  List.forall_mem_cons.mpr ⟨G1_holds,
    List.forall_mem_cons.mpr ⟨G2_holds,
      List.forall_mem_cons.mpr ⟨G3_holds,
        List.forall_mem_cons.mpr ⟨G4_holds,
          List.forall_mem_cons.mpr ⟨G5_holds,
            List.forall_mem_cons.mpr ⟨G6_holds,
              List.forall_mem_cons.mpr ⟨G7_holds,
                List.forall_mem_cons.mpr ⟨G8_holds,
                  List.forall_mem_cons.mpr ⟨G9_holds,
                    List.forall_mem_cons.mpr ⟨G10_holds,
                      List.forall_mem_cons.mpr ⟨G11_holds,
                        List.forall_mem_cons.mpr ⟨G12_holds,
                          List.forall_mem_cons.mpr ⟨G13_holds,
                            List.forall_mem_cons.mpr ⟨G14_holds,
                              List.forall_mem_cons.mpr ⟨G15_holds,
                                List.forall_mem_cons.mpr ⟨G16_holds,
                                  List.forall_mem_cons.mpr ⟨G17_holds,
                                    List.forall_mem_cons.mpr ⟨G18_holds,
                                      List.forall_mem_cons.mpr ⟨G19_holds,
                                        List.forall_mem_cons.mpr ⟨G20_holds,
                                          List.forall_mem_cons.mpr ⟨G21_holds,
                                            List.forall_mem_cons.mpr ⟨G22_holds,
                                              List.forall_mem_cons.mpr ⟨G23_holds,
                                                List.forall_mem_cons.mpr ⟨G24_holds,
                                                  List.forall_mem_cons.mpr ⟨G25_holds,
                                                    List.forall_mem_cons.mpr ⟨h1,
                                                      List.forall_mem_cons.mpr ⟨h2,
                                                        List.forall_mem_cons.mpr ⟨h3,
                                                          List.forall_mem_cons.mpr ⟨h4,
                                                            List.forall_mem_cons.mpr ⟨h5,
                                                              List.forall_mem_cons.mpr ⟨h6,
                                                                List.forall_mem_cons.mpr ⟨h7,
                                                                  List.forall_mem_cons.mpr ⟨h8,
                                                                    List.forall_mem_cons.mpr ⟨h9,
                                                                      List.forall_mem_cons.mpr ⟨h10,
                                                                        List.forall_mem_cons.mpr ⟨h11,
                                                                          List.forall_mem_cons.mpr ⟨h12,
                                                                            List.forall_mem_cons.mpr ⟨h13,
                                                                              List.forall_mem_cons.mpr ⟨h14,
                                                                                List.forall_mem_cons.mpr ⟨h15,
                                                                                  List.forall_mem_cons.mpr ⟨h16,
                                                                                    List.forall_mem_nil _⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩⟩

/-- **z(11,20;3,3) ≤ 111**, conditional on the 16 external fact(s) `F1`…`F16`; no SAT case remains. -/
theorem z_11_20_le_111
    (h1 : FactHolds F1)
    (h2 : FactHolds F2)
    (h3 : FactHolds F3)
    (h4 : FactHolds F4)
    (h5 : FactHolds F5)
    (h6 : FactHolds F6)
    (h7 : FactHolds F7)
    (h8 : FactHolds F8)
    (h9 : FactHolds F9)
    (h10 : FactHolds F10)
    (h11 : FactHolds F11)
    (h12 : FactHolds F12)
    (h13 : FactHolds F13)
    (h14 : FactHolds F14)
    (h15 : FactHolds F15)
    (h16 : FactHolds F16) :
    ∀ A : Mat 11 20, ¬ HasKst P A → weight A ≤ 111 :=
  upper_bound_succ_of_condPrune P 111 rfl facts (factsHold h1 h2 h3 h4 h5 h6 h7 h8 h9 h10 h11 h12 h13 h14 h15 h16) condPrune survList survivors_eq (fun _ hq => nomatch hq)

#print axioms z_11_20_le_111

end ZarPrune.Closures.Z_11_20_112
