import ZarPrune.Prune
import ZarPrune.Evolved.E_c285948723e7

/-!
The promoted library (GENERATED by zar_ub/promote.py from cache/ledger/accepted_prunes.jsonl;
do not edit).  `evolved P` is the OR of every accepted evolved prune; each one lives in its own
module lean/ZarPrune/Evolved/E_<sha>.lean with the candidate source verbatim.
Entries: 1.
-/
set_option autoImplicit false

namespace ZarPrune

/-- Every accepted evolved prune, OR-ed (`Prune.never` while the ledger is empty). -/
def evolved (P : Params) : Prune P :=
  Prune.ofList P [Evolved.E_c285948723e7.candidate P]

end ZarPrune
